/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */
import type {
  ApiErrorResponse,
  CheckRiskBody,
  GetRiskResponse
} from './models';


/**
 * This is Vouchsafe's headline Risk API.

It gives you an instant picture of the identity fraud risk a customer represents, powered by our real-time fraud intelligence network and premium partner data.

Pass the information you have about a customer, and Vouchsafe will scan our network for signs that an identity might be stolen, synthetic or otherwise risky, using verification data and shared reports made by other businesses using the platform.

You can also run premium `enrichments`:

- `CREDIT_BUREAU` will look for authoritative evidence of a claimed idenity and address in official and semi-official databases from around the world, which you can use as an FCA-compliant eKYC onboarding process.
- `ONLINE_FOOTPRINT` will analyse the identity's digital and online history, to determine if it is likely to be legitimate or recently made-up.
- `AML` will search over [280 global databases](https://vouchsafe.id/coverage/) of high-risk entities connected to financial or economic crime, including sanctions, watchlists and politically exposed people. It also enrols the person in ongoing monitoring, reported as `alerts_enabled_at`.
- `NFD` will search the Cifas National Fraud Database to see if the identity is known to be associated with fraud

The more checks you turn on, the more complete the data you send needs to be.

This endpoint always returns a `risk_score` between 0 and 100, and a `recommendation` based on that risk, along with extensive metadata so you can explore the discovered trust and risk signals.

This endpoint can form the basis of a transaction monitoring or data-driven KYC/AML system.

### Recommendations

Our Risk API returns one of three recommendations: `CLEAR`, `REVIEW`, and `REJECT`.

### Face scan

The endpoint accepts an optional `face_scan` — a live selfie or liveness image
(JPEG or PNG, max 10 MB). When provided, Radar runs `face_linked_to_multiple_identities`
— checking whether this face has been submitted under different names in the network.
Without it, that check returns `NOT_PERFORMED`.

### Address

When the credit bureau enrichment is turned on, a structured `address` is required. This should be taken from the results returned by the [`GET /postcode` endpoint](https://app.vouchsafe.id/docs/operations/SearchPostcode).

### Sandbox

In sandbox mode, `email` picks the recommendation you get back.

| `email` | Recommendation |
|---|---|
| contains `+reject` | `REJECT` |
| contains `+review` | `REVIEW` |
| anything else | `CLEAR` |

The response echoes your input and includes only the enrichments you requested.

Requested enrichments are shaped to match the outcome:

- CLEAR: all pass
- REVIEW: only the last requested enrichment fails
- REJECT: all fail

To return a record you can open in the sandbox dashboard, use `dwebb@email.com` (`CLEAR`), `jdoe@email.com` (`REVIEW`), or `eroberts@email.com` (`REJECT`).
 */
export type checkRiskResponse201 = {
  data: GetRiskResponse
  status: 201
}

export type checkRiskResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type checkRiskResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type checkRiskResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type checkRiskResponse405 = {
  data: ApiErrorResponse
  status: 405
}

export type checkRiskResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type checkRiskResponseSuccess = (checkRiskResponse201) & {
  headers: Headers;
};
export type checkRiskResponseError = (checkRiskResponse400 | checkRiskResponse401 | checkRiskResponse403 | checkRiskResponse405 | checkRiskResponse422) & {
  headers: Headers;
};

export type checkRiskResponse = (checkRiskResponseSuccess | checkRiskResponseError)

export const getCheckRiskUrl = () => {


  

  return `https://app.vouchsafe.id/api/v2/risk`
}

export const checkRisk = async (checkRiskBody: CheckRiskBody, options?: RequestInit): Promise<checkRiskResponse> => {
    const formData = new FormData();
formData.append(`first_name`, checkRiskBody.first_name);
formData.append(`last_name`, checkRiskBody.last_name);
formData.append(`email`, checkRiskBody.email);
formData.append(`date_of_birth`, checkRiskBody.date_of_birth);
if(checkRiskBody.enrichments !== undefined) {
 formData.append(`enrichments`, checkRiskBody.enrichments);
 }
if(checkRiskBody.address !== undefined) {
 formData.append(`address`, checkRiskBody.address);
 }
if(checkRiskBody.phone !== undefined) {
 formData.append(`phone`, checkRiskBody.phone);
 }
if(checkRiskBody.thresholds !== undefined) {
 formData.append(`thresholds`, checkRiskBody.thresholds);
 }
if(checkRiskBody.face_scan !== undefined) {
 formData.append(`face_scan`, checkRiskBody.face_scan);
 }

  const res = await fetch(getCheckRiskUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: checkRiskResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as checkRiskResponse
}



