/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */
import type { FailedReason } from './failedReason';

export interface ApiErrorResponse {
  status_code: number;
  message: string;
  error_detail?: unknown;
  failedReason?: FailedReason;
}
