/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */

export type CheckRiskBody = {
  /** Given name(s). Required. */
  first_name: string;
  /** Family name. Required. */
  last_name: string;
  /** Email address. Required. */
  email: string;
  /** Date of birth in YYYY-MM-DD format. Required. */
  date_of_birth: string;
  /** JSON-encoded array of optional enrichment checks to run.
Accepted values: `"CREDIT_BUREAU"`, `"ONLINE_FOOTPRINT"`, `"AML"`. */
  enrichments?: string;
  /** JSON-encoded address. Required when `enrichments` includes `"CREDIT_BUREAU"`.

The address must include `residence_number` (or `building_name`), `postcode`, `city`, and `country_code`. Providing `street` is optional, but omitting it may reduce match rates.

Expected shape:
```json
{
  "residence_number": "10",
  "building_name": null,
  "street": "Downing St",
  "city": "London",
  "postcode": "SW1A 2AA",
  "region": null,
  "country_code": "GB"
}
``` */
  address?: string;
  /** Phone number in E.164 format. Optional.

Recommended when `enrichments` includes `ONLINE_FOOTPRINT` as it improves match rates.
For `CREDIT_BUREAU` checks, providing a UK phone number can improve match rates by enabling matching against mobile data. */
  phone?: string;
  /** JSON-encoded thresholds object. Used to set the pass/fail threshold for `ONLINE_FOOTPRINT` and `AML` checks, otherwise defaulting to 50 and 96 respectively. */
  thresholds?: string;
  /** Face scan image (JPEG or PNG, max 10 MB). Optional binary file field. */
  face_scan?: Blob;
};
