/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */
import type { CheckState } from './checkState';
import type { Reason } from './reason';

export interface CheckResult {
  state: CheckState;
  reason?: Reason;
}
