/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */
import type { CheckState } from './checkState';
import type { RecordCreditBureauVerificationChecksCheckResult } from './recordCreditBureauVerificationChecksCheckResult';

export interface CreditBureauVerificationReport {
  state: CheckState;
  checks: RecordCreditBureauVerificationChecksCheckResult;
}
