/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */

export interface PublicAddressV2 {
  /** House or flat number, e.g. "10" or "Flat 1". */
  residence_number?: string;
  /** House or building name, e.g. "Rose Cottage". */
  building_name?: string;
  street?: string;
  city?: string;
  postcode?: string;
  country?: string;
  /** State, province, or county. */
  region?: string;
  /** ISO 3166-1 alpha-2 country code. */
  country_code?: string;
}
