/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */

export type Reason = 'INVALID_POSTCODE' | 'INVALID_ADDRESS' | 'MED_MATCH_PERSON_AT_ADDRESS' | 'LOW_MATCH_PERSON_AT_ADDRESS' | 'PARTIAL_ADDRESS_MATCH' | 'WEAK_IDENTITY_WITH_FULL_ADDRESS' | 'DOB_NOT_MATCHED' | 'DOB_FUZZY_MATCH' | 'NO_DOB_DATA' | 'NO_IDENTITY_MATCH' | 'NO_RESIDENCY_MATCH';