/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */
import type { CheckResult } from './checkResult';

/**
 * Construct a type with a set of properties K of type T
 */
export interface RecordAmlVerificationChecksCheckResult {
  AML_SANCTIONS_CHECK: CheckResult;
}
