/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs (V2)
 * Vouchsafe V2 API — experimental endpoints.
 * OpenAPI spec version: 2.0.0
 */
import type { RiskMetadataThresholds } from './riskMetadataThresholds';

export interface RiskMetadata {
  /** Effective score thresholds used for the optional enrichment checks. */
  thresholds?: RiskMetadataThresholds;
}
