/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  GetArtefactsResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    GetArtefactsResponseFromJSON,
    GetArtefactsResponseToJSON,
} from '../models/index';

export interface GetArtefactRequest {
    artefactKey: string;
}

/**
 * 
 */
export class ArtefactsApi extends runtime.BaseAPI {

    /**
     * Get an artefact download link.  For security reasons, other endpoints (e.g. `GET /verifications/{id}`) may return only an `artefact_key`. Use this endpoint to exchange that key for a **time-limited pre-signed URL** that can be used to download the file.  Vouchsafe will respond with: - the requested `artefact_key` - a `download_url` (pre-signed and time-limited) - an `expires_at` timestamp (ISO 8601, UTC)  **Note:** The `download_url` will stop working after `expires_at`. If it expires, request a new URL using this endpoint.
     */
    async getArtefactRaw(requestParameters: GetArtefactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetArtefactsResponse>> {
        if (requestParameters['artefactKey'] == null) {
            throw new runtime.RequiredError(
                'artefactKey',
                'Required parameter "artefactKey" was null or undefined when calling getArtefact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/artefacts/{artefact_key}`;
        urlPath = urlPath.replace(`{${"artefact_key"}}`, encodeURIComponent(String(requestParameters['artefactKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetArtefactsResponseFromJSON(jsonValue));
    }

    /**
     * Get an artefact download link.  For security reasons, other endpoints (e.g. `GET /verifications/{id}`) may return only an `artefact_key`. Use this endpoint to exchange that key for a **time-limited pre-signed URL** that can be used to download the file.  Vouchsafe will respond with: - the requested `artefact_key` - a `download_url` (pre-signed and time-limited) - an `expires_at` timestamp (ISO 8601, UTC)  **Note:** The `download_url` will stop working after `expires_at`. If it expires, request a new URL using this endpoint.
     */
    async getArtefact(requestParameters: GetArtefactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetArtefactsResponse> {
        const response = await this.getArtefactRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
