/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CreateDigitalIdSessionInput,
  CreateDigitalIdSessionResponse,
  DigitalIdSession,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CreateDigitalIdSessionInputFromJSON,
    CreateDigitalIdSessionInputToJSON,
    CreateDigitalIdSessionResponseFromJSON,
    CreateDigitalIdSessionResponseToJSON,
    DigitalIdSessionFromJSON,
    DigitalIdSessionToJSON,
} from '../models/index';

export interface CreateSessionRequest {
    createDigitalIdSessionInput: CreateDigitalIdSessionInput;
}

export interface GetSessionRequest {
    id: string;
}

export interface ListSessionsRequest {
    workflowId?: string;
    status?: ListSessionsStatusEnum;
    providerId?: string;
    limit?: number;
    offset?: number;
    createdAfter?: string;
    createdBefore?: string;
}

/**
 * 
 */
export class DigitalIDApi extends runtime.BaseAPI {

    /**
     * <div style=\"background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;\"> <strong style=\"color: #c62828;\">Experimental:</strong> This feature is brand new. <a href=\"https://vouchsafe.id/contact\">Contact us</a> to set it up. </div>  Create a new Digital ID verification session.  This endpoint initiates a new identity verification session using Digital ID providers. The session will generate a unique URL that can be used to start the verification flow.  You can optionally provide known claims about the user (e.g., their email, name, date of birth) to pre-populate the verification form and improve the user experience.  The session will expire after a set period if not completed.
     */
    async createSessionRaw(requestParameters: CreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDigitalIdSessionResponse>> {
        if (requestParameters['createDigitalIdSessionInput'] == null) {
            throw new runtime.RequiredError(
                'createDigitalIdSessionInput',
                'Required parameter "createDigitalIdSessionInput" was null or undefined when calling createSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/digital-id/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDigitalIdSessionInputToJSON(requestParameters['createDigitalIdSessionInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDigitalIdSessionResponseFromJSON(jsonValue));
    }

    /**
     * <div style=\"background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;\"> <strong style=\"color: #c62828;\">Experimental:</strong> This feature is brand new. <a href=\"https://vouchsafe.id/contact\">Contact us</a> to set it up. </div>  Create a new Digital ID verification session.  This endpoint initiates a new identity verification session using Digital ID providers. The session will generate a unique URL that can be used to start the verification flow.  You can optionally provide known claims about the user (e.g., their email, name, date of birth) to pre-populate the verification form and improve the user experience.  The session will expire after a set period if not completed.
     */
    async createSession(requestParameters: CreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDigitalIdSessionResponse> {
        const response = await this.createSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <div style=\"background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;\"> <strong style=\"color: #c62828;\">Experimental:</strong> This feature is brand new. <a href=\"https://vouchsafe.id/contact\">Contact us</a> to set it up. </div>  Get a Digital ID verification session by ID.  Retrieve details of a specific Digital ID verification session. Returns the session status, verified claims, enrichments (including Radar risk assessment and smart lookup results), and other session metadata.  The `enrichments` field will be `null` until the session reaches `completed` status.  Returns a 404 error if the session does not exist or does not belong to your team.
     */
    async getSessionRaw(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DigitalIdSession>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/digital-id/sessions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DigitalIdSessionFromJSON(jsonValue));
    }

    /**
     * <div style=\"background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;\"> <strong style=\"color: #c62828;\">Experimental:</strong> This feature is brand new. <a href=\"https://vouchsafe.id/contact\">Contact us</a> to set it up. </div>  Get a Digital ID verification session by ID.  Retrieve details of a specific Digital ID verification session. Returns the session status, verified claims, enrichments (including Radar risk assessment and smart lookup results), and other session metadata.  The `enrichments` field will be `null` until the session reaches `completed` status.  Returns a 404 error if the session does not exist or does not belong to your team.
     */
    async getSession(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DigitalIdSession> {
        const response = await this.getSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <div style=\"background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;\"> <strong style=\"color: #c62828;\">Experimental:</strong> This feature is brand new. <a href=\"https://vouchsafe.id/contact\">Contact us</a> to set it up. </div>  List Digital ID verification sessions.  Retrieve a list of Digital ID verification sessions for your team. You can filter sessions by workflow, status, provider, or creation date.  Each session includes verified claims and enrichments (Radar risk assessment and smart lookup results) when available. The `enrichments` field will be `null` for sessions that haven\'t completed.  Use pagination parameters (`limit` and `offset`) to page through large result sets.
     */
    async listSessionsRaw(requestParameters: ListSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DigitalIdSession>>> {
        const queryParameters: any = {};

        if (requestParameters['workflowId'] != null) {
            queryParameters['workflow_id'] = requestParameters['workflowId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['providerId'] != null) {
            queryParameters['provider_id'] = requestParameters['providerId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['createdAfter'] != null) {
            queryParameters['created_after'] = requestParameters['createdAfter'];
        }

        if (requestParameters['createdBefore'] != null) {
            queryParameters['created_before'] = requestParameters['createdBefore'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/digital-id/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DigitalIdSessionFromJSON));
    }

    /**
     * <div style=\"background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;\"> <strong style=\"color: #c62828;\">Experimental:</strong> This feature is brand new. <a href=\"https://vouchsafe.id/contact\">Contact us</a> to set it up. </div>  List Digital ID verification sessions.  Retrieve a list of Digital ID verification sessions for your team. You can filter sessions by workflow, status, provider, or creation date.  Each session includes verified claims and enrichments (Radar risk assessment and smart lookup results) when available. The `enrichments` field will be `null` for sessions that haven\'t completed.  Use pagination parameters (`limit` and `offset`) to page through large result sets.
     */
    async listSessions(requestParameters: ListSessionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DigitalIdSession>> {
        const response = await this.listSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListSessionsStatusEnum = {
    Created: 'created',
    Started: 'started',
    Verifying: 'verifying',
    Verified: 'verified',
    Enriching: 'enriching',
    Completed: 'completed',
    Failed: 'failed',
    Expired: 'expired',
    Cancelled: 'cancelled'
} as const;
export type ListSessionsStatusEnum = typeof ListSessionsStatusEnum[keyof typeof ListSessionsStatusEnum];
