/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { AmlMatchApiPropertiesBirthCountry } from './amlMatchApiPropertiesBirthCountry';
import type { AmlMatchApiPropertiesBirthPlace } from './amlMatchApiPropertiesBirthPlace';
import type { AmlMatchApiPropertiesCountry } from './amlMatchApiPropertiesCountry';
import type { AmlMatchApiPropertiesNotes } from './amlMatchApiPropertiesNotes';
import type { AmlMatchApiPropertiesPosition } from './amlMatchApiPropertiesPosition';

export type AmlMatchApiProperties = {
  /** Country of birth of the entity. */
  birth_country: AmlMatchApiPropertiesBirthCountry;
  /** Place of birth of the entity. */
  birth_place: AmlMatchApiPropertiesBirthPlace;
  /** Date of birth of the entity. */
  birth_date: string;
  /** Known positions or roles held by the entity. */
  position: AmlMatchApiPropertiesPosition;
  /** Countries associated with the entity. */
  country: AmlMatchApiPropertiesCountry;
  /** Freeform notes associated with the entity. */
  notes: AmlMatchApiPropertiesNotes;
};
