/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAmlCheckDetails } from './ApiAmlCheckDetails';
import {
    ApiAmlCheckDetailsFromJSON,
    ApiAmlCheckDetailsFromJSONTyped,
    ApiAmlCheckDetailsToJSON,
    ApiAmlCheckDetailsToJSONTyped,
} from './ApiAmlCheckDetails';

/**
 * 
 * @export
 * @interface ApiAmlCheck
 */
export interface ApiAmlCheck {
    /**
     * 
     * @type {ApiAmlCheckDetails}
     * @memberof ApiAmlCheck
     */
    details: ApiAmlCheckDetails;
    /**
     * 
     * @type {string}
     * @memberof ApiAmlCheck
     */
    outcome: ApiAmlCheckOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiAmlCheck
     */
    check: ApiAmlCheckCheckEnum;
}


/**
 * @export
 */
export const ApiAmlCheckOutcomeEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Error: 'error'
} as const;
export type ApiAmlCheckOutcomeEnum = typeof ApiAmlCheckOutcomeEnum[keyof typeof ApiAmlCheckOutcomeEnum];

/**
 * @export
 */
export const ApiAmlCheckCheckEnum = {
    AmlSanctions: 'aml_sanctions'
} as const;
export type ApiAmlCheckCheckEnum = typeof ApiAmlCheckCheckEnum[keyof typeof ApiAmlCheckCheckEnum];


/**
 * Check if a given object implements the ApiAmlCheck interface.
 */
export function instanceOfApiAmlCheck(value: object): value is ApiAmlCheck {
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('check' in value) || value['check'] === undefined) return false;
    return true;
}

export function ApiAmlCheckFromJSON(json: any): ApiAmlCheck {
    return ApiAmlCheckFromJSONTyped(json, false);
}

export function ApiAmlCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAmlCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'details': ApiAmlCheckDetailsFromJSON(json['details']),
        'outcome': json['outcome'],
        'check': json['check'],
    };
}

export function ApiAmlCheckToJSON(json: any): ApiAmlCheck {
    return ApiAmlCheckToJSONTyped(json, false);
}

export function ApiAmlCheckToJSONTyped(value?: ApiAmlCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': ApiAmlCheckDetailsToJSON(value['details']),
        'outcome': value['outcome'],
        'check': value['check'],
    };
}

