/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAmlCheckDetailsMatchesInnerProperties } from './ApiAmlCheckDetailsMatchesInnerProperties';
import {
    ApiAmlCheckDetailsMatchesInnerPropertiesFromJSON,
    ApiAmlCheckDetailsMatchesInnerPropertiesFromJSONTyped,
    ApiAmlCheckDetailsMatchesInnerPropertiesToJSON,
    ApiAmlCheckDetailsMatchesInnerPropertiesToJSONTyped,
} from './ApiAmlCheckDetailsMatchesInnerProperties';

/**
 * 
 * @export
 * @interface ApiAmlCheckDetailsMatchesInner
 */
export interface ApiAmlCheckDetailsMatchesInner {
    /**
     * 
     * @type {ApiAmlCheckDetailsMatchesInnerProperties}
     * @memberof ApiAmlCheckDetailsMatchesInner
     */
    properties: ApiAmlCheckDetailsMatchesInnerProperties;
    /**
     * 
     * @type {string}
     * @memberof ApiAmlCheckDetailsMatchesInner
     */
    last_seen?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAmlCheckDetailsMatchesInner
     */
    first_seen?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiAmlCheckDetailsMatchesInner
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof ApiAmlCheckDetailsMatchesInner
     */
    caption: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAmlCheckDetailsMatchesInner
     */
    id: string;
}

/**
 * Check if a given object implements the ApiAmlCheckDetailsMatchesInner interface.
 */
export function instanceOfApiAmlCheckDetailsMatchesInner(value: object): value is ApiAmlCheckDetailsMatchesInner {
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ApiAmlCheckDetailsMatchesInnerFromJSON(json: any): ApiAmlCheckDetailsMatchesInner {
    return ApiAmlCheckDetailsMatchesInnerFromJSONTyped(json, false);
}

export function ApiAmlCheckDetailsMatchesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAmlCheckDetailsMatchesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': ApiAmlCheckDetailsMatchesInnerPropertiesFromJSON(json['properties']),
        'last_seen': json['last_seen'] == null ? undefined : json['last_seen'],
        'first_seen': json['first_seen'] == null ? undefined : json['first_seen'],
        'score': json['score'],
        'caption': json['caption'],
        'id': json['id'],
    };
}

export function ApiAmlCheckDetailsMatchesInnerToJSON(json: any): ApiAmlCheckDetailsMatchesInner {
    return ApiAmlCheckDetailsMatchesInnerToJSONTyped(json, false);
}

export function ApiAmlCheckDetailsMatchesInnerToJSONTyped(value?: ApiAmlCheckDetailsMatchesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'properties': ApiAmlCheckDetailsMatchesInnerPropertiesToJSON(value['properties']),
        'last_seen': value['last_seen'],
        'first_seen': value['first_seen'],
        'score': value['score'],
        'caption': value['caption'],
        'id': value['id'],
    };
}

