/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVideoSelfieCheckArtefactsInner } from './ApiVideoSelfieCheckArtefactsInner';
import {
    ApiVideoSelfieCheckArtefactsInnerFromJSON,
    ApiVideoSelfieCheckArtefactsInnerFromJSONTyped,
    ApiVideoSelfieCheckArtefactsInnerToJSON,
    ApiVideoSelfieCheckArtefactsInnerToJSONTyped,
} from './ApiVideoSelfieCheckArtefactsInner';
import type { ApiBankAccountEvidenceItemValidations } from './ApiBankAccountEvidenceItemValidations';
import {
    ApiBankAccountEvidenceItemValidationsFromJSON,
    ApiBankAccountEvidenceItemValidationsFromJSONTyped,
    ApiBankAccountEvidenceItemValidationsToJSON,
    ApiBankAccountEvidenceItemValidationsToJSONTyped,
} from './ApiBankAccountEvidenceItemValidations';
import type { ApiBankAccountEvidenceItemExtractedDetails } from './ApiBankAccountEvidenceItemExtractedDetails';
import {
    ApiBankAccountEvidenceItemExtractedDetailsFromJSON,
    ApiBankAccountEvidenceItemExtractedDetailsFromJSONTyped,
    ApiBankAccountEvidenceItemExtractedDetailsToJSON,
    ApiBankAccountEvidenceItemExtractedDetailsToJSONTyped,
} from './ApiBankAccountEvidenceItemExtractedDetails';

/**
 * 
 * @export
 * @interface ApiBankAccountEvidenceItem
 */
export interface ApiBankAccountEvidenceItem {
    /**
     * 
     * @type {ApiBankAccountEvidenceItemExtractedDetails}
     * @memberof ApiBankAccountEvidenceItem
     */
    extracted_details: ApiBankAccountEvidenceItemExtractedDetails;
    /**
     * 
     * @type {Array<ApiVideoSelfieCheckArtefactsInner>}
     * @memberof ApiBankAccountEvidenceItem
     */
    artefacts?: Array<ApiVideoSelfieCheckArtefactsInner>;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItem
     */
    evidence_type: ApiBankAccountEvidenceItemEvidenceTypeEnum;
    /**
     * 
     * @type {ApiBankAccountEvidenceItemValidations}
     * @memberof ApiBankAccountEvidenceItem
     */
    validations: ApiBankAccountEvidenceItemValidations;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItem
     */
    created_at?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiBankAccountEvidenceItem
     */
    total_attempts?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItem
     */
    outcome?: ApiBankAccountEvidenceItemOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItem
     */
    step: ApiBankAccountEvidenceItemStepEnum;
}


/**
 * @export
 */
export const ApiBankAccountEvidenceItemEvidenceTypeEnum = {
    OpenBanking: 'open_banking'
} as const;
export type ApiBankAccountEvidenceItemEvidenceTypeEnum = typeof ApiBankAccountEvidenceItemEvidenceTypeEnum[keyof typeof ApiBankAccountEvidenceItemEvidenceTypeEnum];

/**
 * @export
 */
export const ApiBankAccountEvidenceItemOutcomeEnum = {
    InProgress: 'in_progress',
    Pass: 'pass',
    Fail: 'fail'
} as const;
export type ApiBankAccountEvidenceItemOutcomeEnum = typeof ApiBankAccountEvidenceItemOutcomeEnum[keyof typeof ApiBankAccountEvidenceItemOutcomeEnum];

/**
 * @export
 */
export const ApiBankAccountEvidenceItemStepEnum = {
    BankAccount: 'bank_account'
} as const;
export type ApiBankAccountEvidenceItemStepEnum = typeof ApiBankAccountEvidenceItemStepEnum[keyof typeof ApiBankAccountEvidenceItemStepEnum];


/**
 * Check if a given object implements the ApiBankAccountEvidenceItem interface.
 */
export function instanceOfApiBankAccountEvidenceItem(value: object): value is ApiBankAccountEvidenceItem {
    if (!('extracted_details' in value) || value['extracted_details'] === undefined) return false;
    if (!('evidence_type' in value) || value['evidence_type'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function ApiBankAccountEvidenceItemFromJSON(json: any): ApiBankAccountEvidenceItem {
    return ApiBankAccountEvidenceItemFromJSONTyped(json, false);
}

export function ApiBankAccountEvidenceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBankAccountEvidenceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'extracted_details': ApiBankAccountEvidenceItemExtractedDetailsFromJSON(json['extracted_details']),
        'artefacts': json['artefacts'] == null ? undefined : ((json['artefacts'] as Array<any>).map(ApiVideoSelfieCheckArtefactsInnerFromJSON)),
        'evidence_type': json['evidence_type'],
        'validations': ApiBankAccountEvidenceItemValidationsFromJSON(json['validations']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'total_attempts': json['total_attempts'] == null ? undefined : json['total_attempts'],
        'outcome': json['outcome'] == null ? undefined : json['outcome'],
        'step': json['step'],
    };
}

export function ApiBankAccountEvidenceItemToJSON(json: any): ApiBankAccountEvidenceItem {
    return ApiBankAccountEvidenceItemToJSONTyped(json, false);
}

export function ApiBankAccountEvidenceItemToJSONTyped(value?: ApiBankAccountEvidenceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extracted_details': ApiBankAccountEvidenceItemExtractedDetailsToJSON(value['extracted_details']),
        'artefacts': value['artefacts'] == null ? undefined : ((value['artefacts'] as Array<any>).map(ApiVideoSelfieCheckArtefactsInnerToJSON)),
        'evidence_type': value['evidence_type'],
        'validations': ApiBankAccountEvidenceItemValidationsToJSON(value['validations']),
        'created_at': value['created_at'],
        'total_attempts': value['total_attempts'],
        'outcome': value['outcome'],
        'step': value['step'],
    };
}

