/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiBankAccountEvidenceItemExtractedDetails
 */
export interface ApiBankAccountEvidenceItemExtractedDetails {
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    first_line_of_address?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    date_of_birth?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    last_name: string;
    /**
     * 
     * @type {any}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    transaction_data: any | null;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    account_type: ApiBankAccountEvidenceItemExtractedDetailsAccountTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiBankAccountEvidenceItemExtractedDetails
     */
    bank_name: string;
}


/**
 * @export
 */
export const ApiBankAccountEvidenceItemExtractedDetailsAccountTypeEnum = {
    CashCurrent: 'cash:current',
    Savings: 'savings'
} as const;
export type ApiBankAccountEvidenceItemExtractedDetailsAccountTypeEnum = typeof ApiBankAccountEvidenceItemExtractedDetailsAccountTypeEnum[keyof typeof ApiBankAccountEvidenceItemExtractedDetailsAccountTypeEnum];


/**
 * Check if a given object implements the ApiBankAccountEvidenceItemExtractedDetails interface.
 */
export function instanceOfApiBankAccountEvidenceItemExtractedDetails(value: object): value is ApiBankAccountEvidenceItemExtractedDetails {
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('transaction_data' in value) || value['transaction_data'] === undefined) return false;
    if (!('account_type' in value) || value['account_type'] === undefined) return false;
    if (!('bank_name' in value) || value['bank_name'] === undefined) return false;
    return true;
}

export function ApiBankAccountEvidenceItemExtractedDetailsFromJSON(json: any): ApiBankAccountEvidenceItemExtractedDetails {
    return ApiBankAccountEvidenceItemExtractedDetailsFromJSONTyped(json, false);
}

export function ApiBankAccountEvidenceItemExtractedDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBankAccountEvidenceItemExtractedDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'first_line_of_address': json['first_line_of_address'] == null ? undefined : json['first_line_of_address'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'transaction_data': json['transaction_data'],
        'account_type': json['account_type'],
        'bank_name': json['bank_name'],
    };
}

export function ApiBankAccountEvidenceItemExtractedDetailsToJSON(json: any): ApiBankAccountEvidenceItemExtractedDetails {
    return ApiBankAccountEvidenceItemExtractedDetailsToJSONTyped(json, false);
}

export function ApiBankAccountEvidenceItemExtractedDetailsToJSONTyped(value?: ApiBankAccountEvidenceItemExtractedDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postcode': value['postcode'],
        'first_line_of_address': value['first_line_of_address'],
        'date_of_birth': value['date_of_birth'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'transaction_data': value['transaction_data'],
        'account_type': value['account_type'],
        'bank_name': value['bank_name'],
    };
}

