/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPhotoIdEvidenceItemExtractedDetails
 */
export interface ApiPhotoIdEvidenceItemExtractedDetails {
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    first_line_of_address?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    date_of_birth?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    smart_card_number?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    mrz_code?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    icao_format?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    issuing_country?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    issue_date?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    expiration_date?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPhotoIdEvidenceItemExtractedDetails
     */
    document_number: string;
}

/**
 * Check if a given object implements the ApiPhotoIdEvidenceItemExtractedDetails interface.
 */
export function instanceOfApiPhotoIdEvidenceItemExtractedDetails(value: object): value is ApiPhotoIdEvidenceItemExtractedDetails {
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('document_number' in value) || value['document_number'] === undefined) return false;
    return true;
}

export function ApiPhotoIdEvidenceItemExtractedDetailsFromJSON(json: any): ApiPhotoIdEvidenceItemExtractedDetails {
    return ApiPhotoIdEvidenceItemExtractedDetailsFromJSONTyped(json, false);
}

export function ApiPhotoIdEvidenceItemExtractedDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPhotoIdEvidenceItemExtractedDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'first_line_of_address': json['first_line_of_address'] == null ? undefined : json['first_line_of_address'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'smart_card_number': json['smart_card_number'] == null ? undefined : json['smart_card_number'],
        'mrz_code': json['mrz_code'] == null ? undefined : json['mrz_code'],
        'icao_format': json['icao_format'] == null ? undefined : json['icao_format'],
        'issuing_country': json['issuing_country'] == null ? undefined : json['issuing_country'],
        'issue_date': json['issue_date'] == null ? undefined : json['issue_date'],
        'expiration_date': json['expiration_date'] == null ? undefined : json['expiration_date'],
        'document_number': json['document_number'],
    };
}

export function ApiPhotoIdEvidenceItemExtractedDetailsToJSON(json: any): ApiPhotoIdEvidenceItemExtractedDetails {
    return ApiPhotoIdEvidenceItemExtractedDetailsToJSONTyped(json, false);
}

export function ApiPhotoIdEvidenceItemExtractedDetailsToJSONTyped(value?: ApiPhotoIdEvidenceItemExtractedDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postcode': value['postcode'],
        'first_line_of_address': value['first_line_of_address'],
        'date_of_birth': value['date_of_birth'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'smart_card_number': value['smart_card_number'],
        'mrz_code': value['mrz_code'],
        'icao_format': value['icao_format'],
        'issuing_country': value['issuing_country'],
        'issue_date': value['issue_date'],
        'expiration_date': value['expiration_date'],
        'document_number': value['document_number'],
    };
}

