/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth } from './ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth';
import {
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSONTyped,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSONTyped,
} from './ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth';

/**
 * 
 * @export
 * @interface ApiReviewUserCheckValidations
 */
export interface ApiReviewUserCheckValidations {
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiReviewUserCheckValidations
     */
    referee_confirmed_date_of_birth?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiReviewUserCheckValidations
     */
    referee_confirmed_name?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiReviewUserCheckValidations
     */
    referee_confirmed_photo?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
}

/**
 * Check if a given object implements the ApiReviewUserCheckValidations interface.
 */
export function instanceOfApiReviewUserCheckValidations(value: object): value is ApiReviewUserCheckValidations {
    return true;
}

export function ApiReviewUserCheckValidationsFromJSON(json: any): ApiReviewUserCheckValidations {
    return ApiReviewUserCheckValidationsFromJSONTyped(json, false);
}

export function ApiReviewUserCheckValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiReviewUserCheckValidations {
    if (json == null) {
        return json;
    }
    return {
        
        'referee_confirmed_date_of_birth': json['referee_confirmed_date_of_birth'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_confirmed_date_of_birth']),
        'referee_confirmed_name': json['referee_confirmed_name'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_confirmed_name']),
        'referee_confirmed_photo': json['referee_confirmed_photo'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_confirmed_photo']),
    };
}

export function ApiReviewUserCheckValidationsToJSON(json: any): ApiReviewUserCheckValidations {
    return ApiReviewUserCheckValidationsToJSONTyped(json, false);
}

export function ApiReviewUserCheckValidationsToJSONTyped(value?: ApiReviewUserCheckValidations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referee_confirmed_date_of_birth': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_confirmed_date_of_birth']),
        'referee_confirmed_name': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_confirmed_name']),
        'referee_confirmed_photo': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_confirmed_photo']),
    };
}

