/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRadarCheckDetails } from './ApiRadarCheckDetails';
import {
    ApiRadarCheckDetailsFromJSON,
    ApiRadarCheckDetailsFromJSONTyped,
    ApiRadarCheckDetailsToJSON,
    ApiRadarCheckDetailsToJSONTyped,
} from './ApiRadarCheckDetails';

/**
 * 
 * @export
 * @interface ApiRadarCheck
 */
export interface ApiRadarCheck {
    /**
     * 
     * @type {ApiRadarCheckDetails}
     * @memberof ApiRadarCheck
     */
    details: ApiRadarCheckDetails;
    /**
     * 
     * @type {string}
     * @memberof ApiRadarCheck
     */
    outcome: ApiRadarCheckOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiRadarCheck
     */
    check: ApiRadarCheckCheckEnum;
}


/**
 * @export
 */
export const ApiRadarCheckOutcomeEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Error: 'error'
} as const;
export type ApiRadarCheckOutcomeEnum = typeof ApiRadarCheckOutcomeEnum[keyof typeof ApiRadarCheckOutcomeEnum];

/**
 * @export
 */
export const ApiRadarCheckCheckEnum = {
    Radar: 'radar'
} as const;
export type ApiRadarCheckCheckEnum = typeof ApiRadarCheckCheckEnum[keyof typeof ApiRadarCheckCheckEnum];


/**
 * Check if a given object implements the ApiRadarCheck interface.
 */
export function instanceOfApiRadarCheck(value: object): value is ApiRadarCheck {
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('check' in value) || value['check'] === undefined) return false;
    return true;
}

export function ApiRadarCheckFromJSON(json: any): ApiRadarCheck {
    return ApiRadarCheckFromJSONTyped(json, false);
}

export function ApiRadarCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRadarCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'details': ApiRadarCheckDetailsFromJSON(json['details']),
        'outcome': json['outcome'],
        'check': json['check'],
    };
}

export function ApiRadarCheckToJSON(json: any): ApiRadarCheck {
    return ApiRadarCheckToJSONTyped(json, false);
}

export function ApiRadarCheckToJSONTyped(value?: ApiRadarCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': ApiRadarCheckDetailsToJSON(value['details']),
        'outcome': value['outcome'],
        'check': value['check'],
    };
}

