/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiReviewUserCheckValidations } from './ApiReviewUserCheckValidations';
import {
    ApiReviewUserCheckValidationsFromJSON,
    ApiReviewUserCheckValidationsFromJSONTyped,
    ApiReviewUserCheckValidationsToJSON,
    ApiReviewUserCheckValidationsToJSONTyped,
} from './ApiReviewUserCheckValidations';

/**
 * 
 * @export
 * @interface ApiReviewUserCheck
 */
export interface ApiReviewUserCheck {
    /**
     * 
     * @type {ApiReviewUserCheckValidations}
     * @memberof ApiReviewUserCheck
     */
    validations: ApiReviewUserCheckValidations;
    /**
     * 
     * @type {string}
     * @memberof ApiReviewUserCheck
     */
    created_at?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiReviewUserCheck
     */
    total_attempts?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiReviewUserCheck
     */
    outcome: ApiReviewUserCheckOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiReviewUserCheck
     */
    step: ApiReviewUserCheckStepEnum;
}


/**
 * @export
 */
export const ApiReviewUserCheckOutcomeEnum = {
    InProgress: 'in_progress',
    Pass: 'pass',
    Fail: 'fail'
} as const;
export type ApiReviewUserCheckOutcomeEnum = typeof ApiReviewUserCheckOutcomeEnum[keyof typeof ApiReviewUserCheckOutcomeEnum];

/**
 * @export
 */
export const ApiReviewUserCheckStepEnum = {
    VerifyUserDetails: 'verify_user_details'
} as const;
export type ApiReviewUserCheckStepEnum = typeof ApiReviewUserCheckStepEnum[keyof typeof ApiReviewUserCheckStepEnum];


/**
 * Check if a given object implements the ApiReviewUserCheck interface.
 */
export function instanceOfApiReviewUserCheck(value: object): value is ApiReviewUserCheck {
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function ApiReviewUserCheckFromJSON(json: any): ApiReviewUserCheck {
    return ApiReviewUserCheckFromJSONTyped(json, false);
}

export function ApiReviewUserCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiReviewUserCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'validations': ApiReviewUserCheckValidationsFromJSON(json['validations']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'total_attempts': json['total_attempts'] == null ? undefined : json['total_attempts'],
        'outcome': json['outcome'],
        'step': json['step'],
    };
}

export function ApiReviewUserCheckToJSON(json: any): ApiReviewUserCheck {
    return ApiReviewUserCheckToJSONTyped(json, false);
}

export function ApiReviewUserCheckToJSONTyped(value?: ApiReviewUserCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validations': ApiReviewUserCheckValidationsToJSON(value['validations']),
        'created_at': value['created_at'],
        'total_attempts': value['total_attempts'],
        'outcome': value['outcome'],
        'step': value['step'],
    };
}

