/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRadarCheckDetailsValidations } from './ApiRadarCheckDetailsValidations';
import {
    ApiRadarCheckDetailsValidationsFromJSON,
    ApiRadarCheckDetailsValidationsFromJSONTyped,
    ApiRadarCheckDetailsValidationsToJSON,
    ApiRadarCheckDetailsValidationsToJSONTyped,
} from './ApiRadarCheckDetailsValidations';

/**
 * 
 * @export
 * @interface ApiRadarCheckDetails
 */
export interface ApiRadarCheckDetails {
    /**
     * 
     * @type {ApiRadarCheckDetailsValidations}
     * @memberof ApiRadarCheckDetails
     */
    validations: ApiRadarCheckDetailsValidations;
}

/**
 * Check if a given object implements the ApiRadarCheckDetails interface.
 */
export function instanceOfApiRadarCheckDetails(value: object): value is ApiRadarCheckDetails {
    if (!('validations' in value) || value['validations'] === undefined) return false;
    return true;
}

export function ApiRadarCheckDetailsFromJSON(json: any): ApiRadarCheckDetails {
    return ApiRadarCheckDetailsFromJSONTyped(json, false);
}

export function ApiRadarCheckDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRadarCheckDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'validations': ApiRadarCheckDetailsValidationsFromJSON(json['validations']),
    };
}

export function ApiRadarCheckDetailsToJSON(json: any): ApiRadarCheckDetails {
    return ApiRadarCheckDetailsToJSONTyped(json, false);
}

export function ApiRadarCheckDetailsToJSONTyped(value?: ApiRadarCheckDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validations': ApiRadarCheckDetailsValidationsToJSON(value['validations']),
    };
}

