/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth } from './ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth';
import {
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSONTyped,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSONTyped,
} from './ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth';

/**
 * 
 * @export
 * @interface ApiRefereeEvidenceItemValidations
 */
export interface ApiRefereeEvidenceItemValidations {
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiRefereeEvidenceItemValidations
     */
    approved_professional_domain?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiRefereeEvidenceItemValidations
     */
    relationship_minimum_duration_met: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
}

/**
 * Check if a given object implements the ApiRefereeEvidenceItemValidations interface.
 */
export function instanceOfApiRefereeEvidenceItemValidations(value: object): value is ApiRefereeEvidenceItemValidations {
    if (!('relationship_minimum_duration_met' in value) || value['relationship_minimum_duration_met'] === undefined) return false;
    return true;
}

export function ApiRefereeEvidenceItemValidationsFromJSON(json: any): ApiRefereeEvidenceItemValidations {
    return ApiRefereeEvidenceItemValidationsFromJSONTyped(json, false);
}

export function ApiRefereeEvidenceItemValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRefereeEvidenceItemValidations {
    if (json == null) {
        return json;
    }
    return {
        
        'approved_professional_domain': json['approved_professional_domain'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['approved_professional_domain']),
        'relationship_minimum_duration_met': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['relationship_minimum_duration_met']),
    };
}

export function ApiRefereeEvidenceItemValidationsToJSON(json: any): ApiRefereeEvidenceItemValidations {
    return ApiRefereeEvidenceItemValidationsToJSONTyped(json, false);
}

export function ApiRefereeEvidenceItemValidationsToJSONTyped(value?: ApiRefereeEvidenceItemValidations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approved_professional_domain': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['approved_professional_domain']),
        'relationship_minimum_duration_met': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['relationship_minimum_duration_met']),
    };
}

