/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth } from './ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth';
import {
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSONTyped,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON,
    ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSONTyped,
} from './ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth';

/**
 * 
 * @export
 * @interface ApiSupportingDocEvidenceItemValidations
 */
export interface ApiSupportingDocEvidenceItemValidations {
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    referee_biometrics_dissimilar?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    addresses_consistent?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    dates_of_birth_consistent?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    names_consistent?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    date_fields_valid?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    tampering_signals_check?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    document_complete_and_legible?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    document_age_valid?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    document_unique?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    category_match?: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiSupportingDocEvidenceItemValidations
     */
    required_fields_extracted: ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth;
}

/**
 * Check if a given object implements the ApiSupportingDocEvidenceItemValidations interface.
 */
export function instanceOfApiSupportingDocEvidenceItemValidations(value: object): value is ApiSupportingDocEvidenceItemValidations {
    if (!('required_fields_extracted' in value) || value['required_fields_extracted'] === undefined) return false;
    return true;
}

export function ApiSupportingDocEvidenceItemValidationsFromJSON(json: any): ApiSupportingDocEvidenceItemValidations {
    return ApiSupportingDocEvidenceItemValidationsFromJSONTyped(json, false);
}

export function ApiSupportingDocEvidenceItemValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSupportingDocEvidenceItemValidations {
    if (json == null) {
        return json;
    }
    return {
        
        'referee_biometrics_dissimilar': json['referee_biometrics_dissimilar'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_biometrics_dissimilar']),
        'addresses_consistent': json['addresses_consistent'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['addresses_consistent']),
        'dates_of_birth_consistent': json['dates_of_birth_consistent'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['dates_of_birth_consistent']),
        'names_consistent': json['names_consistent'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['names_consistent']),
        'date_fields_valid': json['date_fields_valid'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['date_fields_valid']),
        'tampering_signals_check': json['tampering_signals_check'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['tampering_signals_check']),
        'document_complete_and_legible': json['document_complete_and_legible'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['document_complete_and_legible']),
        'document_age_valid': json['document_age_valid'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['document_age_valid']),
        'document_unique': json['document_unique'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['document_unique']),
        'category_match': json['category_match'] == null ? undefined : ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['category_match']),
        'required_fields_extracted': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthFromJSON(json['required_fields_extracted']),
    };
}

export function ApiSupportingDocEvidenceItemValidationsToJSON(json: any): ApiSupportingDocEvidenceItemValidations {
    return ApiSupportingDocEvidenceItemValidationsToJSONTyped(json, false);
}

export function ApiSupportingDocEvidenceItemValidationsToJSONTyped(value?: ApiSupportingDocEvidenceItemValidations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referee_biometrics_dissimilar': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_biometrics_dissimilar']),
        'addresses_consistent': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['addresses_consistent']),
        'dates_of_birth_consistent': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['dates_of_birth_consistent']),
        'names_consistent': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['names_consistent']),
        'date_fields_valid': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['date_fields_valid']),
        'tampering_signals_check': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['tampering_signals_check']),
        'document_complete_and_legible': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['document_complete_and_legible']),
        'document_age_valid': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['document_age_valid']),
        'document_unique': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['document_unique']),
        'category_match': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['category_match']),
        'required_fields_extracted': ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirthToJSON(value['required_fields_extracted']),
    };
}

