/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVideoSelfieCheckArtefactsInner } from './ApiVideoSelfieCheckArtefactsInner';
import {
    ApiVideoSelfieCheckArtefactsInnerFromJSON,
    ApiVideoSelfieCheckArtefactsInnerFromJSONTyped,
    ApiVideoSelfieCheckArtefactsInnerToJSON,
    ApiVideoSelfieCheckArtefactsInnerToJSONTyped,
} from './ApiVideoSelfieCheckArtefactsInner';
import type { ApiSupportingDocEvidenceItemValidations } from './ApiSupportingDocEvidenceItemValidations';
import {
    ApiSupportingDocEvidenceItemValidationsFromJSON,
    ApiSupportingDocEvidenceItemValidationsFromJSONTyped,
    ApiSupportingDocEvidenceItemValidationsToJSON,
    ApiSupportingDocEvidenceItemValidationsToJSONTyped,
} from './ApiSupportingDocEvidenceItemValidations';
import type { ApiSupportingDocEvidenceItemExtractedDetails } from './ApiSupportingDocEvidenceItemExtractedDetails';
import {
    ApiSupportingDocEvidenceItemExtractedDetailsFromJSON,
    ApiSupportingDocEvidenceItemExtractedDetailsFromJSONTyped,
    ApiSupportingDocEvidenceItemExtractedDetailsToJSON,
    ApiSupportingDocEvidenceItemExtractedDetailsToJSONTyped,
} from './ApiSupportingDocEvidenceItemExtractedDetails';

/**
 * 
 * @export
 * @interface ApiSupportingDocEvidenceItem
 */
export interface ApiSupportingDocEvidenceItem {
    /**
     * 
     * @type {ApiSupportingDocEvidenceItemExtractedDetails}
     * @memberof ApiSupportingDocEvidenceItem
     */
    extracted_details: ApiSupportingDocEvidenceItemExtractedDetails;
    /**
     * 
     * @type {Array<ApiVideoSelfieCheckArtefactsInner>}
     * @memberof ApiSupportingDocEvidenceItem
     */
    artefacts?: Array<ApiVideoSelfieCheckArtefactsInner>;
    /**
     * 
     * @type {string}
     * @memberof ApiSupportingDocEvidenceItem
     */
    evidence_type: ApiSupportingDocEvidenceItemEvidenceTypeEnum;
    /**
     * 
     * @type {ApiSupportingDocEvidenceItemValidations}
     * @memberof ApiSupportingDocEvidenceItem
     */
    validations: ApiSupportingDocEvidenceItemValidations;
    /**
     * 
     * @type {string}
     * @memberof ApiSupportingDocEvidenceItem
     */
    created_at?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiSupportingDocEvidenceItem
     */
    total_attempts?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiSupportingDocEvidenceItem
     */
    outcome: ApiSupportingDocEvidenceItemOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiSupportingDocEvidenceItem
     */
    step: ApiSupportingDocEvidenceItemStepEnum;
}


/**
 * @export
 */
export const ApiSupportingDocEvidenceItemEvidenceTypeEnum = {
    Payslip: 'payslip',
    PensionAnnualStatement: 'pension_annual_statement',
    BenefitsLetter: 'benefits_letter',
    HmppsLetter: 'hmpps_letter',
    NhsLetter: 'nhs_letter',
    BankStatement: 'bank_statement',
    CreditCardStatement: 'credit_card_statement',
    MortgageStatement: 'mortgage_statement',
    UtilityBill: 'utility_bill',
    MobilePhoneBill: 'mobile_phone_bill',
    BirthOrAdoptionCertificate: 'birth_or_adoption_certificate',
    MarriageCertificate: 'marriage_certificate',
    NaturalisationOrRegCertificate: 'naturalisation_or_reg_certificate',
    EducationCertificate: 'education_certificate',
    PayeTaxSummary: 'paye_tax_summary',
    InsurancePolicyAgreement: 'insurance_policy_agreement',
    OlderPersonBusPass: 'older_person_bus_pass'
} as const;
export type ApiSupportingDocEvidenceItemEvidenceTypeEnum = typeof ApiSupportingDocEvidenceItemEvidenceTypeEnum[keyof typeof ApiSupportingDocEvidenceItemEvidenceTypeEnum];

/**
 * @export
 */
export const ApiSupportingDocEvidenceItemOutcomeEnum = {
    Pass: 'pass',
    Fail: 'fail',
    InProgress: 'in_progress',
    Error: 'error'
} as const;
export type ApiSupportingDocEvidenceItemOutcomeEnum = typeof ApiSupportingDocEvidenceItemOutcomeEnum[keyof typeof ApiSupportingDocEvidenceItemOutcomeEnum];

/**
 * @export
 */
export const ApiSupportingDocEvidenceItemStepEnum = {
    SupportingDocument: 'supporting_document'
} as const;
export type ApiSupportingDocEvidenceItemStepEnum = typeof ApiSupportingDocEvidenceItemStepEnum[keyof typeof ApiSupportingDocEvidenceItemStepEnum];


/**
 * Check if a given object implements the ApiSupportingDocEvidenceItem interface.
 */
export function instanceOfApiSupportingDocEvidenceItem(value: object): value is ApiSupportingDocEvidenceItem {
    if (!('extracted_details' in value) || value['extracted_details'] === undefined) return false;
    if (!('evidence_type' in value) || value['evidence_type'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function ApiSupportingDocEvidenceItemFromJSON(json: any): ApiSupportingDocEvidenceItem {
    return ApiSupportingDocEvidenceItemFromJSONTyped(json, false);
}

export function ApiSupportingDocEvidenceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSupportingDocEvidenceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'extracted_details': ApiSupportingDocEvidenceItemExtractedDetailsFromJSON(json['extracted_details']),
        'artefacts': json['artefacts'] == null ? undefined : ((json['artefacts'] as Array<any>).map(ApiVideoSelfieCheckArtefactsInnerFromJSON)),
        'evidence_type': json['evidence_type'],
        'validations': ApiSupportingDocEvidenceItemValidationsFromJSON(json['validations']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'total_attempts': json['total_attempts'] == null ? undefined : json['total_attempts'],
        'outcome': json['outcome'],
        'step': json['step'],
    };
}

export function ApiSupportingDocEvidenceItemToJSON(json: any): ApiSupportingDocEvidenceItem {
    return ApiSupportingDocEvidenceItemToJSONTyped(json, false);
}

export function ApiSupportingDocEvidenceItemToJSONTyped(value?: ApiSupportingDocEvidenceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extracted_details': ApiSupportingDocEvidenceItemExtractedDetailsToJSON(value['extracted_details']),
        'artefacts': value['artefacts'] == null ? undefined : ((value['artefacts'] as Array<any>).map(ApiVideoSelfieCheckArtefactsInnerToJSON)),
        'evidence_type': value['evidence_type'],
        'validations': ApiSupportingDocEvidenceItemValidationsToJSON(value['validations']),
        'created_at': value['created_at'],
        'total_attempts': value['total_attempts'],
        'outcome': value['outcome'],
        'step': value['step'],
    };
}

