/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerificationCheck7ExtractedDetails } from './ApiVerificationCheck7ExtractedDetails';
import {
    ApiVerificationCheck7ExtractedDetailsFromJSON,
    ApiVerificationCheck7ExtractedDetailsFromJSONTyped,
    ApiVerificationCheck7ExtractedDetailsToJSON,
    ApiVerificationCheck7ExtractedDetailsToJSONTyped,
} from './ApiVerificationCheck7ExtractedDetails';
import type { ApiVerificationCheck7Validations } from './ApiVerificationCheck7Validations';
import {
    ApiVerificationCheck7ValidationsFromJSON,
    ApiVerificationCheck7ValidationsFromJSONTyped,
    ApiVerificationCheck7ValidationsToJSON,
    ApiVerificationCheck7ValidationsToJSONTyped,
} from './ApiVerificationCheck7Validations';
import type { ApiVerificationCheck0ArtefactsInner } from './ApiVerificationCheck0ArtefactsInner';
import {
    ApiVerificationCheck0ArtefactsInnerFromJSON,
    ApiVerificationCheck0ArtefactsInnerFromJSONTyped,
    ApiVerificationCheck0ArtefactsInnerToJSON,
    ApiVerificationCheck0ArtefactsInnerToJSONTyped,
} from './ApiVerificationCheck0ArtefactsInner';

/**
 * 
 * @export
 * @interface ApiVerificationCheck7
 */
export interface ApiVerificationCheck7 {
    /**
     * 
     * @type {ApiVerificationCheck7ExtractedDetails}
     * @memberof ApiVerificationCheck7
     */
    extracted_details: ApiVerificationCheck7ExtractedDetails;
    /**
     * 
     * @type {Array<ApiVerificationCheck0ArtefactsInner>}
     * @memberof ApiVerificationCheck7
     */
    artefacts: Array<ApiVerificationCheck0ArtefactsInner>;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck7
     */
    evidence_type: ApiVerificationCheck7EvidenceTypeEnum;
    /**
     * 
     * @type {ApiVerificationCheck7Validations}
     * @memberof ApiVerificationCheck7
     */
    validations: ApiVerificationCheck7Validations;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck7
     */
    created_at?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiVerificationCheck7
     */
    total_attempts?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck7
     */
    outcome: ApiVerificationCheck7OutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck7
     */
    step: ApiVerificationCheck7StepEnum;
}


/**
 * @export
 */
export const ApiVerificationCheck7EvidenceTypeEnum = {
    RightToWork: 'right_to_work',
    RightToRent: 'right_to_rent',
    ImmigrationStatus: 'immigration_status',
    Unknown: 'unknown'
} as const;
export type ApiVerificationCheck7EvidenceTypeEnum = typeof ApiVerificationCheck7EvidenceTypeEnum[keyof typeof ApiVerificationCheck7EvidenceTypeEnum];

/**
 * @export
 */
export const ApiVerificationCheck7OutcomeEnum = {
    Pass: 'pass',
    Fail: 'fail',
    InProgress: 'in_progress',
    Error: 'error'
} as const;
export type ApiVerificationCheck7OutcomeEnum = typeof ApiVerificationCheck7OutcomeEnum[keyof typeof ApiVerificationCheck7OutcomeEnum];

/**
 * @export
 */
export const ApiVerificationCheck7StepEnum = {
    Evisa: 'evisa'
} as const;
export type ApiVerificationCheck7StepEnum = typeof ApiVerificationCheck7StepEnum[keyof typeof ApiVerificationCheck7StepEnum];


/**
 * Check if a given object implements the ApiVerificationCheck7 interface.
 */
export function instanceOfApiVerificationCheck7(value: object): value is ApiVerificationCheck7 {
    if (!('extracted_details' in value) || value['extracted_details'] === undefined) return false;
    if (!('artefacts' in value) || value['artefacts'] === undefined) return false;
    if (!('evidence_type' in value) || value['evidence_type'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function ApiVerificationCheck7FromJSON(json: any): ApiVerificationCheck7 {
    return ApiVerificationCheck7FromJSONTyped(json, false);
}

export function ApiVerificationCheck7FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck7 {
    if (json == null) {
        return json;
    }
    return {
        
        'extracted_details': ApiVerificationCheck7ExtractedDetailsFromJSON(json['extracted_details']),
        'artefacts': ((json['artefacts'] as Array<any>).map(ApiVerificationCheck0ArtefactsInnerFromJSON)),
        'evidence_type': json['evidence_type'],
        'validations': ApiVerificationCheck7ValidationsFromJSON(json['validations']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'total_attempts': json['total_attempts'] == null ? undefined : json['total_attempts'],
        'outcome': json['outcome'],
        'step': json['step'],
    };
}

export function ApiVerificationCheck7ToJSON(json: any): ApiVerificationCheck7 {
    return ApiVerificationCheck7ToJSONTyped(json, false);
}

export function ApiVerificationCheck7ToJSONTyped(value?: ApiVerificationCheck7 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extracted_details': ApiVerificationCheck7ExtractedDetailsToJSON(value['extracted_details']),
        'artefacts': ((value['artefacts'] as Array<any>).map(ApiVerificationCheck0ArtefactsInnerToJSON)),
        'evidence_type': value['evidence_type'],
        'validations': ApiVerificationCheck7ValidationsToJSON(value['validations']),
        'created_at': value['created_at'],
        'total_attempts': value['total_attempts'],
        'outcome': value['outcome'],
        'step': value['step'],
    };
}

