/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth } from './ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth';
import {
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSONTyped,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSONTyped,
} from './ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth';

/**
 * 
 * @export
 * @interface ApiVerificationCheck3Validations
 */
export interface ApiVerificationCheck3Validations {
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck3Validations
     */
    referee_confirmed_date_of_birth?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck3Validations
     */
    referee_confirmed_name?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck3Validations
     */
    referee_confirmed_photo?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
}

/**
 * Check if a given object implements the ApiVerificationCheck3Validations interface.
 */
export function instanceOfApiVerificationCheck3Validations(value: object): value is ApiVerificationCheck3Validations {
    return true;
}

export function ApiVerificationCheck3ValidationsFromJSON(json: any): ApiVerificationCheck3Validations {
    return ApiVerificationCheck3ValidationsFromJSONTyped(json, false);
}

export function ApiVerificationCheck3ValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck3Validations {
    if (json == null) {
        return json;
    }
    return {
        
        'referee_confirmed_date_of_birth': json['referee_confirmed_date_of_birth'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_confirmed_date_of_birth']),
        'referee_confirmed_name': json['referee_confirmed_name'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_confirmed_name']),
        'referee_confirmed_photo': json['referee_confirmed_photo'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_confirmed_photo']),
    };
}

export function ApiVerificationCheck3ValidationsToJSON(json: any): ApiVerificationCheck3Validations {
    return ApiVerificationCheck3ValidationsToJSONTyped(json, false);
}

export function ApiVerificationCheck3ValidationsToJSONTyped(value?: ApiVerificationCheck3Validations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referee_confirmed_date_of_birth': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_confirmed_date_of_birth']),
        'referee_confirmed_name': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_confirmed_name']),
        'referee_confirmed_photo': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_confirmed_photo']),
    };
}

