/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVerifyEmailCheckValidationsEmailVerified
 */
export interface ApiVerifyEmailCheckValidationsEmailVerified {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ApiVerifyEmailCheckValidationsEmailVerified
     */
    verified_at: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerifyEmailCheckValidationsEmailVerified
     */
    status: ApiVerifyEmailCheckValidationsEmailVerifiedStatusEnum;
}


/**
 * @export
 */
export const ApiVerifyEmailCheckValidationsEmailVerifiedStatusEnum = {
    Pass: 'pass',
    Fail: 'fail'
} as const;
export type ApiVerifyEmailCheckValidationsEmailVerifiedStatusEnum = typeof ApiVerifyEmailCheckValidationsEmailVerifiedStatusEnum[keyof typeof ApiVerifyEmailCheckValidationsEmailVerifiedStatusEnum];


/**
 * Check if a given object implements the ApiVerifyEmailCheckValidationsEmailVerified interface.
 */
export function instanceOfApiVerifyEmailCheckValidationsEmailVerified(value: object): value is ApiVerifyEmailCheckValidationsEmailVerified {
    if (!('verified_at' in value) || value['verified_at'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApiVerifyEmailCheckValidationsEmailVerifiedFromJSON(json: any): ApiVerifyEmailCheckValidationsEmailVerified {
    return ApiVerifyEmailCheckValidationsEmailVerifiedFromJSONTyped(json, false);
}

export function ApiVerifyEmailCheckValidationsEmailVerifiedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerifyEmailCheckValidationsEmailVerified {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'verified_at': json['verified_at'],
        'status': json['status'],
    };
}

export function ApiVerifyEmailCheckValidationsEmailVerifiedToJSON(json: any): ApiVerifyEmailCheckValidationsEmailVerified {
    return ApiVerifyEmailCheckValidationsEmailVerifiedToJSONTyped(json, false);
}

export function ApiVerifyEmailCheckValidationsEmailVerifiedToJSONTyped(value?: ApiVerifyEmailCheckValidationsEmailVerified | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'verified_at': value['verified_at'],
        'status': value['status'],
    };
}

