/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerificationEnrichment0DetailsMatchesInnerProperties } from './ApiVerificationEnrichment0DetailsMatchesInnerProperties';
import {
    ApiVerificationEnrichment0DetailsMatchesInnerPropertiesFromJSON,
    ApiVerificationEnrichment0DetailsMatchesInnerPropertiesFromJSONTyped,
    ApiVerificationEnrichment0DetailsMatchesInnerPropertiesToJSON,
    ApiVerificationEnrichment0DetailsMatchesInnerPropertiesToJSONTyped,
} from './ApiVerificationEnrichment0DetailsMatchesInnerProperties';

/**
 * 
 * @export
 * @interface ApiVerificationEnrichment0DetailsMatchesInner
 */
export interface ApiVerificationEnrichment0DetailsMatchesInner {
    /**
     * 
     * @type {ApiVerificationEnrichment0DetailsMatchesInnerProperties}
     * @memberof ApiVerificationEnrichment0DetailsMatchesInner
     */
    properties: ApiVerificationEnrichment0DetailsMatchesInnerProperties;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationEnrichment0DetailsMatchesInner
     */
    last_seen?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationEnrichment0DetailsMatchesInner
     */
    first_seen?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiVerificationEnrichment0DetailsMatchesInner
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationEnrichment0DetailsMatchesInner
     */
    caption: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationEnrichment0DetailsMatchesInner
     */
    id: string;
}

/**
 * Check if a given object implements the ApiVerificationEnrichment0DetailsMatchesInner interface.
 */
export function instanceOfApiVerificationEnrichment0DetailsMatchesInner(value: object): value is ApiVerificationEnrichment0DetailsMatchesInner {
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ApiVerificationEnrichment0DetailsMatchesInnerFromJSON(json: any): ApiVerificationEnrichment0DetailsMatchesInner {
    return ApiVerificationEnrichment0DetailsMatchesInnerFromJSONTyped(json, false);
}

export function ApiVerificationEnrichment0DetailsMatchesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationEnrichment0DetailsMatchesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': ApiVerificationEnrichment0DetailsMatchesInnerPropertiesFromJSON(json['properties']),
        'last_seen': json['last_seen'] == null ? undefined : json['last_seen'],
        'first_seen': json['first_seen'] == null ? undefined : json['first_seen'],
        'score': json['score'],
        'caption': json['caption'],
        'id': json['id'],
    };
}

export function ApiVerificationEnrichment0DetailsMatchesInnerToJSON(json: any): ApiVerificationEnrichment0DetailsMatchesInner {
    return ApiVerificationEnrichment0DetailsMatchesInnerToJSONTyped(json, false);
}

export function ApiVerificationEnrichment0DetailsMatchesInnerToJSONTyped(value?: ApiVerificationEnrichment0DetailsMatchesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'properties': ApiVerificationEnrichment0DetailsMatchesInnerPropertiesToJSON(value['properties']),
        'last_seen': value['last_seen'],
        'first_seen': value['first_seen'],
        'score': value['score'],
        'caption': value['caption'],
        'id': value['id'],
    };
}

