/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiValidationStatus = {
    Pass: 'pass',
    Fail: 'fail'
} as const;
export type ApiValidationStatus = typeof ApiValidationStatus[keyof typeof ApiValidationStatus];


export function instanceOfApiValidationStatus(value: any): boolean {
    for (const key in ApiValidationStatus) {
        if (Object.prototype.hasOwnProperty.call(ApiValidationStatus, key)) {
            if (ApiValidationStatus[key as keyof typeof ApiValidationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiValidationStatusFromJSON(json: any): ApiValidationStatus {
    return ApiValidationStatusFromJSONTyped(json, false);
}

export function ApiValidationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiValidationStatus {
    return json as ApiValidationStatus;
}

export function ApiValidationStatusToJSON(value?: ApiValidationStatus | null): any {
    return value as any;
}

export function ApiValidationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiValidationStatus {
    return value as ApiValidationStatus;
}

