/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerificationEnrichment1Details } from './ApiVerificationEnrichment1Details';
import {
    ApiVerificationEnrichment1DetailsFromJSON,
    ApiVerificationEnrichment1DetailsFromJSONTyped,
    ApiVerificationEnrichment1DetailsToJSON,
    ApiVerificationEnrichment1DetailsToJSONTyped,
} from './ApiVerificationEnrichment1Details';

/**
 * 
 * @export
 * @interface ApiVerificationEnrichment1
 */
export interface ApiVerificationEnrichment1 {
    /**
     * 
     * @type {ApiVerificationEnrichment1Details}
     * @memberof ApiVerificationEnrichment1
     */
    details: ApiVerificationEnrichment1Details;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationEnrichment1
     */
    outcome: ApiVerificationEnrichment1OutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationEnrichment1
     */
    check: ApiVerificationEnrichment1CheckEnum;
}


/**
 * @export
 */
export const ApiVerificationEnrichment1OutcomeEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Error: 'error'
} as const;
export type ApiVerificationEnrichment1OutcomeEnum = typeof ApiVerificationEnrichment1OutcomeEnum[keyof typeof ApiVerificationEnrichment1OutcomeEnum];

/**
 * @export
 */
export const ApiVerificationEnrichment1CheckEnum = {
    EmailFootprintAnalysis: 'email_footprint_analysis',
    PhoneFootprintAnalysis: 'phone_footprint_analysis'
} as const;
export type ApiVerificationEnrichment1CheckEnum = typeof ApiVerificationEnrichment1CheckEnum[keyof typeof ApiVerificationEnrichment1CheckEnum];


/**
 * Check if a given object implements the ApiVerificationEnrichment1 interface.
 */
export function instanceOfApiVerificationEnrichment1(value: object): value is ApiVerificationEnrichment1 {
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('check' in value) || value['check'] === undefined) return false;
    return true;
}

export function ApiVerificationEnrichment1FromJSON(json: any): ApiVerificationEnrichment1 {
    return ApiVerificationEnrichment1FromJSONTyped(json, false);
}

export function ApiVerificationEnrichment1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationEnrichment1 {
    if (json == null) {
        return json;
    }
    return {
        
        'details': ApiVerificationEnrichment1DetailsFromJSON(json['details']),
        'outcome': json['outcome'],
        'check': json['check'],
    };
}

export function ApiVerificationEnrichment1ToJSON(json: any): ApiVerificationEnrichment1 {
    return ApiVerificationEnrichment1ToJSONTyped(json, false);
}

export function ApiVerificationEnrichment1ToJSONTyped(value?: ApiVerificationEnrichment1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': ApiVerificationEnrichment1DetailsToJSON(value['details']),
        'outcome': value['outcome'],
        'check': value['check'],
    };
}

