/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVideoSelfieCheckArtefactsInner
 */
export interface ApiVideoSelfieCheckArtefactsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiVideoSelfieCheckArtefactsInner
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoSelfieCheckArtefactsInner
     */
    role: ApiVideoSelfieCheckArtefactsInnerRoleEnum;
}


/**
 * @export
 */
export const ApiVideoSelfieCheckArtefactsInnerRoleEnum = {
    Document: 'document',
    Backside: 'backside',
    FaceScan: 'face_scan'
} as const;
export type ApiVideoSelfieCheckArtefactsInnerRoleEnum = typeof ApiVideoSelfieCheckArtefactsInnerRoleEnum[keyof typeof ApiVideoSelfieCheckArtefactsInnerRoleEnum];


/**
 * Check if a given object implements the ApiVideoSelfieCheckArtefactsInner interface.
 */
export function instanceOfApiVideoSelfieCheckArtefactsInner(value: object): value is ApiVideoSelfieCheckArtefactsInner {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ApiVideoSelfieCheckArtefactsInnerFromJSON(json: any): ApiVideoSelfieCheckArtefactsInner {
    return ApiVideoSelfieCheckArtefactsInnerFromJSONTyped(json, false);
}

export function ApiVideoSelfieCheckArtefactsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVideoSelfieCheckArtefactsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'role': json['role'],
    };
}

export function ApiVideoSelfieCheckArtefactsInnerToJSON(json: any): ApiVideoSelfieCheckArtefactsInner {
    return ApiVideoSelfieCheckArtefactsInnerToJSONTyped(json, false);
}

export function ApiVideoSelfieCheckArtefactsInnerToJSONTyped(value?: ApiVideoSelfieCheckArtefactsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'role': value['role'],
    };
}

