/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerifyPhoneNumberCheckValidations } from './ApiVerifyPhoneNumberCheckValidations';
import {
    ApiVerifyPhoneNumberCheckValidationsFromJSON,
    ApiVerifyPhoneNumberCheckValidationsFromJSONTyped,
    ApiVerifyPhoneNumberCheckValidationsToJSON,
    ApiVerifyPhoneNumberCheckValidationsToJSONTyped,
} from './ApiVerifyPhoneNumberCheckValidations';

/**
 * 
 * @export
 * @interface ApiVerifyPhoneNumberCheck
 */
export interface ApiVerifyPhoneNumberCheck {
    /**
     * 
     * @type {ApiVerifyPhoneNumberCheckValidations}
     * @memberof ApiVerifyPhoneNumberCheck
     */
    validations: ApiVerifyPhoneNumberCheckValidations;
    /**
     * 
     * @type {string}
     * @memberof ApiVerifyPhoneNumberCheck
     */
    created_at?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiVerifyPhoneNumberCheck
     */
    total_attempts?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVerifyPhoneNumberCheck
     */
    outcome: ApiVerifyPhoneNumberCheckOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiVerifyPhoneNumberCheck
     */
    step: ApiVerifyPhoneNumberCheckStepEnum;
}


/**
 * @export
 */
export const ApiVerifyPhoneNumberCheckOutcomeEnum = {
    Pass: 'pass',
    Fail: 'fail',
    InProgress: 'in_progress',
    Error: 'error'
} as const;
export type ApiVerifyPhoneNumberCheckOutcomeEnum = typeof ApiVerifyPhoneNumberCheckOutcomeEnum[keyof typeof ApiVerifyPhoneNumberCheckOutcomeEnum];

/**
 * @export
 */
export const ApiVerifyPhoneNumberCheckStepEnum = {
    VerifyPhoneNumber: 'verify_phone_number'
} as const;
export type ApiVerifyPhoneNumberCheckStepEnum = typeof ApiVerifyPhoneNumberCheckStepEnum[keyof typeof ApiVerifyPhoneNumberCheckStepEnum];


/**
 * Check if a given object implements the ApiVerifyPhoneNumberCheck interface.
 */
export function instanceOfApiVerifyPhoneNumberCheck(value: object): value is ApiVerifyPhoneNumberCheck {
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function ApiVerifyPhoneNumberCheckFromJSON(json: any): ApiVerifyPhoneNumberCheck {
    return ApiVerifyPhoneNumberCheckFromJSONTyped(json, false);
}

export function ApiVerifyPhoneNumberCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerifyPhoneNumberCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'validations': ApiVerifyPhoneNumberCheckValidationsFromJSON(json['validations']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'total_attempts': json['total_attempts'] == null ? undefined : json['total_attempts'],
        'outcome': json['outcome'],
        'step': json['step'],
    };
}

export function ApiVerifyPhoneNumberCheckToJSON(json: any): ApiVerifyPhoneNumberCheck {
    return ApiVerifyPhoneNumberCheckToJSONTyped(json, false);
}

export function ApiVerifyPhoneNumberCheckToJSONTyped(value?: ApiVerifyPhoneNumberCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validations': ApiVerifyPhoneNumberCheckValidationsToJSON(value['validations']),
        'created_at': value['created_at'],
        'total_attempts': value['total_attempts'],
        'outcome': value['outcome'],
        'step': value['step'],
    };
}

