/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVideoSelfieCheckArtefactsInner } from './ApiVideoSelfieCheckArtefactsInner';
import {
    ApiVideoSelfieCheckArtefactsInnerFromJSON,
    ApiVideoSelfieCheckArtefactsInnerFromJSONTyped,
    ApiVideoSelfieCheckArtefactsInnerToJSON,
    ApiVideoSelfieCheckArtefactsInnerToJSONTyped,
} from './ApiVideoSelfieCheckArtefactsInner';
import type { ApiVideoSelfieCheckValidations } from './ApiVideoSelfieCheckValidations';
import {
    ApiVideoSelfieCheckValidationsFromJSON,
    ApiVideoSelfieCheckValidationsFromJSONTyped,
    ApiVideoSelfieCheckValidationsToJSON,
    ApiVideoSelfieCheckValidationsToJSONTyped,
} from './ApiVideoSelfieCheckValidations';

/**
 * 
 * @export
 * @interface ApiVideoSelfieCheck
 */
export interface ApiVideoSelfieCheck {
    /**
     * 
     * @type {Array<ApiVideoSelfieCheckArtefactsInner>}
     * @memberof ApiVideoSelfieCheck
     */
    artefacts: Array<ApiVideoSelfieCheckArtefactsInner>;
    /**
     * 
     * @type {ApiVideoSelfieCheckValidations}
     * @memberof ApiVideoSelfieCheck
     */
    validations: ApiVideoSelfieCheckValidations;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoSelfieCheck
     */
    created_at?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiVideoSelfieCheck
     */
    total_attempts?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoSelfieCheck
     */
    outcome?: ApiVideoSelfieCheckOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoSelfieCheck
     */
    step: ApiVideoSelfieCheckStepEnum;
}


/**
 * @export
 */
export const ApiVideoSelfieCheckOutcomeEnum = {
    InProgress: 'in_progress',
    Pass: 'pass',
    Fail: 'fail'
} as const;
export type ApiVideoSelfieCheckOutcomeEnum = typeof ApiVideoSelfieCheckOutcomeEnum[keyof typeof ApiVideoSelfieCheckOutcomeEnum];

/**
 * @export
 */
export const ApiVideoSelfieCheckStepEnum = {
    VideoSelfie: 'video_selfie'
} as const;
export type ApiVideoSelfieCheckStepEnum = typeof ApiVideoSelfieCheckStepEnum[keyof typeof ApiVideoSelfieCheckStepEnum];


/**
 * Check if a given object implements the ApiVideoSelfieCheck interface.
 */
export function instanceOfApiVideoSelfieCheck(value: object): value is ApiVideoSelfieCheck {
    if (!('artefacts' in value) || value['artefacts'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function ApiVideoSelfieCheckFromJSON(json: any): ApiVideoSelfieCheck {
    return ApiVideoSelfieCheckFromJSONTyped(json, false);
}

export function ApiVideoSelfieCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVideoSelfieCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'artefacts': ((json['artefacts'] as Array<any>).map(ApiVideoSelfieCheckArtefactsInnerFromJSON)),
        'validations': ApiVideoSelfieCheckValidationsFromJSON(json['validations']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'total_attempts': json['total_attempts'] == null ? undefined : json['total_attempts'],
        'outcome': json['outcome'] == null ? undefined : json['outcome'],
        'step': json['step'],
    };
}

export function ApiVideoSelfieCheckToJSON(json: any): ApiVideoSelfieCheck {
    return ApiVideoSelfieCheckToJSONTyped(json, false);
}

export function ApiVideoSelfieCheckToJSONTyped(value?: ApiVideoSelfieCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artefacts': ((value['artefacts'] as Array<any>).map(ApiVideoSelfieCheckArtefactsInnerToJSON)),
        'validations': ApiVideoSelfieCheckValidationsToJSON(value['validations']),
        'created_at': value['created_at'],
        'total_attempts': value['total_attempts'],
        'outcome': value['outcome'],
        'step': value['step'],
    };
}

