/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerificationCheck1ValidationsEmailVerified } from './ApiVerificationCheck1ValidationsEmailVerified';
import {
    ApiVerificationCheck1ValidationsEmailVerifiedFromJSON,
    ApiVerificationCheck1ValidationsEmailVerifiedFromJSONTyped,
    ApiVerificationCheck1ValidationsEmailVerifiedToJSON,
    ApiVerificationCheck1ValidationsEmailVerifiedToJSONTyped,
} from './ApiVerificationCheck1ValidationsEmailVerified';

/**
 * 
 * @export
 * @interface ApiVerificationCheck1Validations
 */
export interface ApiVerificationCheck1Validations {
    /**
     * 
     * @type {ApiVerificationCheck1ValidationsEmailVerified}
     * @memberof ApiVerificationCheck1Validations
     */
    email_verified?: ApiVerificationCheck1ValidationsEmailVerified;
}

/**
 * Check if a given object implements the ApiVerificationCheck1Validations interface.
 */
export function instanceOfApiVerificationCheck1Validations(value: object): value is ApiVerificationCheck1Validations {
    return true;
}

export function ApiVerificationCheck1ValidationsFromJSON(json: any): ApiVerificationCheck1Validations {
    return ApiVerificationCheck1ValidationsFromJSONTyped(json, false);
}

export function ApiVerificationCheck1ValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck1Validations {
    if (json == null) {
        return json;
    }
    return {
        
        'email_verified': json['email_verified'] == null ? undefined : ApiVerificationCheck1ValidationsEmailVerifiedFromJSON(json['email_verified']),
    };
}

export function ApiVerificationCheck1ValidationsToJSON(json: any): ApiVerificationCheck1Validations {
    return ApiVerificationCheck1ValidationsToJSONTyped(json, false);
}

export function ApiVerificationCheck1ValidationsToJSONTyped(value?: ApiVerificationCheck1Validations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email_verified': ApiVerificationCheck1ValidationsEmailVerifiedToJSON(value['email_verified']),
    };
}

