/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVerificationCheck6ExtractedDetails
 */
export interface ApiVerificationCheck6ExtractedDetails {
    /**
     * 
     * @type {any}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    transaction_data: any | null;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    account_type: ApiVerificationCheck6ExtractedDetailsAccountTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    bank_name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    first_line_of_address?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    date_of_birth?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck6ExtractedDetails
     */
    last_name: string;
}


/**
 * @export
 */
export const ApiVerificationCheck6ExtractedDetailsAccountTypeEnum = {
    CashCurrent: 'cash:current',
    Savings: 'savings'
} as const;
export type ApiVerificationCheck6ExtractedDetailsAccountTypeEnum = typeof ApiVerificationCheck6ExtractedDetailsAccountTypeEnum[keyof typeof ApiVerificationCheck6ExtractedDetailsAccountTypeEnum];


/**
 * Check if a given object implements the ApiVerificationCheck6ExtractedDetails interface.
 */
export function instanceOfApiVerificationCheck6ExtractedDetails(value: object): value is ApiVerificationCheck6ExtractedDetails {
    if (!('transaction_data' in value) || value['transaction_data'] === undefined) return false;
    if (!('account_type' in value) || value['account_type'] === undefined) return false;
    if (!('bank_name' in value) || value['bank_name'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    return true;
}

export function ApiVerificationCheck6ExtractedDetailsFromJSON(json: any): ApiVerificationCheck6ExtractedDetails {
    return ApiVerificationCheck6ExtractedDetailsFromJSONTyped(json, false);
}

export function ApiVerificationCheck6ExtractedDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck6ExtractedDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction_data': json['transaction_data'],
        'account_type': json['account_type'],
        'bank_name': json['bank_name'],
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'first_line_of_address': json['first_line_of_address'] == null ? undefined : json['first_line_of_address'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
    };
}

export function ApiVerificationCheck6ExtractedDetailsToJSON(json: any): ApiVerificationCheck6ExtractedDetails {
    return ApiVerificationCheck6ExtractedDetailsToJSONTyped(json, false);
}

export function ApiVerificationCheck6ExtractedDetailsToJSONTyped(value?: ApiVerificationCheck6ExtractedDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_data': value['transaction_data'],
        'account_type': value['account_type'],
        'bank_name': value['bank_name'],
        'postcode': value['postcode'],
        'first_line_of_address': value['first_line_of_address'],
        'date_of_birth': value['date_of_birth'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
    };
}

