/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerificationCheck0ValidationsRefereeDissimilarityCheck } from './ApiVerificationCheck0ValidationsRefereeDissimilarityCheck';
import {
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSON,
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSONTyped,
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSON,
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSONTyped,
} from './ApiVerificationCheck0ValidationsRefereeDissimilarityCheck';
import type { ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth } from './ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth';
import {
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSONTyped,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSONTyped,
} from './ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth';

/**
 * 
 * @export
 * @interface ApiVerificationCheck7Validations
 */
export interface ApiVerificationCheck7Validations {
    /**
     * 
     * @type {ApiVerificationCheck0ValidationsRefereeDissimilarityCheck}
     * @memberof ApiVerificationCheck7Validations
     */
    face_match?: ApiVerificationCheck0ValidationsRefereeDissimilarityCheck;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck7Validations
     */
    evisa_not_expired: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck7Validations
     */
    evisa_started: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck7Validations
     */
    required_fields_extracted: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck7Validations
     */
    evisa_exists: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
}

/**
 * Check if a given object implements the ApiVerificationCheck7Validations interface.
 */
export function instanceOfApiVerificationCheck7Validations(value: object): value is ApiVerificationCheck7Validations {
    if (!('evisa_not_expired' in value) || value['evisa_not_expired'] === undefined) return false;
    if (!('evisa_started' in value) || value['evisa_started'] === undefined) return false;
    if (!('required_fields_extracted' in value) || value['required_fields_extracted'] === undefined) return false;
    if (!('evisa_exists' in value) || value['evisa_exists'] === undefined) return false;
    return true;
}

export function ApiVerificationCheck7ValidationsFromJSON(json: any): ApiVerificationCheck7Validations {
    return ApiVerificationCheck7ValidationsFromJSONTyped(json, false);
}

export function ApiVerificationCheck7ValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck7Validations {
    if (json == null) {
        return json;
    }
    return {
        
        'face_match': json['face_match'] == null ? undefined : ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSON(json['face_match']),
        'evisa_not_expired': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['evisa_not_expired']),
        'evisa_started': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['evisa_started']),
        'required_fields_extracted': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['required_fields_extracted']),
        'evisa_exists': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['evisa_exists']),
    };
}

export function ApiVerificationCheck7ValidationsToJSON(json: any): ApiVerificationCheck7Validations {
    return ApiVerificationCheck7ValidationsToJSONTyped(json, false);
}

export function ApiVerificationCheck7ValidationsToJSONTyped(value?: ApiVerificationCheck7Validations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'face_match': ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSON(value['face_match']),
        'evisa_not_expired': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['evisa_not_expired']),
        'evisa_started': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['evisa_started']),
        'required_fields_extracted': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['required_fields_extracted']),
        'evisa_exists': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['evisa_exists']),
    };
}

