/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVerificationCheck0ValidationsRefereeDissimilarityCheck
 */
export interface ApiVerificationCheck0ValidationsRefereeDissimilarityCheck {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof ApiVerificationCheck0ValidationsRefereeDissimilarityCheck
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVerificationCheck0ValidationsRefereeDissimilarityCheck
     */
    status: ApiVerificationCheck0ValidationsRefereeDissimilarityCheckStatusEnum;
}


/**
 * @export
 */
export const ApiVerificationCheck0ValidationsRefereeDissimilarityCheckStatusEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Error: 'error'
} as const;
export type ApiVerificationCheck0ValidationsRefereeDissimilarityCheckStatusEnum = typeof ApiVerificationCheck0ValidationsRefereeDissimilarityCheckStatusEnum[keyof typeof ApiVerificationCheck0ValidationsRefereeDissimilarityCheckStatusEnum];


/**
 * Check if a given object implements the ApiVerificationCheck0ValidationsRefereeDissimilarityCheck interface.
 */
export function instanceOfApiVerificationCheck0ValidationsRefereeDissimilarityCheck(value: object): value is ApiVerificationCheck0ValidationsRefereeDissimilarityCheck {
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSON(json: any): ApiVerificationCheck0ValidationsRefereeDissimilarityCheck {
    return ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSONTyped(json, false);
}

export function ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck0ValidationsRefereeDissimilarityCheck {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'score': json['score'],
        'status': json['status'],
    };
}

export function ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSON(json: any): ApiVerificationCheck0ValidationsRefereeDissimilarityCheck {
    return ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSONTyped(json, false);
}

export function ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSONTyped(value?: ApiVerificationCheck0ValidationsRefereeDissimilarityCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'score': value['score'],
        'status': value['status'],
    };
}

