/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVerificationCheck0ValidationsRefereeDissimilarityCheck } from './ApiVerificationCheck0ValidationsRefereeDissimilarityCheck';
import {
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSON,
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSONTyped,
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSON,
    ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSONTyped,
} from './ApiVerificationCheck0ValidationsRefereeDissimilarityCheck';
import type { ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth } from './ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth';
import {
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSONTyped,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON,
    ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSONTyped,
} from './ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth';

/**
 * 
 * @export
 * @interface ApiVerificationCheck4Validations
 */
export interface ApiVerificationCheck4Validations {
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    referee_biometrics_dissimilar?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    referee_over18?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    issuing_country_allowed?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    icao_format_valid?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    names_consistent?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    dates_of_birth_consistent?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    has_not_expired?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck0ValidationsRefereeDissimilarityCheck}
     * @memberof ApiVerificationCheck4Validations
     */
    face_match?: ApiVerificationCheck0ValidationsRefereeDissimilarityCheck;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    not_sample_or_internal_use?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    identifier_format_valid?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    matches_issuer_database?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    compound_identifiers_match?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    security_features_present?: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
    /**
     * 
     * @type {ApiVerificationCheck0ValidationsRefereeDissimilarityCheck}
     * @memberof ApiVerificationCheck4Validations
     */
    document_borders_detected: ApiVerificationCheck0ValidationsRefereeDissimilarityCheck;
    /**
     * 
     * @type {ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth}
     * @memberof ApiVerificationCheck4Validations
     */
    required_fields_extracted: ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirth;
}

/**
 * Check if a given object implements the ApiVerificationCheck4Validations interface.
 */
export function instanceOfApiVerificationCheck4Validations(value: object): value is ApiVerificationCheck4Validations {
    if (!('document_borders_detected' in value) || value['document_borders_detected'] === undefined) return false;
    if (!('required_fields_extracted' in value) || value['required_fields_extracted'] === undefined) return false;
    return true;
}

export function ApiVerificationCheck4ValidationsFromJSON(json: any): ApiVerificationCheck4Validations {
    return ApiVerificationCheck4ValidationsFromJSONTyped(json, false);
}

export function ApiVerificationCheck4ValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck4Validations {
    if (json == null) {
        return json;
    }
    return {
        
        'referee_biometrics_dissimilar': json['referee_biometrics_dissimilar'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_biometrics_dissimilar']),
        'referee_over18': json['referee_over18'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['referee_over18']),
        'issuing_country_allowed': json['issuing_country_allowed'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['issuing_country_allowed']),
        'icao_format_valid': json['icao_format_valid'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['icao_format_valid']),
        'names_consistent': json['names_consistent'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['names_consistent']),
        'dates_of_birth_consistent': json['dates_of_birth_consistent'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['dates_of_birth_consistent']),
        'has_not_expired': json['has_not_expired'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['has_not_expired']),
        'face_match': json['face_match'] == null ? undefined : ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSON(json['face_match']),
        'not_sample_or_internal_use': json['not_sample_or_internal_use'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['not_sample_or_internal_use']),
        'identifier_format_valid': json['identifier_format_valid'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['identifier_format_valid']),
        'matches_issuer_database': json['matches_issuer_database'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['matches_issuer_database']),
        'compound_identifiers_match': json['compound_identifiers_match'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['compound_identifiers_match']),
        'security_features_present': json['security_features_present'] == null ? undefined : ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['security_features_present']),
        'document_borders_detected': ApiVerificationCheck0ValidationsRefereeDissimilarityCheckFromJSON(json['document_borders_detected']),
        'required_fields_extracted': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthFromJSON(json['required_fields_extracted']),
    };
}

export function ApiVerificationCheck4ValidationsToJSON(json: any): ApiVerificationCheck4Validations {
    return ApiVerificationCheck4ValidationsToJSONTyped(json, false);
}

export function ApiVerificationCheck4ValidationsToJSONTyped(value?: ApiVerificationCheck4Validations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referee_biometrics_dissimilar': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_biometrics_dissimilar']),
        'referee_over18': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['referee_over18']),
        'issuing_country_allowed': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['issuing_country_allowed']),
        'icao_format_valid': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['icao_format_valid']),
        'names_consistent': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['names_consistent']),
        'dates_of_birth_consistent': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['dates_of_birth_consistent']),
        'has_not_expired': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['has_not_expired']),
        'face_match': ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSON(value['face_match']),
        'not_sample_or_internal_use': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['not_sample_or_internal_use']),
        'identifier_format_valid': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['identifier_format_valid']),
        'matches_issuer_database': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['matches_issuer_database']),
        'compound_identifiers_match': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['compound_identifiers_match']),
        'security_features_present': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['security_features_present']),
        'document_borders_detected': ApiVerificationCheck0ValidationsRefereeDissimilarityCheckToJSON(value['document_borders_detected']),
        'required_fields_extracted': ApiVerificationCheck3ValidationsRefereeConfirmedDateOfBirthToJSON(value['required_fields_extracted']),
    };
}

