/* tslint:disable */
/* eslint-disable */
/**
 * Proper discriminated union for Api_VerificationCheck_.
 * This file is auto-generated by post-processing script.
 */

import type { ApiVerificationCheck0 } from './ApiVerificationCheck0';
import type { ApiVerificationCheck1 } from './ApiVerificationCheck1';
import type { ApiVerificationCheck2 } from './ApiVerificationCheck2';
import type { ApiVerificationCheck3 } from './ApiVerificationCheck3';
import type { ApiVerificationCheck4 } from './ApiVerificationCheck4';
import type { ApiVerificationCheck5 } from './ApiVerificationCheck5';
import type { ApiVerificationCheck6 } from './ApiVerificationCheck6';
import type { ApiVerificationCheck7 } from './ApiVerificationCheck7';
import type { ApiVerificationCheck8 } from './ApiVerificationCheck8';

import { ApiVerificationCheck0FromJSON, ApiVerificationCheck0ToJSON } from './ApiVerificationCheck0';
import { ApiVerificationCheck1FromJSON, ApiVerificationCheck1ToJSON } from './ApiVerificationCheck1';
import { ApiVerificationCheck2FromJSON, ApiVerificationCheck2ToJSON } from './ApiVerificationCheck2';
import { ApiVerificationCheck3FromJSON, ApiVerificationCheck3ToJSON } from './ApiVerificationCheck3';
import { ApiVerificationCheck4FromJSON, ApiVerificationCheck4ToJSON } from './ApiVerificationCheck4';
import { ApiVerificationCheck5FromJSON, ApiVerificationCheck5ToJSON } from './ApiVerificationCheck5';
import { ApiVerificationCheck6FromJSON, ApiVerificationCheck6ToJSON } from './ApiVerificationCheck6';
import { ApiVerificationCheck7FromJSON, ApiVerificationCheck7ToJSON } from './ApiVerificationCheck7';
import { ApiVerificationCheck8FromJSON, ApiVerificationCheck8ToJSON } from './ApiVerificationCheck8';

/**
 * Discriminated union of all Api_VerificationCheck_ types
 * @export
 */
export type ApiVerificationCheck =
  | ApiVerificationCheck0
  | ApiVerificationCheck1
  | ApiVerificationCheck2
  | ApiVerificationCheck3
  | ApiVerificationCheck4
  | ApiVerificationCheck5
  | ApiVerificationCheck6
  | ApiVerificationCheck7
  | ApiVerificationCheck8;

export function ApiVerificationCheckFromJSON(json: any): ApiVerificationCheck {
  return ApiVerificationCheckFromJSONTyped(json, false);
}

export function ApiVerificationCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVerificationCheck {
  if (json == null) {
    return json;
  }
  
  if (ignoreDiscriminator) {
    // If ignoring discriminator, try to parse as first variant
    return ApiVerificationCheck0FromJSON(json);
  }
  
  // Use discriminator to determine which type to parse
  switch (json['step']) {
    case 'video_selfie':
      return ApiVerificationCheck0FromJSON(json);
    case 'verify_email':
      return ApiVerificationCheck1FromJSON(json);
    case 'verify_phone_number':
      return ApiVerificationCheck2FromJSON(json);
    case 'verify_user_details':
      return ApiVerificationCheck3FromJSON(json);
    case 'photo_id':
      return ApiVerificationCheck4FromJSON(json);
    case 'supporting_document':
      return ApiVerificationCheck5FromJSON(json);
    case 'bank_account':
      return ApiVerificationCheck6FromJSON(json);
    case 'evisa':
      return ApiVerificationCheck7FromJSON(json);
    case 'vouch':
      return ApiVerificationCheck8FromJSON(json);
    default:
      throw new Error(`Unknown step value: ${json['step']}`);
  }
}

export function ApiVerificationCheckToJSON(value: ApiVerificationCheck): any {
  return ApiVerificationCheckToJSONTyped(value, false);
}

export function ApiVerificationCheckToJSONTyped(value: ApiVerificationCheck | undefined, ignoreDiscriminator: boolean): any {
  if (value == null) {
    return value;
  }
  
  if (ignoreDiscriminator) {
    // If ignoring discriminator, serialize normally
  }
  
  // Use discriminator to determine which serializer to use
  switch ((value as any).step) {
    case 'video_selfie':
      return ApiVerificationCheck0ToJSON(value as ApiVerificationCheck0);
    case 'verify_email':
      return ApiVerificationCheck1ToJSON(value as ApiVerificationCheck1);
    case 'verify_phone_number':
      return ApiVerificationCheck2ToJSON(value as ApiVerificationCheck2);
    case 'verify_user_details':
      return ApiVerificationCheck3ToJSON(value as ApiVerificationCheck3);
    case 'photo_id':
      return ApiVerificationCheck4ToJSON(value as ApiVerificationCheck4);
    case 'supporting_document':
      return ApiVerificationCheck5ToJSON(value as ApiVerificationCheck5);
    case 'bank_account':
      return ApiVerificationCheck6ToJSON(value as ApiVerificationCheck6);
    case 'evisa':
      return ApiVerificationCheck7ToJSON(value as ApiVerificationCheck7);
    case 'vouch':
      return ApiVerificationCheck8ToJSON(value as ApiVerificationCheck8);
    default:
      throw new Error(`Unknown step value: ${(value as any).step}`);
  }
}
