/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { ApiVerificationCheckAnyOfThreethreeValidationsCompoundIdentifiersMatch } from './apiVerificationCheckAnyOfThreethreeValidationsCompoundIdentifiersMatch';
import type { ApiVerificationCheckAnyOfThreethreeValidationsDatesOfBirthConsistent } from './apiVerificationCheckAnyOfThreethreeValidationsDatesOfBirthConsistent';
import type { ApiVerificationCheckAnyOfThreethreeValidationsDocumentBordersDetected } from './apiVerificationCheckAnyOfThreethreeValidationsDocumentBordersDetected';
import type { ApiVerificationCheckAnyOfThreethreeValidationsFaceMatch } from './apiVerificationCheckAnyOfThreethreeValidationsFaceMatch';
import type { ApiVerificationCheckAnyOfThreethreeValidationsHasNotExpired } from './apiVerificationCheckAnyOfThreethreeValidationsHasNotExpired';
import type { ApiVerificationCheckAnyOfThreethreeValidationsIcaoFormatValid } from './apiVerificationCheckAnyOfThreethreeValidationsIcaoFormatValid';
import type { ApiVerificationCheckAnyOfThreethreeValidationsIdentifierFormatValid } from './apiVerificationCheckAnyOfThreethreeValidationsIdentifierFormatValid';
import type { ApiVerificationCheckAnyOfThreethreeValidationsIssuingCountryAllowed } from './apiVerificationCheckAnyOfThreethreeValidationsIssuingCountryAllowed';
import type { ApiVerificationCheckAnyOfThreethreeValidationsMatchesIssuerDatabase } from './apiVerificationCheckAnyOfThreethreeValidationsMatchesIssuerDatabase';
import type { ApiVerificationCheckAnyOfThreethreeValidationsNamesConsistent } from './apiVerificationCheckAnyOfThreethreeValidationsNamesConsistent';
import type { ApiVerificationCheckAnyOfThreethreeValidationsNotSampleOrInternalUse } from './apiVerificationCheckAnyOfThreethreeValidationsNotSampleOrInternalUse';
import type { ApiVerificationCheckAnyOfThreethreeValidationsRefereeBiometricsDissimilar } from './apiVerificationCheckAnyOfThreethreeValidationsRefereeBiometricsDissimilar';
import type { ApiVerificationCheckAnyOfThreethreeValidationsRefereeOver18 } from './apiVerificationCheckAnyOfThreethreeValidationsRefereeOver18';
import type { ApiVerificationCheckAnyOfThreethreeValidationsRequiredFieldsExtracted } from './apiVerificationCheckAnyOfThreethreeValidationsRequiredFieldsExtracted';
import type { ApiVerificationCheckAnyOfThreethreeValidationsSecurityFeaturesPresent } from './apiVerificationCheckAnyOfThreethreeValidationsSecurityFeaturesPresent';

export type ApiVerificationCheckAnyOfThreethreeValidations = {
  referee_biometrics_dissimilar?: ApiVerificationCheckAnyOfThreethreeValidationsRefereeBiometricsDissimilar;
  referee_over18?: ApiVerificationCheckAnyOfThreethreeValidationsRefereeOver18;
  issuing_country_allowed?: ApiVerificationCheckAnyOfThreethreeValidationsIssuingCountryAllowed;
  icao_format_valid?: ApiVerificationCheckAnyOfThreethreeValidationsIcaoFormatValid;
  names_consistent?: ApiVerificationCheckAnyOfThreethreeValidationsNamesConsistent;
  dates_of_birth_consistent?: ApiVerificationCheckAnyOfThreethreeValidationsDatesOfBirthConsistent;
  has_not_expired?: ApiVerificationCheckAnyOfThreethreeValidationsHasNotExpired;
  face_match?: ApiVerificationCheckAnyOfThreethreeValidationsFaceMatch;
  not_sample_or_internal_use?: ApiVerificationCheckAnyOfThreethreeValidationsNotSampleOrInternalUse;
  identifier_format_valid?: ApiVerificationCheckAnyOfThreethreeValidationsIdentifierFormatValid;
  matches_issuer_database?: ApiVerificationCheckAnyOfThreethreeValidationsMatchesIssuerDatabase;
  compound_identifiers_match?: ApiVerificationCheckAnyOfThreethreeValidationsCompoundIdentifiersMatch;
  security_features_present?: ApiVerificationCheckAnyOfThreethreeValidationsSecurityFeaturesPresent;
  document_borders_detected: ApiVerificationCheckAnyOfThreethreeValidationsDocumentBordersDetected;
  required_fields_extracted: ApiVerificationCheckAnyOfThreethreeValidationsRequiredFieldsExtracted;
};
