/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */

export type ApiVerificationCheckAnyOfSevenoneEvidenceType = 'payslip' | 'pension_annual_statement' | 'benefits_letter' | 'hmpps_letter' | 'nhs_letter' | 'bank_statement' | 'credit_card_statement' | 'mortgage_statement' | 'utility_bill' | 'mobile_phone_bill' | 'birth_or_adoption_certificate' | 'marriage_certificate' | 'naturalisation_or_reg_certificate' | 'education_certificate' | 'paye_tax_summary' | 'insurance_policy_agreement' | 'older_person_bus_pass';