/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OverallStatus } from './OverallStatus';
import {
    OverallStatusFromJSON,
    OverallStatusFromJSONTyped,
    OverallStatusToJSON,
    OverallStatusToJSONTyped,
} from './OverallStatus';

/**
 * 
 * @export
 * @interface BaseCheckVerifyEmailOrVerifyPhoneNumber
 */
export interface BaseCheckVerifyEmailOrVerifyPhoneNumber {
    /**
     * 
     * @type {OverallStatus}
     * @memberof BaseCheckVerifyEmailOrVerifyPhoneNumber
     */
    status: OverallStatus;
    /**
     * 
     * @type {string}
     * @memberof BaseCheckVerifyEmailOrVerifyPhoneNumber
     */
    check_type: BaseCheckVerifyEmailOrVerifyPhoneNumberCheckTypeEnum;
}


/**
 * @export
 */
export const BaseCheckVerifyEmailOrVerifyPhoneNumberCheckTypeEnum = {
    VerifyEmail: 'verify_email',
    VerifyPhoneNumber: 'verify_phone_number'
} as const;
export type BaseCheckVerifyEmailOrVerifyPhoneNumberCheckTypeEnum = typeof BaseCheckVerifyEmailOrVerifyPhoneNumberCheckTypeEnum[keyof typeof BaseCheckVerifyEmailOrVerifyPhoneNumberCheckTypeEnum];


/**
 * Check if a given object implements the BaseCheckVerifyEmailOrVerifyPhoneNumber interface.
 */
export function instanceOfBaseCheckVerifyEmailOrVerifyPhoneNumber(value: object): value is BaseCheckVerifyEmailOrVerifyPhoneNumber {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('check_type' in value) || value['check_type'] === undefined) return false;
    return true;
}

export function BaseCheckVerifyEmailOrVerifyPhoneNumberFromJSON(json: any): BaseCheckVerifyEmailOrVerifyPhoneNumber {
    return BaseCheckVerifyEmailOrVerifyPhoneNumberFromJSONTyped(json, false);
}

export function BaseCheckVerifyEmailOrVerifyPhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseCheckVerifyEmailOrVerifyPhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OverallStatusFromJSON(json['status']),
        'check_type': json['check_type'],
    };
}

export function BaseCheckVerifyEmailOrVerifyPhoneNumberToJSON(json: any): BaseCheckVerifyEmailOrVerifyPhoneNumber {
    return BaseCheckVerifyEmailOrVerifyPhoneNumberToJSONTyped(json, false);
}

export function BaseCheckVerifyEmailOrVerifyPhoneNumberToJSONTyped(value?: BaseCheckVerifyEmailOrVerifyPhoneNumber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OverallStatusToJSON(value['status']),
        'check_type': value['check_type'],
    };
}

