/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { CitizenCardValidationApiDocumentBordersDetected } from './citizenCardValidationApiDocumentBordersDetected';
import type { CitizenCardValidationApiFaceMatch } from './citizenCardValidationApiFaceMatch';
import type { ValidationOutcomeApi } from './validationOutcomeApi';

export interface CitizenCardValidationApi {
  /** Whether the required fields were extracted. */
  required_fields_extracted: ValidationOutcomeApi;
  /** Whether the correct document dimensions were detected (with score). */
  document_borders_detected: CitizenCardValidationApiDocumentBordersDetected;
  /** Whether the photo ID face matches the video selfie (with score). */
  face_match?: CitizenCardValidationApiFaceMatch;
  /** Whether the dates of birth matches other evidence. */
  dates_of_birth_consistent?: ValidationOutcomeApi;
  /** Whether the name matches other evidence. */
  names_consistent?: ValidationOutcomeApi;
  /** Whether the referee is 18 or over. */
  referee_over_18?: ValidationOutcomeApi;
  /** Whether the referee biometrics differ from the user. */
  referee_biometrics_dissimilar?: ValidationOutcomeApi;
  /** Whether the card details match the issuer database. */
  matches_issuer_database: ValidationOutcomeApi;
  /** Whether the document is in date. Omitted when the flow permits expired documents. */
  has_not_expired?: ValidationOutcomeApi;
}
