/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateTeamResponseCredentials } from './createTeamResponseCredentials';

/**
 * Response from creating a new team
 */
export interface CreateTeamResponse {
  /** Unique identifier for the created team */
  id: string;
  /** The name of the team. */
  name: string;
  /** The public name of the team, shown in end-user facing screens and communications. If set, overrides the name. */
  public_name?: string;
  /** ISO 8601 timestamp of team creation */
  created_at: string;
  /** Production API credentials for this team */
  credentials: CreateTeamResponseCredentials;
}
