/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordCreditBureauVerificationChecksCheckResult } from './RecordCreditBureauVerificationChecksCheckResult';
import {
    RecordCreditBureauVerificationChecksCheckResultFromJSON,
    RecordCreditBureauVerificationChecksCheckResultFromJSONTyped,
    RecordCreditBureauVerificationChecksCheckResultToJSON,
    RecordCreditBureauVerificationChecksCheckResultToJSONTyped,
} from './RecordCreditBureauVerificationChecksCheckResult';
import type { CheckState } from './CheckState';
import {
    CheckStateFromJSON,
    CheckStateFromJSONTyped,
    CheckStateToJSON,
    CheckStateToJSONTyped,
} from './CheckState';

/**
 * 
 * @export
 * @interface CreditBureauVerificationReport
 */
export interface CreditBureauVerificationReport {
    /**
     * 
     * @type {CheckState}
     * @memberof CreditBureauVerificationReport
     */
    state: CheckState;
    /**
     * 
     * @type {RecordCreditBureauVerificationChecksCheckResult}
     * @memberof CreditBureauVerificationReport
     */
    checks: RecordCreditBureauVerificationChecksCheckResult;
}



/**
 * Check if a given object implements the CreditBureauVerificationReport interface.
 */
export function instanceOfCreditBureauVerificationReport(value: object): value is CreditBureauVerificationReport {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('checks' in value) || value['checks'] === undefined) return false;
    return true;
}

export function CreditBureauVerificationReportFromJSON(json: any): CreditBureauVerificationReport {
    return CreditBureauVerificationReportFromJSONTyped(json, false);
}

export function CreditBureauVerificationReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBureauVerificationReport {
    if (json == null) {
        return json;
    }
    return {
        
        'state': CheckStateFromJSON(json['state']),
        'checks': RecordCreditBureauVerificationChecksCheckResultFromJSON(json['checks']),
    };
}

export function CreditBureauVerificationReportToJSON(json: any): CreditBureauVerificationReport {
    return CreditBureauVerificationReportToJSONTyped(json, false);
}

export function CreditBureauVerificationReportToJSONTyped(value?: CreditBureauVerificationReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': CheckStateToJSON(value['state']),
        'checks': RecordCreditBureauVerificationChecksCheckResultToJSON(value['checks']),
    };
}

