/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */

export interface DigitalIdExtractedDetailsApi {
  /**
   * First name, if extracted. Otherwise null.
   * @nullable
   */
  first_name: string | null;
  /**
   * Last name, if extracted. Otherwise null.
   * @nullable
   */
  last_name: string | null;
  /**
   * Date of birth (YYYY-MM-DD), if extracted. Otherwise null.
   * @nullable
   */
  date_of_birth: string | null;
  /**
   * First line of address, if extracted. Otherwise null.
   * @nullable
   */
  first_line_of_address: string | null;
  /**
   * Postcode, if extracted. Otherwise null.
   * @nullable
   */
  postcode: string | null;
  /** Phone number, if provided by the provider. */
  phone_number?: string;
  /** Nationality, if provided by the provider. */
  nationality?: string;
  /** Document number, if provided by the provider. */
  document_number?: string;
  /** Document type (for example IdCard), if provided by the provider. */
  document_type?: string;
  /** Document issue date (YYYY-MM-DD), if provided by the provider. */
  issue_date?: string;
  /** Document expiration date (YYYY-MM-DD), if provided by the provider. */
  expiration_date?: string;
  /** Issuing country, if provided by the provider. */
  issuing_country?: string;
  /** Immigration status, if provided by the provider (eVisa flows). */
  immigration_status?: string;
}
