/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DigitalIdSessionStatus = {
    Created: 'created',
    Started: 'started',
    Verifying: 'verifying',
    Verified: 'verified',
    Enriching: 'enriching',
    Completed: 'completed',
    Failed: 'failed',
    Expired: 'expired',
    Cancelled: 'cancelled'
} as const;
export type DigitalIdSessionStatus = typeof DigitalIdSessionStatus[keyof typeof DigitalIdSessionStatus];


export function instanceOfDigitalIdSessionStatus(value: any): boolean {
    for (const key in DigitalIdSessionStatus) {
        if (Object.prototype.hasOwnProperty.call(DigitalIdSessionStatus, key)) {
            if (DigitalIdSessionStatus[key as keyof typeof DigitalIdSessionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DigitalIdSessionStatusFromJSON(json: any): DigitalIdSessionStatus {
    return DigitalIdSessionStatusFromJSONTyped(json, false);
}

export function DigitalIdSessionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigitalIdSessionStatus {
    return json as DigitalIdSessionStatus;
}

export function DigitalIdSessionStatusToJSON(value?: DigitalIdSessionStatus | null): any {
    return value as any;
}

export function DigitalIdSessionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DigitalIdSessionStatus {
    return value as DigitalIdSessionStatus;
}

