/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { DigitalIdSessionEnrichments } from './digitalIdSessionEnrichments';
import type { DigitalIdSessionKnownClaims } from './digitalIdSessionKnownClaims';
import type { DigitalIdSessionStatus } from './digitalIdSessionStatus';
import type { DigitalIdSessionVerifiedClaims } from './digitalIdSessionVerifiedClaims';

export interface DigitalIdSession {
  enrichments: DigitalIdSessionEnrichments;
  verified_claims: DigitalIdSessionVerifiedClaims;
  known_claims: DigitalIdSessionKnownClaims;
  /** @nullable */
  provider_id: string | null;
  flow_id: string;
  /** @nullable */
  redirect_url: string | null;
  expires_at: string;
  created_at: string;
  status: DigitalIdSessionStatus;
  id: string;
}
