/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationOutcomeApi } from './validationOutcomeApi';

export interface DigitalIdValidationsApi {
  /** Whether the applicant's name matches other evidence on the case. */
  names_consistent?: ValidationOutcomeApi;
  /** Whether the document has not expired. Only present if an expiration date was provided. */
  has_not_expired?: ValidationOutcomeApi;
  /** Whether an eVisa record was found for the provided details. Only present for eVisa flows. */
  evisa_exists?: ValidationOutcomeApi;
  /** Whether all required fields were extracted from the eVisa response. Only present for eVisa flows. */
  required_fields_extracted?: ValidationOutcomeApi;
  /** Whether the eVisa start date has begun. Only present for ImmigrationStatus and RightToRent. */
  evisa_started?: ValidationOutcomeApi;
  /** Whether the eVisa has not expired, or is indefinite. Only present for eVisa flows. */
  evisa_not_expired?: ValidationOutcomeApi;
}
