/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DocumentCompleteAndLegibleFailedReason = {
    OriginalDocInconclusive: 'ORIGINAL_DOC_INCONCLUSIVE',
    OriginalDocNotDetected: 'ORIGINAL_DOC_NOT_DETECTED'
} as const;
export type DocumentCompleteAndLegibleFailedReason = typeof DocumentCompleteAndLegibleFailedReason[keyof typeof DocumentCompleteAndLegibleFailedReason];


export function instanceOfDocumentCompleteAndLegibleFailedReason(value: any): boolean {
    for (const key in DocumentCompleteAndLegibleFailedReason) {
        if (Object.prototype.hasOwnProperty.call(DocumentCompleteAndLegibleFailedReason, key)) {
            if (DocumentCompleteAndLegibleFailedReason[key as keyof typeof DocumentCompleteAndLegibleFailedReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DocumentCompleteAndLegibleFailedReasonFromJSON(json: any): DocumentCompleteAndLegibleFailedReason {
    return DocumentCompleteAndLegibleFailedReasonFromJSONTyped(json, false);
}

export function DocumentCompleteAndLegibleFailedReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCompleteAndLegibleFailedReason {
    return json as DocumentCompleteAndLegibleFailedReason;
}

export function DocumentCompleteAndLegibleFailedReasonToJSON(value?: DocumentCompleteAndLegibleFailedReason | null): any {
    return value as any;
}

export function DocumentCompleteAndLegibleFailedReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): DocumentCompleteAndLegibleFailedReason {
    return value as DocumentCompleteAndLegibleFailedReason;
}

