/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DocumentAgeValidFailedReason = {
    PartialExtraction: 'PARTIAL_EXTRACTION',
    InvalidDocumentDateFormat: 'INVALID_DOCUMENT_DATE_FORMAT',
    DocumentDateExceedsValidityPeriod: 'DOCUMENT_DATE_EXCEEDS_VALIDITY_PERIOD'
} as const;
export type DocumentAgeValidFailedReason = typeof DocumentAgeValidFailedReason[keyof typeof DocumentAgeValidFailedReason];


export function instanceOfDocumentAgeValidFailedReason(value: any): boolean {
    for (const key in DocumentAgeValidFailedReason) {
        if (Object.prototype.hasOwnProperty.call(DocumentAgeValidFailedReason, key)) {
            if (DocumentAgeValidFailedReason[key as keyof typeof DocumentAgeValidFailedReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DocumentAgeValidFailedReasonFromJSON(json: any): DocumentAgeValidFailedReason {
    return DocumentAgeValidFailedReasonFromJSONTyped(json, false);
}

export function DocumentAgeValidFailedReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentAgeValidFailedReason {
    return json as DocumentAgeValidFailedReason;
}

export function DocumentAgeValidFailedReasonToJSON(value?: DocumentAgeValidFailedReason | null): any {
    return value as any;
}

export function DocumentAgeValidFailedReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): DocumentAgeValidFailedReason {
    return value as DocumentAgeValidFailedReason;
}

