/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { CheckDocumentFaceErrorCode } from './checkDocumentFaceErrorCode';
import type { CheckDrivingLicenceFailedReason } from './checkDrivingLicenceFailedReason';
import type { CheckSpecimenErrorCode } from './checkSpecimenErrorCode';
import type { CheckTamperingErrorCode } from './checkTamperingErrorCode';
import type { ScoreCheckDocumentDimensionsErrorCode } from './scoreCheckDocumentDimensionsErrorCode';
import type { ScoreCheckFaceMatchErrorCode } from './scoreCheckFaceMatchErrorCode';

export interface DrivingLicenceValidation {
  /** Whether all required fields were successfully extracted from the document. */
  required_fields_extracted: CheckDrivingLicenceFailedReason;
  /** Whether the licence has not passed its expiry date. */
  has_not_expired: CheckDrivingLicenceFailedReason;
  /** Whether the document appears to be a specimen or sample rather than a real issued document. */
  not_specimen: CheckSpecimenErrorCode;
  /** Whether the document appears to be a screenshot or has moire patterns indicating a photographed screen. */
  not_screenshot: CheckTamperingErrorCode;
  /** Whether the document dimensions matched the expected dimensions for the document type. */
  document_dimensions_matched: ScoreCheckDocumentDimensionsErrorCode;
  /** Whether the expected security features are present in the document. */
  document_features_present: CheckDrivingLicenceFailedReason;
  /** Whether a face was detected within the document's bounding box. */
  document_contains_face: CheckDocumentFaceErrorCode;
  /** Whether the document photo matched the face scan. Absent if no face scan was provided. */
  face_match?: ScoreCheckFaceMatchErrorCode;
}
