/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrichmentVerificationReport } from './EnrichmentVerificationReport';
import {
    EnrichmentVerificationReportFromJSON,
    EnrichmentVerificationReportFromJSONTyped,
    EnrichmentVerificationReportToJSON,
    EnrichmentVerificationReportToJSONTyped,
} from './EnrichmentVerificationReport';
import type { RadarResult } from './RadarResult';
import {
    RadarResultFromJSON,
    RadarResultFromJSONTyped,
    RadarResultToJSON,
    RadarResultToJSONTyped,
} from './RadarResult';

/**
 * 
 * @export
 * @interface Enrichments
 */
export interface Enrichments {
    /**
     * 
     * @type {EnrichmentVerificationReport}
     * @memberof Enrichments
     */
    aml: EnrichmentVerificationReport | null;
    /**
     * 
     * @type {EnrichmentVerificationReport}
     * @memberof Enrichments
     */
    online_footprint: EnrichmentVerificationReport | null;
    /**
     * 
     * @type {EnrichmentVerificationReport}
     * @memberof Enrichments
     */
    credit_bureau: EnrichmentVerificationReport | null;
    /**
     * 
     * @type {EnrichmentVerificationReport}
     * @memberof Enrichments
     */
    address_verification: EnrichmentVerificationReport | null;
    /**
     * 
     * @type {RadarResult}
     * @memberof Enrichments
     */
    radar: RadarResult | null;
}

/**
 * Check if a given object implements the Enrichments interface.
 */
export function instanceOfEnrichments(value: object): value is Enrichments {
    if (!('aml' in value) || value['aml'] === undefined) return false;
    if (!('online_footprint' in value) || value['online_footprint'] === undefined) return false;
    if (!('credit_bureau' in value) || value['credit_bureau'] === undefined) return false;
    if (!('address_verification' in value) || value['address_verification'] === undefined) return false;
    if (!('radar' in value) || value['radar'] === undefined) return false;
    return true;
}

export function EnrichmentsFromJSON(json: any): Enrichments {
    return EnrichmentsFromJSONTyped(json, false);
}

export function EnrichmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Enrichments {
    if (json == null) {
        return json;
    }
    return {
        
        'aml': EnrichmentVerificationReportFromJSON(json['aml']),
        'online_footprint': EnrichmentVerificationReportFromJSON(json['online_footprint']),
        'credit_bureau': EnrichmentVerificationReportFromJSON(json['credit_bureau']),
        'address_verification': EnrichmentVerificationReportFromJSON(json['address_verification']),
        'radar': RadarResultFromJSON(json['radar']),
    };
}

export function EnrichmentsToJSON(json: any): Enrichments {
    return EnrichmentsToJSONTyped(json, false);
}

export function EnrichmentsToJSONTyped(value?: Enrichments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aml': EnrichmentVerificationReportToJSON(value['aml']),
        'online_footprint': EnrichmentVerificationReportToJSON(value['online_footprint']),
        'credit_bureau': EnrichmentVerificationReportToJSON(value['credit_bureau']),
        'address_verification': EnrichmentVerificationReportToJSON(value['address_verification']),
        'radar': RadarResultToJSON(value['radar']),
    };
}

