/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EvisaNotExpiredFailedReason = {
    ShareCodeError: 'SHARE_CODE_ERROR',
    IncorrectDetails: 'INCORRECT_DETAILS',
    EvisaNotYetValid: 'EVISA_NOT_YET_VALID',
    ExpiryDatePassed: 'EXPIRY_DATE_PASSED'
} as const;
export type EvisaNotExpiredFailedReason = typeof EvisaNotExpiredFailedReason[keyof typeof EvisaNotExpiredFailedReason];


export function instanceOfEvisaNotExpiredFailedReason(value: any): boolean {
    for (const key in EvisaNotExpiredFailedReason) {
        if (Object.prototype.hasOwnProperty.call(EvisaNotExpiredFailedReason, key)) {
            if (EvisaNotExpiredFailedReason[key as keyof typeof EvisaNotExpiredFailedReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EvisaNotExpiredFailedReasonFromJSON(json: any): EvisaNotExpiredFailedReason {
    return EvisaNotExpiredFailedReasonFromJSONTyped(json, false);
}

export function EvisaNotExpiredFailedReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvisaNotExpiredFailedReason {
    return json as EvisaNotExpiredFailedReason;
}

export function EvisaNotExpiredFailedReasonToJSON(value?: EvisaNotExpiredFailedReason | null): any {
    return value as any;
}

export function EvisaNotExpiredFailedReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): EvisaNotExpiredFailedReason {
    return value as EvisaNotExpiredFailedReason;
}

