/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FailedReason } from './FailedReason';
import {
    FailedReasonFromJSON,
    FailedReasonFromJSONTyped,
    FailedReasonToJSON,
    FailedReasonToJSONTyped,
} from './FailedReason';
import type { ApiValidationStatus } from './ApiValidationStatus';
import {
    ApiValidationStatusFromJSON,
    ApiValidationStatusFromJSONTyped,
    ApiValidationStatusToJSON,
    ApiValidationStatusToJSONTyped,
} from './ApiValidationStatus';

/**
 * 
 * @export
 * @interface EvisaValidationResult
 */
export interface EvisaValidationResult {
    /**
     * 
     * @type {ApiValidationStatus}
     * @memberof EvisaValidationResult
     */
    status: ApiValidationStatus;
    /**
     * 
     * @type {Array<FailedReason>}
     * @memberof EvisaValidationResult
     */
    failed_reasons?: Array<FailedReason>;
}



/**
 * Check if a given object implements the EvisaValidationResult interface.
 */
export function instanceOfEvisaValidationResult(value: object): value is EvisaValidationResult {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EvisaValidationResultFromJSON(json: any): EvisaValidationResult {
    return EvisaValidationResultFromJSONTyped(json, false);
}

export function EvisaValidationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvisaValidationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ApiValidationStatusFromJSON(json['status']),
        'failed_reasons': json['failed_reasons'] == null ? undefined : ((json['failed_reasons'] as Array<any>).map(FailedReasonFromJSON)),
    };
}

export function EvisaValidationResultToJSON(json: any): EvisaValidationResult {
    return EvisaValidationResultToJSONTyped(json, false);
}

export function EvisaValidationResultToJSONTyped(value?: EvisaValidationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ApiValidationStatusToJSON(value['status']),
        'failed_reasons': value['failed_reasons'] == null ? undefined : ((value['failed_reasons'] as Array<any>).map(FailedReasonToJSON)),
    };
}

