/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EvisaExistsFailedReason = {
    ShareCodeError: 'SHARE_CODE_ERROR',
    IncorrectDetails: 'INCORRECT_DETAILS'
} as const;
export type EvisaExistsFailedReason = typeof EvisaExistsFailedReason[keyof typeof EvisaExistsFailedReason];


export function instanceOfEvisaExistsFailedReason(value: any): boolean {
    for (const key in EvisaExistsFailedReason) {
        if (Object.prototype.hasOwnProperty.call(EvisaExistsFailedReason, key)) {
            if (EvisaExistsFailedReason[key as keyof typeof EvisaExistsFailedReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EvisaExistsFailedReasonFromJSON(json: any): EvisaExistsFailedReason {
    return EvisaExistsFailedReasonFromJSONTyped(json, false);
}

export function EvisaExistsFailedReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvisaExistsFailedReason {
    return json as EvisaExistsFailedReason;
}

export function EvisaExistsFailedReasonToJSON(value?: EvisaExistsFailedReason | null): any {
    return value as any;
}

export function EvisaExistsFailedReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): EvisaExistsFailedReason {
    return value as EvisaExistsFailedReason;
}

