/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvisaNotExpiredFailedReason } from './EvisaNotExpiredFailedReason';
import {
    EvisaNotExpiredFailedReasonFromJSON,
    EvisaNotExpiredFailedReasonFromJSONTyped,
    EvisaNotExpiredFailedReasonToJSON,
    EvisaNotExpiredFailedReasonToJSONTyped,
} from './EvisaNotExpiredFailedReason';
import type { ApiValidationStatus } from './ApiValidationStatus';
import {
    ApiValidationStatusFromJSON,
    ApiValidationStatusFromJSONTyped,
    ApiValidationStatusToJSON,
    ApiValidationStatusToJSONTyped,
} from './ApiValidationStatus';

/**
 * 
 * @export
 * @interface EvisaNotExpiredResult
 */
export interface EvisaNotExpiredResult {
    /**
     * 
     * @type {ApiValidationStatus}
     * @memberof EvisaNotExpiredResult
     */
    status: ApiValidationStatus;
    /**
     * 
     * @type {Array<EvisaNotExpiredFailedReason>}
     * @memberof EvisaNotExpiredResult
     */
    failed_reasons?: Array<EvisaNotExpiredFailedReason>;
}



/**
 * Check if a given object implements the EvisaNotExpiredResult interface.
 */
export function instanceOfEvisaNotExpiredResult(value: object): value is EvisaNotExpiredResult {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EvisaNotExpiredResultFromJSON(json: any): EvisaNotExpiredResult {
    return EvisaNotExpiredResultFromJSONTyped(json, false);
}

export function EvisaNotExpiredResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvisaNotExpiredResult {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ApiValidationStatusFromJSON(json['status']),
        'failed_reasons': json['failed_reasons'] == null ? undefined : ((json['failed_reasons'] as Array<any>).map(EvisaNotExpiredFailedReasonFromJSON)),
    };
}

export function EvisaNotExpiredResultToJSON(json: any): EvisaNotExpiredResult {
    return EvisaNotExpiredResultToJSONTyped(json, false);
}

export function EvisaNotExpiredResultToJSONTyped(value?: EvisaNotExpiredResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ApiValidationStatusToJSON(value['status']),
        'failed_reasons': value['failed_reasons'] == null ? undefined : ((value['failed_reasons'] as Array<any>).map(EvisaNotExpiredFailedReasonToJSON)),
    };
}

