/* tslint:disable */
/* eslint-disable */
/**
 * Proper discriminated union for EvisaVerificationInput.
 * This file is auto-generated by post-processing script.
 */

import type { ImmigrationStatusInput } from './ImmigrationStatusInput';
import type { RightToWorkInput } from './RightToWorkInput';
import type { RightToRentInput } from './RightToRentInput';

import { ImmigrationStatusInputFromJSON, ImmigrationStatusInputToJSON } from './ImmigrationStatusInput';
import { RightToWorkInputFromJSON, RightToWorkInputToJSON } from './RightToWorkInput';
import { RightToRentInputFromJSON, RightToRentInputToJSON } from './RightToRentInput';

/**
 * Discriminated union of all EvisaVerificationInput types
 * @export
 */
export type EvisaVerificationInput =
  | ImmigrationStatusInput
  | RightToWorkInput
  | RightToRentInput;

export function EvisaVerificationInputFromJSON(json: any): EvisaVerificationInput {
  return EvisaVerificationInputFromJSONTyped(json, false);
}

export function EvisaVerificationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvisaVerificationInput {
  if (json == null) {
    return json;
  }
  
  if (ignoreDiscriminator) {
    // If ignoring discriminator, try to parse as first variant
    return ImmigrationStatusInputFromJSON(json);
  }
  
  // Use discriminator to determine which type to parse
  switch (json['sub_type']) {
    case 'ImmigrationStatus':
      return ImmigrationStatusInputFromJSON(json);
    case 'RightToWork':
      return RightToWorkInputFromJSON(json);
    case 'RightToRent':
      return RightToRentInputFromJSON(json);
    default:
      throw new Error(`Unknown sub_type value: ${json['sub_type']}`);
  }
}

export function EvisaVerificationInputToJSON(value: EvisaVerificationInput): any {
  return EvisaVerificationInputToJSONTyped(value, false);
}

export function EvisaVerificationInputToJSONTyped(value: EvisaVerificationInput | undefined, ignoreDiscriminator: boolean): any {
  if (value == null) {
    return value;
  }
  
  if (ignoreDiscriminator) {
    // If ignoring discriminator, serialize normally
  }
  
  // Use discriminator to determine which serializer to use
  switch ((value as any).sub_type) {
    case 'ImmigrationStatus':
      return ImmigrationStatusInputToJSON(value as ImmigrationStatusInput);
    case 'RightToWork':
      return RightToWorkInputToJSON(value as RightToWorkInput);
    case 'RightToRent':
      return RightToRentInputToJSON(value as RightToRentInput);
    default:
      throw new Error(`Unknown sub_type value: ${(value as any).sub_type}`);
  }
}
