/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvisaNotExpiredResult } from './EvisaNotExpiredResult';
import {
    EvisaNotExpiredResultFromJSON,
    EvisaNotExpiredResultFromJSONTyped,
    EvisaNotExpiredResultToJSON,
    EvisaNotExpiredResultToJSONTyped,
} from './EvisaNotExpiredResult';
import type { EvisaRequiredFieldsExtractedResult } from './EvisaRequiredFieldsExtractedResult';
import {
    EvisaRequiredFieldsExtractedResultFromJSON,
    EvisaRequiredFieldsExtractedResultFromJSONTyped,
    EvisaRequiredFieldsExtractedResultToJSON,
    EvisaRequiredFieldsExtractedResultToJSONTyped,
} from './EvisaRequiredFieldsExtractedResult';
import type { EvisaStartedResult } from './EvisaStartedResult';
import {
    EvisaStartedResultFromJSON,
    EvisaStartedResultFromJSONTyped,
    EvisaStartedResultToJSON,
    EvisaStartedResultToJSONTyped,
} from './EvisaStartedResult';
import type { EvisaExistsResult } from './EvisaExistsResult';
import {
    EvisaExistsResultFromJSON,
    EvisaExistsResultFromJSONTyped,
    EvisaExistsResultToJSON,
    EvisaExistsResultToJSONTyped,
} from './EvisaExistsResult';

/**
 * 
 * @export
 * @interface EvisaValidations
 */
export interface EvisaValidations {
    /**
     * 
     * @type {EvisaExistsResult}
     * @memberof EvisaValidations
     */
    evisa_exists?: EvisaExistsResult;
    /**
     * 
     * @type {EvisaRequiredFieldsExtractedResult}
     * @memberof EvisaValidations
     */
    required_fields_extracted?: EvisaRequiredFieldsExtractedResult;
    /**
     * 
     * @type {EvisaStartedResult}
     * @memberof EvisaValidations
     */
    evisa_started?: EvisaStartedResult;
    /**
     * 
     * @type {EvisaNotExpiredResult}
     * @memberof EvisaValidations
     */
    evisa_not_expired?: EvisaNotExpiredResult;
}

/**
 * Check if a given object implements the EvisaValidations interface.
 */
export function instanceOfEvisaValidations(value: object): value is EvisaValidations {
    return true;
}

export function EvisaValidationsFromJSON(json: any): EvisaValidations {
    return EvisaValidationsFromJSONTyped(json, false);
}

export function EvisaValidationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvisaValidations {
    if (json == null) {
        return json;
    }
    return {
        
        'evisa_exists': json['evisa_exists'] == null ? undefined : EvisaExistsResultFromJSON(json['evisa_exists']),
        'required_fields_extracted': json['required_fields_extracted'] == null ? undefined : EvisaRequiredFieldsExtractedResultFromJSON(json['required_fields_extracted']),
        'evisa_started': json['evisa_started'] == null ? undefined : EvisaStartedResultFromJSON(json['evisa_started']),
        'evisa_not_expired': json['evisa_not_expired'] == null ? undefined : EvisaNotExpiredResultFromJSON(json['evisa_not_expired']),
    };
}

export function EvisaValidationsToJSON(json: any): EvisaValidations {
    return EvisaValidationsToJSONTyped(json, false);
}

export function EvisaValidationsToJSONTyped(value?: EvisaValidations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evisa_exists': EvisaExistsResultToJSON(value['evisa_exists']),
        'required_fields_extracted': EvisaRequiredFieldsExtractedResultToJSON(value['required_fields_extracted']),
        'evisa_started': EvisaStartedResultToJSON(value['evisa_started']),
        'evisa_not_expired': EvisaNotExpiredResultToJSON(value['evisa_not_expired']),
    };
}

