/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FraudFlag = {
    FaceScanBlocked: 'FACE_SCAN_BLOCKED',
    NameSuspicious: 'NAME_SUSPICIOUS',
    BurnerEmail: 'BURNER_EMAIL',
    BlockedEmail: 'BLOCKED_EMAIL',
    BurnerPhoneNumber: 'BURNER_PHONE_NUMBER',
    HighRiskCountryPhoneNumber: 'HIGH_RISK_COUNTRY_PHONE_NUMBER'
} as const;
export type FraudFlag = typeof FraudFlag[keyof typeof FraudFlag];


export function instanceOfFraudFlag(value: any): boolean {
    for (const key in FraudFlag) {
        if (Object.prototype.hasOwnProperty.call(FraudFlag, key)) {
            if (FraudFlag[key as keyof typeof FraudFlag] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FraudFlagFromJSON(json: any): FraudFlag {
    return FraudFlagFromJSONTyped(json, false);
}

export function FraudFlagFromJSONTyped(json: any, ignoreDiscriminator: boolean): FraudFlag {
    return json as FraudFlag;
}

export function FraudFlagToJSON(value?: FraudFlag | null): any {
    return value as any;
}

export function FraudFlagToJSONTyped(value: any, ignoreDiscriminator: boolean): FraudFlag {
    return value as FraudFlag;
}

