/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { AmlVerificationReport } from './amlVerificationReport';
import type { CreditBureauVerificationReport } from './creditBureauVerificationReport';
import type { GetSmartLookupResponseChecksItem } from './getSmartLookupResponseChecksItem';
import type { OnlineFootprintVerificationReport } from './onlineFootprintVerificationReport';
import type { SmartLookupMetadata } from './smartLookupMetadata';

export interface GetSmartLookupResponse {
  id: string;
  team_id: string;
  checks: GetSmartLookupResponseChecksItem[];
  /** @nullable */
  first_name: string | null;
  /** @nullable */
  last_name: string | null;
  /** @nullable */
  first_line_of_address: string | null;
  /** @nullable */
  postcode: string | null;
  date_of_birth?: string;
  email?: string;
  phone?: string;
  /** Whether the overall check and its sub-checks passed, failed or somethng else. */
  credit_bureau_verification_report?: CreditBureauVerificationReport;
  online_footprint_verification_report?: OnlineFootprintVerificationReport;
  aml_verification_report?: AmlVerificationReport;
  metadata: SmartLookupMetadata;
  created_at: string;
}
