/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditBureauVerificationReport } from './CreditBureauVerificationReport';
import {
    CreditBureauVerificationReportFromJSON,
    CreditBureauVerificationReportFromJSONTyped,
    CreditBureauVerificationReportToJSON,
    CreditBureauVerificationReportToJSONTyped,
} from './CreditBureauVerificationReport';
import type { AddressVerificationReport } from './AddressVerificationReport';
import {
    AddressVerificationReportFromJSON,
    AddressVerificationReportFromJSONTyped,
    AddressVerificationReportToJSON,
    AddressVerificationReportToJSONTyped,
} from './AddressVerificationReport';

/**
 * 
 * @export
 * @interface GetSmartLookupResponse
 */
export interface GetSmartLookupResponse {
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    team_id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetSmartLookupResponse
     */
    checks: Array<GetSmartLookupResponseChecksEnum>;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    first_name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    last_name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    first_line_of_address: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    postcode: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    date_of_birth?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    phone?: string;
    /**
     * 
     * @type {AddressVerificationReport}
     * @memberof GetSmartLookupResponse
     */
    address_verification_report?: AddressVerificationReport;
    /**
     * 
     * @type {CreditBureauVerificationReport}
     * @memberof GetSmartLookupResponse
     */
    credit_bureau_verification_report?: CreditBureauVerificationReport;
    /**
     * Extra information to aid debugging. May change without notice.
     * @type {any}
     * @memberof GetSmartLookupResponse
     */
    metadata: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetSmartLookupResponse
     */
    created_at: string;
}


/**
 * @export
 */
export const GetSmartLookupResponseChecksEnum = {
    Address: 'Address',
    CreditBureau: 'CreditBureau'
} as const;
export type GetSmartLookupResponseChecksEnum = typeof GetSmartLookupResponseChecksEnum[keyof typeof GetSmartLookupResponseChecksEnum];


/**
 * Check if a given object implements the GetSmartLookupResponse interface.
 */
export function instanceOfGetSmartLookupResponse(value: object): value is GetSmartLookupResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('team_id' in value) || value['team_id'] === undefined) return false;
    if (!('checks' in value) || value['checks'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('first_line_of_address' in value) || value['first_line_of_address'] === undefined) return false;
    if (!('postcode' in value) || value['postcode'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function GetSmartLookupResponseFromJSON(json: any): GetSmartLookupResponse {
    return GetSmartLookupResponseFromJSONTyped(json, false);
}

export function GetSmartLookupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSmartLookupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'team_id': json['team_id'],
        'checks': json['checks'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'first_line_of_address': json['first_line_of_address'],
        'postcode': json['postcode'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address_verification_report': json['address_verification_report'] == null ? undefined : AddressVerificationReportFromJSON(json['address_verification_report']),
        'credit_bureau_verification_report': json['credit_bureau_verification_report'] == null ? undefined : CreditBureauVerificationReportFromJSON(json['credit_bureau_verification_report']),
        'metadata': json['metadata'],
        'created_at': json['created_at'],
    };
}

export function GetSmartLookupResponseToJSON(json: any): GetSmartLookupResponse {
    return GetSmartLookupResponseToJSONTyped(json, false);
}

export function GetSmartLookupResponseToJSONTyped(value?: GetSmartLookupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['team_id'],
        'checks': value['checks'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'first_line_of_address': value['first_line_of_address'],
        'postcode': value['postcode'],
        'date_of_birth': value['date_of_birth'],
        'email': value['email'],
        'phone': value['phone'],
        'address_verification_report': AddressVerificationReportToJSON(value['address_verification_report']),
        'credit_bureau_verification_report': CreditBureauVerificationReportToJSON(value['credit_bureau_verification_report']),
        'metadata': value['metadata'],
        'created_at': value['created_at'],
    };
}

