/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRadarCheckDetails } from './ApiRadarCheckDetails';
import {
    ApiRadarCheckDetailsFromJSON,
    ApiRadarCheckDetailsFromJSONTyped,
    ApiRadarCheckDetailsToJSON,
    ApiRadarCheckDetailsToJSONTyped,
} from './ApiRadarCheckDetails';
import type { ApiAmlCheck } from './ApiAmlCheck';
import {
    ApiAmlCheckFromJSON,
    ApiAmlCheckFromJSONTyped,
    ApiAmlCheckToJSON,
    ApiAmlCheckToJSONTyped,
} from './ApiAmlCheck';
import type { ApiRadarCheck } from './ApiRadarCheck';
import {
    ApiRadarCheckFromJSON,
    ApiRadarCheckFromJSONTyped,
    ApiRadarCheckToJSON,
    ApiRadarCheckToJSONTyped,
} from './ApiRadarCheck';
import type { ApiOfaCheck } from './ApiOfaCheck';
import {
    ApiOfaCheckFromJSON,
    ApiOfaCheckFromJSONTyped,
    ApiOfaCheckToJSON,
    ApiOfaCheckToJSONTyped,
} from './ApiOfaCheck';

/**
 * 
 * @export
 * @interface GetVerificationResponseEnrichmentsInner
 */
export interface GetVerificationResponseEnrichmentsInner {
    /**
     * 
     * @type {ApiRadarCheckDetails}
     * @memberof GetVerificationResponseEnrichmentsInner
     */
    details: ApiRadarCheckDetails;
    /**
     * 
     * @type {string}
     * @memberof GetVerificationResponseEnrichmentsInner
     */
    outcome: GetVerificationResponseEnrichmentsInnerOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetVerificationResponseEnrichmentsInner
     */
    check: GetVerificationResponseEnrichmentsInnerCheckEnum;
}


/**
 * @export
 */
export const GetVerificationResponseEnrichmentsInnerOutcomeEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Error: 'error'
} as const;
export type GetVerificationResponseEnrichmentsInnerOutcomeEnum = typeof GetVerificationResponseEnrichmentsInnerOutcomeEnum[keyof typeof GetVerificationResponseEnrichmentsInnerOutcomeEnum];

/**
 * @export
 */
export const GetVerificationResponseEnrichmentsInnerCheckEnum = {
    Radar: 'radar'
} as const;
export type GetVerificationResponseEnrichmentsInnerCheckEnum = typeof GetVerificationResponseEnrichmentsInnerCheckEnum[keyof typeof GetVerificationResponseEnrichmentsInnerCheckEnum];


/**
 * Check if a given object implements the GetVerificationResponseEnrichmentsInner interface.
 */
export function instanceOfGetVerificationResponseEnrichmentsInner(value: object): value is GetVerificationResponseEnrichmentsInner {
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('check' in value) || value['check'] === undefined) return false;
    return true;
}

export function GetVerificationResponseEnrichmentsInnerFromJSON(json: any): GetVerificationResponseEnrichmentsInner {
    return GetVerificationResponseEnrichmentsInnerFromJSONTyped(json, false);
}

export function GetVerificationResponseEnrichmentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVerificationResponseEnrichmentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'details': ApiRadarCheckDetailsFromJSON(json['details']),
        'outcome': json['outcome'],
        'check': json['check'],
    };
}

export function GetVerificationResponseEnrichmentsInnerToJSON(json: any): GetVerificationResponseEnrichmentsInner {
    return GetVerificationResponseEnrichmentsInnerToJSONTyped(json, false);
}

export function GetVerificationResponseEnrichmentsInnerToJSONTyped(value?: GetVerificationResponseEnrichmentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': ApiRadarCheckDetailsToJSON(value['details']),
        'outcome': value['outcome'],
        'check': value['check'],
    };
}

