/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OtpCheck } from './OtpCheck';
import {
    OtpCheckFromJSON,
    OtpCheckFromJSONTyped,
    OtpCheckToJSON,
    OtpCheckToJSONTyped,
} from './OtpCheck';
import type { ReviewUserCheck } from './ReviewUserCheck';
import {
    ReviewUserCheckFromJSON,
    ReviewUserCheckFromJSONTyped,
    ReviewUserCheckToJSON,
    ReviewUserCheckToJSONTyped,
} from './ReviewUserCheck';
import type { ReviewUserCheckAllOfConfirmedClaims } from './ReviewUserCheckAllOfConfirmedClaims';
import {
    ReviewUserCheckAllOfConfirmedClaimsFromJSON,
    ReviewUserCheckAllOfConfirmedClaimsFromJSONTyped,
    ReviewUserCheckAllOfConfirmedClaimsToJSON,
    ReviewUserCheckAllOfConfirmedClaimsToJSONTyped,
} from './ReviewUserCheckAllOfConfirmedClaims';
import type { VideoSelfieEvidenceItem } from './VideoSelfieEvidenceItem';
import {
    VideoSelfieEvidenceItemFromJSON,
    VideoSelfieEvidenceItemFromJSONTyped,
    VideoSelfieEvidenceItemToJSON,
    VideoSelfieEvidenceItemToJSONTyped,
} from './VideoSelfieEvidenceItem';
import type { BaseCheckExtendedVideoSelfieVideoSelfieEvidenceItem } from './BaseCheckExtendedVideoSelfieVideoSelfieEvidenceItem';
import {
    BaseCheckExtendedVideoSelfieVideoSelfieEvidenceItemFromJSON,
    BaseCheckExtendedVideoSelfieVideoSelfieEvidenceItemFromJSONTyped,
    BaseCheckExtendedVideoSelfieVideoSelfieEvidenceItemToJSON,
    BaseCheckExtendedVideoSelfieVideoSelfieEvidenceItemToJSONTyped,
} from './BaseCheckExtendedVideoSelfieVideoSelfieEvidenceItem';
import type { OverallStatus } from './OverallStatus';
import {
    OverallStatusFromJSON,
    OverallStatusFromJSONTyped,
    OverallStatusToJSON,
    OverallStatusToJSONTyped,
} from './OverallStatus';

/**
 * 
 * @export
 * @interface GetVerificationResponseChecksInner
 */
export interface GetVerificationResponseChecksInner {
    /**
     * 
     * @type {Array<VideoSelfieEvidenceItem>}
     * @memberof GetVerificationResponseChecksInner
     */
    recorded_past_attempts: Array<VideoSelfieEvidenceItem>;
    /**
     * 
     * @type {Array<VideoSelfieEvidenceItem>}
     * @memberof GetVerificationResponseChecksInner
     */
    submitted_evidence: Array<VideoSelfieEvidenceItem>;
    /**
     * 
     * @type {number}
     * @memberof GetVerificationResponseChecksInner
     */
    total_attempts: number;
    /**
     * 
     * @type {OverallStatus}
     * @memberof GetVerificationResponseChecksInner
     */
    status: OverallStatus;
    /**
     * 
     * @type {string}
     * @memberof GetVerificationResponseChecksInner
     */
    check_type: GetVerificationResponseChecksInnerCheckTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetVerificationResponseChecksInner
     */
    verified_at: string | null;
    /**
     * 
     * @type {ReviewUserCheckAllOfConfirmedClaims}
     * @memberof GetVerificationResponseChecksInner
     */
    confirmed_claims: ReviewUserCheckAllOfConfirmedClaims | null;
}


/**
 * @export
 */
export const GetVerificationResponseChecksInnerCheckTypeEnum = {
    VerifyUserDetails: 'verify_user_details'
} as const;
export type GetVerificationResponseChecksInnerCheckTypeEnum = typeof GetVerificationResponseChecksInnerCheckTypeEnum[keyof typeof GetVerificationResponseChecksInnerCheckTypeEnum];


/**
 * Check if a given object implements the GetVerificationResponseChecksInner interface.
 */
export function instanceOfGetVerificationResponseChecksInner(value: object): value is GetVerificationResponseChecksInner {
    if (!('recorded_past_attempts' in value) || value['recorded_past_attempts'] === undefined) return false;
    if (!('submitted_evidence' in value) || value['submitted_evidence'] === undefined) return false;
    if (!('total_attempts' in value) || value['total_attempts'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('check_type' in value) || value['check_type'] === undefined) return false;
    if (!('verified_at' in value) || value['verified_at'] === undefined) return false;
    if (!('confirmed_claims' in value) || value['confirmed_claims'] === undefined) return false;
    return true;
}

export function GetVerificationResponseChecksInnerFromJSON(json: any): GetVerificationResponseChecksInner {
    return GetVerificationResponseChecksInnerFromJSONTyped(json, false);
}

export function GetVerificationResponseChecksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVerificationResponseChecksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'recorded_past_attempts': ((json['recorded_past_attempts'] as Array<any>).map(VideoSelfieEvidenceItemFromJSON)),
        'submitted_evidence': ((json['submitted_evidence'] as Array<any>).map(VideoSelfieEvidenceItemFromJSON)),
        'total_attempts': json['total_attempts'],
        'status': OverallStatusFromJSON(json['status']),
        'check_type': json['check_type'],
        'verified_at': json['verified_at'],
        'confirmed_claims': ReviewUserCheckAllOfConfirmedClaimsFromJSON(json['confirmed_claims']),
    };
}

export function GetVerificationResponseChecksInnerToJSON(json: any): GetVerificationResponseChecksInner {
    return GetVerificationResponseChecksInnerToJSONTyped(json, false);
}

export function GetVerificationResponseChecksInnerToJSONTyped(value?: GetVerificationResponseChecksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recorded_past_attempts': ((value['recorded_past_attempts'] as Array<any>).map(VideoSelfieEvidenceItemToJSON)),
        'submitted_evidence': ((value['submitted_evidence'] as Array<any>).map(VideoSelfieEvidenceItemToJSON)),
        'total_attempts': value['total_attempts'],
        'status': OverallStatusToJSON(value['status']),
        'check_type': value['check_type'],
        'verified_at': value['verified_at'],
        'confirmed_claims': ReviewUserCheckAllOfConfirmedClaimsToJSON(value['confirmed_claims']),
    };
}

