/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImmigrationStatusVerificationResponseExtractedDetails } from './ImmigrationStatusVerificationResponseExtractedDetails';
import {
    ImmigrationStatusVerificationResponseExtractedDetailsFromJSON,
    ImmigrationStatusVerificationResponseExtractedDetailsFromJSONTyped,
    ImmigrationStatusVerificationResponseExtractedDetailsToJSON,
    ImmigrationStatusVerificationResponseExtractedDetailsToJSONTyped,
} from './ImmigrationStatusVerificationResponseExtractedDetails';
import type { ImmigrationStatusVerificationResponseValidations } from './ImmigrationStatusVerificationResponseValidations';
import {
    ImmigrationStatusVerificationResponseValidationsFromJSON,
    ImmigrationStatusVerificationResponseValidationsFromJSONTyped,
    ImmigrationStatusVerificationResponseValidationsToJSON,
    ImmigrationStatusVerificationResponseValidationsToJSONTyped,
} from './ImmigrationStatusVerificationResponseValidations';
import type { EvisaArtefact } from './EvisaArtefact';
import {
    EvisaArtefactFromJSON,
    EvisaArtefactFromJSONTyped,
    EvisaArtefactToJSON,
    EvisaArtefactToJSONTyped,
} from './EvisaArtefact';
import type { ApiValidationStatus } from './ApiValidationStatus';
import {
    ApiValidationStatusFromJSON,
    ApiValidationStatusFromJSONTyped,
    ApiValidationStatusToJSON,
    ApiValidationStatusToJSONTyped,
} from './ApiValidationStatus';

/**
 * 
 * @export
 * @interface ImmigrationStatusVerificationResponse
 */
export interface ImmigrationStatusVerificationResponse {
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponse
     */
    verification_method: ImmigrationStatusVerificationResponseVerificationMethodEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ImmigrationStatusVerificationResponse
     */
    billable: boolean;
    /**
     * 
     * @type {ApiValidationStatus}
     * @memberof ImmigrationStatusVerificationResponse
     */
    outcome: ApiValidationStatus;
    /**
     * 
     * @type {Array<EvisaArtefact>}
     * @memberof ImmigrationStatusVerificationResponse
     */
    artefacts: Array<EvisaArtefact>;
    /**
     * 
     * @type {ImmigrationStatusVerificationResponseValidations}
     * @memberof ImmigrationStatusVerificationResponse
     */
    validations: ImmigrationStatusVerificationResponseValidations;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponse
     */
    evidence_type: ImmigrationStatusVerificationResponseEvidenceTypeEnum;
    /**
     * 
     * @type {ImmigrationStatusVerificationResponseExtractedDetails}
     * @memberof ImmigrationStatusVerificationResponse
     */
    extracted_details: ImmigrationStatusVerificationResponseExtractedDetails;
}


/**
 * @export
 */
export const ImmigrationStatusVerificationResponseVerificationMethodEnum = {
    Evisa: 'evisa'
} as const;
export type ImmigrationStatusVerificationResponseVerificationMethodEnum = typeof ImmigrationStatusVerificationResponseVerificationMethodEnum[keyof typeof ImmigrationStatusVerificationResponseVerificationMethodEnum];

/**
 * @export
 */
export const ImmigrationStatusVerificationResponseEvidenceTypeEnum = {
    ImmigrationStatus: 'immigration_status'
} as const;
export type ImmigrationStatusVerificationResponseEvidenceTypeEnum = typeof ImmigrationStatusVerificationResponseEvidenceTypeEnum[keyof typeof ImmigrationStatusVerificationResponseEvidenceTypeEnum];


/**
 * Check if a given object implements the ImmigrationStatusVerificationResponse interface.
 */
export function instanceOfImmigrationStatusVerificationResponse(value: object): value is ImmigrationStatusVerificationResponse {
    if (!('verification_method' in value) || value['verification_method'] === undefined) return false;
    if (!('billable' in value) || value['billable'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('artefacts' in value) || value['artefacts'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('evidence_type' in value) || value['evidence_type'] === undefined) return false;
    if (!('extracted_details' in value) || value['extracted_details'] === undefined) return false;
    return true;
}

export function ImmigrationStatusVerificationResponseFromJSON(json: any): ImmigrationStatusVerificationResponse {
    return ImmigrationStatusVerificationResponseFromJSONTyped(json, false);
}

export function ImmigrationStatusVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImmigrationStatusVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verification_method': json['verification_method'],
        'billable': json['billable'],
        'outcome': ApiValidationStatusFromJSON(json['outcome']),
        'artefacts': ((json['artefacts'] as Array<any>).map(EvisaArtefactFromJSON)),
        'validations': ImmigrationStatusVerificationResponseValidationsFromJSON(json['validations']),
        'evidence_type': json['evidence_type'],
        'extracted_details': ImmigrationStatusVerificationResponseExtractedDetailsFromJSON(json['extracted_details']),
    };
}

export function ImmigrationStatusVerificationResponseToJSON(json: any): ImmigrationStatusVerificationResponse {
    return ImmigrationStatusVerificationResponseToJSONTyped(json, false);
}

export function ImmigrationStatusVerificationResponseToJSONTyped(value?: ImmigrationStatusVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_method': value['verification_method'],
        'billable': value['billable'],
        'outcome': ApiValidationStatusToJSON(value['outcome']),
        'artefacts': ((value['artefacts'] as Array<any>).map(EvisaArtefactToJSON)),
        'validations': ImmigrationStatusVerificationResponseValidationsToJSON(value['validations']),
        'evidence_type': value['evidence_type'],
        'extracted_details': ImmigrationStatusVerificationResponseExtractedDetailsToJSON(value['extracted_details']),
    };
}

