/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */

export type ImmigrationStatusInputPayload = {
  /** Reason for the verification (max 50 characters) */
  reason: string;
  /** Job title of the person being verified */
  job_title: string;
  /** Name of the company requesting the verification */
  company_name: string;
  /** Date of birth in YYYY-MM-DD or ISO 8601 format */
  date_of_birth: string;
  /** The 9-character share code from the UK Home Office */
  share_code: string;
};
