/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImmigrationStatusExtractedDetails } from './ImmigrationStatusExtractedDetails';
import {
    ImmigrationStatusExtractedDetailsFromJSON,
    ImmigrationStatusExtractedDetailsFromJSONTyped,
    ImmigrationStatusExtractedDetailsToJSON,
    ImmigrationStatusExtractedDetailsToJSONTyped,
} from './ImmigrationStatusExtractedDetails';

/**
 * 
 * @export
 * @interface ImmigrationStatusVerificationResponseExtractedDetails
 */
export interface ImmigrationStatusVerificationResponseExtractedDetails {
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    first_name?: string;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    last_name?: string;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    date_of_birth?: string;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    share_code?: string;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    reference_number?: string;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    expiration_date?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    valid_from?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    nationality?: string;
    /**
     * 
     * @type {string}
     * @memberof ImmigrationStatusVerificationResponseExtractedDetails
     */
    immigration_status?: string;
}

/**
 * Check if a given object implements the ImmigrationStatusVerificationResponseExtractedDetails interface.
 */
export function instanceOfImmigrationStatusVerificationResponseExtractedDetails(value: object): value is ImmigrationStatusVerificationResponseExtractedDetails {
    return true;
}

export function ImmigrationStatusVerificationResponseExtractedDetailsFromJSON(json: any): ImmigrationStatusVerificationResponseExtractedDetails {
    return ImmigrationStatusVerificationResponseExtractedDetailsFromJSONTyped(json, false);
}

export function ImmigrationStatusVerificationResponseExtractedDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImmigrationStatusVerificationResponseExtractedDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'first_name': json['first_name'] == null ? undefined : json['first_name'],
        'last_name': json['last_name'] == null ? undefined : json['last_name'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'share_code': json['share_code'] == null ? undefined : json['share_code'],
        'reference_number': json['reference_number'] == null ? undefined : json['reference_number'],
        'expiration_date': json['expiration_date'] == null ? undefined : json['expiration_date'],
        'valid_from': json['valid_from'] == null ? undefined : json['valid_from'],
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'immigration_status': json['immigration_status'] == null ? undefined : json['immigration_status'],
    };
}

export function ImmigrationStatusVerificationResponseExtractedDetailsToJSON(json: any): ImmigrationStatusVerificationResponseExtractedDetails {
    return ImmigrationStatusVerificationResponseExtractedDetailsToJSONTyped(json, false);
}

export function ImmigrationStatusVerificationResponseExtractedDetailsToJSONTyped(value?: ImmigrationStatusVerificationResponseExtractedDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'date_of_birth': value['date_of_birth'],
        'share_code': value['share_code'],
        'reference_number': value['reference_number'],
        'expiration_date': value['expiration_date'],
        'valid_from': value['valid_from'],
        'nationality': value['nationality'],
        'immigration_status': value['immigration_status'],
    };
}

