/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImmigrationStatusInputPayload
 */
export interface ImmigrationStatusInputPayload {
    /**
     * Reason for the verification (max 50 characters)
     * @type {string}
     * @memberof ImmigrationStatusInputPayload
     */
    reason: string;
    /**
     * Job title of the person being verified
     * @type {string}
     * @memberof ImmigrationStatusInputPayload
     */
    job_title: string;
    /**
     * Name of the company requesting the verification
     * @type {string}
     * @memberof ImmigrationStatusInputPayload
     */
    company_name: string;
    /**
     * Date of birth in YYYY-MM-DD or ISO 8601 format
     * @type {string}
     * @memberof ImmigrationStatusInputPayload
     */
    date_of_birth: string;
    /**
     * The 9-character share code from the UK Home Office
     * @type {string}
     * @memberof ImmigrationStatusInputPayload
     */
    share_code: string;
}

/**
 * Check if a given object implements the ImmigrationStatusInputPayload interface.
 */
export function instanceOfImmigrationStatusInputPayload(value: object): value is ImmigrationStatusInputPayload {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('job_title' in value) || value['job_title'] === undefined) return false;
    if (!('company_name' in value) || value['company_name'] === undefined) return false;
    if (!('date_of_birth' in value) || value['date_of_birth'] === undefined) return false;
    if (!('share_code' in value) || value['share_code'] === undefined) return false;
    return true;
}

export function ImmigrationStatusInputPayloadFromJSON(json: any): ImmigrationStatusInputPayload {
    return ImmigrationStatusInputPayloadFromJSONTyped(json, false);
}

export function ImmigrationStatusInputPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImmigrationStatusInputPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'job_title': json['job_title'],
        'company_name': json['company_name'],
        'date_of_birth': json['date_of_birth'],
        'share_code': json['share_code'],
    };
}

export function ImmigrationStatusInputPayloadToJSON(json: any): ImmigrationStatusInputPayload {
    return ImmigrationStatusInputPayloadToJSONTyped(json, false);
}

export function ImmigrationStatusInputPayloadToJSONTyped(value?: ImmigrationStatusInputPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'job_title': value['job_title'],
        'company_name': value['company_name'],
        'date_of_birth': value['date_of_birth'],
        'share_code': value['share_code'],
    };
}

