/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KnownClaimsAddress
 */
export interface KnownClaimsAddress {
    /**
     * 
     * @type {string}
     * @memberof KnownClaimsAddress
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof KnownClaimsAddress
     */
    postal_code?: string;
    /**
     * 
     * @type {string}
     * @memberof KnownClaimsAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof KnownClaimsAddress
     */
    line2?: string;
    /**
     * 
     * @type {string}
     * @memberof KnownClaimsAddress
     */
    line1?: string;
}

/**
 * Check if a given object implements the KnownClaimsAddress interface.
 */
export function instanceOfKnownClaimsAddress(value: object): value is KnownClaimsAddress {
    return true;
}

export function KnownClaimsAddressFromJSON(json: any): KnownClaimsAddress {
    return KnownClaimsAddressFromJSONTyped(json, false);
}

export function KnownClaimsAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnownClaimsAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'postal_code': json['postal_code'] == null ? undefined : json['postal_code'],
        'city': json['city'] == null ? undefined : json['city'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'line1': json['line1'] == null ? undefined : json['line1'],
    };
}

export function KnownClaimsAddressToJSON(json: any): KnownClaimsAddress {
    return KnownClaimsAddressToJSONTyped(json, false);
}

export function KnownClaimsAddressToJSONTyped(value?: KnownClaimsAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'postal_code': value['postal_code'],
        'city': value['city'],
        'line2': value['line2'],
        'line1': value['line1'],
    };
}

