/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OverallStatus } from './OverallStatus';
import {
    OverallStatusFromJSON,
    OverallStatusFromJSONTyped,
    OverallStatusToJSON,
    OverallStatusToJSONTyped,
} from './OverallStatus';

/**
 * 
 * @export
 * @interface OtpCheck
 */
export interface OtpCheck {
    /**
     * 
     * @type {OverallStatus}
     * @memberof OtpCheck
     */
    status: OverallStatus;
    /**
     * 
     * @type {string}
     * @memberof OtpCheck
     */
    check_type: OtpCheckCheckTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OtpCheck
     */
    verified_at: string | null;
}


/**
 * @export
 */
export const OtpCheckCheckTypeEnum = {
    VerifyEmail: 'verify_email',
    VerifyPhoneNumber: 'verify_phone_number'
} as const;
export type OtpCheckCheckTypeEnum = typeof OtpCheckCheckTypeEnum[keyof typeof OtpCheckCheckTypeEnum];


/**
 * Check if a given object implements the OtpCheck interface.
 */
export function instanceOfOtpCheck(value: object): value is OtpCheck {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('check_type' in value) || value['check_type'] === undefined) return false;
    if (!('verified_at' in value) || value['verified_at'] === undefined) return false;
    return true;
}

export function OtpCheckFromJSON(json: any): OtpCheck {
    return OtpCheckFromJSONTyped(json, false);
}

export function OtpCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtpCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OverallStatusFromJSON(json['status']),
        'check_type': json['check_type'],
        'verified_at': json['verified_at'],
    };
}

export function OtpCheckToJSON(json: any): OtpCheck {
    return OtpCheckToJSONTyped(json, false);
}

export function OtpCheckToJSONTyped(value?: OtpCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OverallStatusToJSON(value['status']),
        'check_type': value['check_type'],
        'verified_at': value['verified_at'],
    };
}

