/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { ArtefactApi } from './artefactApi';
import type { PhotoIdEvidenceApi } from './photoIdEvidenceApi';
import type { PhotoIdEvidenceItemApiOutcome } from './photoIdEvidenceItemApiOutcome';
import type { PhotoIdEvidenceItemApiStep } from './photoIdEvidenceItemApiStep';
import type { PhotoIdExtractedDetailsApi } from './photoIdExtractedDetailsApi';
import type { PhotoIdValidationsApi } from './photoIdValidationsApi';

export interface PhotoIdEvidenceItemApi {
  /** A submitted Photo ID evidence. */
  step: PhotoIdEvidenceItemApiStep;
  /** The overall outcome of the document submission. */
  outcome: PhotoIdEvidenceItemApiOutcome;
  /** The type of photo ID submitted. */
  evidence_type: PhotoIdEvidenceApi;
  /** ISO 8601 timestamp for when this evidence attempt was started. */
  created_at: string;
  /** Files captured or uploaded for this evidence item. */
  artefacts: ArtefactApi[];
  /** Extracted details from the document.
Shape depends on evidence type. */
  extracted_details: PhotoIdExtractedDetailsApi;
  /** Validations performed on the document and their results.
Shape depends on evidence type. */
  validations: PhotoIdValidationsApi;
}
