/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckResult } from './CheckResult';
import {
    CheckResultFromJSON,
    CheckResultFromJSONTyped,
    CheckResultToJSON,
    CheckResultToJSONTyped,
} from './CheckResult';

/**
 * Construct a type with a set of properties K of type T
 * @export
 * @interface RecordAmlVerificationChecksCheckResult
 */
export interface RecordAmlVerificationChecksCheckResult {
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordAmlVerificationChecksCheckResult
     */
    AML_SANCTIONS_CHECK: CheckResult;
}

/**
 * Check if a given object implements the RecordAmlVerificationChecksCheckResult interface.
 */
export function instanceOfRecordAmlVerificationChecksCheckResult(value: object): value is RecordAmlVerificationChecksCheckResult {
    if (!('AML_SANCTIONS_CHECK' in value) || value['AML_SANCTIONS_CHECK'] === undefined) return false;
    return true;
}

export function RecordAmlVerificationChecksCheckResultFromJSON(json: any): RecordAmlVerificationChecksCheckResult {
    return RecordAmlVerificationChecksCheckResultFromJSONTyped(json, false);
}

export function RecordAmlVerificationChecksCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordAmlVerificationChecksCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'AML_SANCTIONS_CHECK': CheckResultFromJSON(json['AML_SANCTIONS_CHECK']),
    };
}

export function RecordAmlVerificationChecksCheckResultToJSON(json: any): RecordAmlVerificationChecksCheckResult {
    return RecordAmlVerificationChecksCheckResultToJSONTyped(json, false);
}

export function RecordAmlVerificationChecksCheckResultToJSONTyped(value?: RecordAmlVerificationChecksCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AML_SANCTIONS_CHECK': CheckResultToJSON(value['AML_SANCTIONS_CHECK']),
    };
}

