/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckResult } from './CheckResult';
import {
    CheckResultFromJSON,
    CheckResultFromJSONTyped,
    CheckResultToJSON,
    CheckResultToJSONTyped,
} from './CheckResult';

/**
 * Construct a type with a set of properties K of type T
 * @export
 * @interface RecordCreditBureauVerificationChecksCheckResult
 */
export interface RecordCreditBureauVerificationChecksCheckResult {
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordCreditBureauVerificationChecksCheckResult
     */
    IDENTITY_MATCH: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordCreditBureauVerificationChecksCheckResult
     */
    RESIDENCY_MATCH: CheckResult;
}

/**
 * Check if a given object implements the RecordCreditBureauVerificationChecksCheckResult interface.
 */
export function instanceOfRecordCreditBureauVerificationChecksCheckResult(value: object): value is RecordCreditBureauVerificationChecksCheckResult {
    if (!('IDENTITY_MATCH' in value) || value['IDENTITY_MATCH'] === undefined) return false;
    if (!('RESIDENCY_MATCH' in value) || value['RESIDENCY_MATCH'] === undefined) return false;
    return true;
}

export function RecordCreditBureauVerificationChecksCheckResultFromJSON(json: any): RecordCreditBureauVerificationChecksCheckResult {
    return RecordCreditBureauVerificationChecksCheckResultFromJSONTyped(json, false);
}

export function RecordCreditBureauVerificationChecksCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordCreditBureauVerificationChecksCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'IDENTITY_MATCH': CheckResultFromJSON(json['IDENTITY_MATCH']),
        'RESIDENCY_MATCH': CheckResultFromJSON(json['RESIDENCY_MATCH']),
    };
}

export function RecordCreditBureauVerificationChecksCheckResultToJSON(json: any): RecordCreditBureauVerificationChecksCheckResult {
    return RecordCreditBureauVerificationChecksCheckResultToJSONTyped(json, false);
}

export function RecordCreditBureauVerificationChecksCheckResultToJSONTyped(value?: RecordCreditBureauVerificationChecksCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IDENTITY_MATCH': CheckResultToJSON(value['IDENTITY_MATCH']),
        'RESIDENCY_MATCH': CheckResultToJSON(value['RESIDENCY_MATCH']),
    };
}

