/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckResult } from './CheckResult';
import {
    CheckResultFromJSON,
    CheckResultFromJSONTyped,
    CheckResultToJSON,
    CheckResultToJSONTyped,
} from './CheckResult';

/**
 * Construct a type with a set of properties K of type T
 * @export
 * @interface RecordOnlineFootprintVerificationChecksCheckResult
 */
export interface RecordOnlineFootprintVerificationChecksCheckResult {
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordOnlineFootprintVerificationChecksCheckResult
     */
    EMAIL_SCORE: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof RecordOnlineFootprintVerificationChecksCheckResult
     */
    PHONE_SCORE: CheckResult;
}

/**
 * Check if a given object implements the RecordOnlineFootprintVerificationChecksCheckResult interface.
 */
export function instanceOfRecordOnlineFootprintVerificationChecksCheckResult(value: object): value is RecordOnlineFootprintVerificationChecksCheckResult {
    if (!('EMAIL_SCORE' in value) || value['EMAIL_SCORE'] === undefined) return false;
    if (!('PHONE_SCORE' in value) || value['PHONE_SCORE'] === undefined) return false;
    return true;
}

export function RecordOnlineFootprintVerificationChecksCheckResultFromJSON(json: any): RecordOnlineFootprintVerificationChecksCheckResult {
    return RecordOnlineFootprintVerificationChecksCheckResultFromJSONTyped(json, false);
}

export function RecordOnlineFootprintVerificationChecksCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordOnlineFootprintVerificationChecksCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'EMAIL_SCORE': CheckResultFromJSON(json['EMAIL_SCORE']),
        'PHONE_SCORE': CheckResultFromJSON(json['PHONE_SCORE']),
    };
}

export function RecordOnlineFootprintVerificationChecksCheckResultToJSON(json: any): RecordOnlineFootprintVerificationChecksCheckResult {
    return RecordOnlineFootprintVerificationChecksCheckResultToJSONTyped(json, false);
}

export function RecordOnlineFootprintVerificationChecksCheckResultToJSONTyped(value?: RecordOnlineFootprintVerificationChecksCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'EMAIL_SCORE': CheckResultToJSON(value['EMAIL_SCORE']),
        'PHONE_SCORE': CheckResultToJSON(value['PHONE_SCORE']),
    };
}

