/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { RefereeEvidenceItemApiOutcome } from './refereeEvidenceItemApiOutcome';
import type { RefereeEvidenceItemApiStep } from './refereeEvidenceItemApiStep';
import type { VouchDetailsApi } from './vouchDetailsApi';
import type { VouchEvidenceApi } from './vouchEvidenceApi';
import type { VouchValidationsApi } from './vouchValidationsApi';

export interface RefereeEvidenceItemApi {
  /** A submitted vouch evidence. */
  step: RefereeEvidenceItemApiStep;
  /** The overall outcome of the referee verification. */
  outcome: RefereeEvidenceItemApiOutcome;
  /** The referee type used. */
  evidence_type: VouchEvidenceApi;
  /** ISO 8601 timestamp for when the vouch request was sent to the referee. */
  created_at: string;
  /** Details of the referee. */
  extracted_details: VouchDetailsApi;
  /** Validations performed on the vouching relationship and their results. */
  validations: VouchValidationsApi;
}
