/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RequiredFieldsExtractedFailedReason = {
    PartialExtraction: 'PARTIAL_EXTRACTION'
} as const;
export type RequiredFieldsExtractedFailedReason = typeof RequiredFieldsExtractedFailedReason[keyof typeof RequiredFieldsExtractedFailedReason];


export function instanceOfRequiredFieldsExtractedFailedReason(value: any): boolean {
    for (const key in RequiredFieldsExtractedFailedReason) {
        if (Object.prototype.hasOwnProperty.call(RequiredFieldsExtractedFailedReason, key)) {
            if (RequiredFieldsExtractedFailedReason[key as keyof typeof RequiredFieldsExtractedFailedReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RequiredFieldsExtractedFailedReasonFromJSON(json: any): RequiredFieldsExtractedFailedReason {
    return RequiredFieldsExtractedFailedReasonFromJSONTyped(json, false);
}

export function RequiredFieldsExtractedFailedReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequiredFieldsExtractedFailedReason {
    return json as RequiredFieldsExtractedFailedReason;
}

export function RequiredFieldsExtractedFailedReasonToJSON(value?: RequiredFieldsExtractedFailedReason | null): any {
    return value as any;
}

export function RequiredFieldsExtractedFailedReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): RequiredFieldsExtractedFailedReason {
    return value as RequiredFieldsExtractedFailedReason;
}

