/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */

export interface RequestVerificationInput {
  /** The user's email address */
  email: string;
  /** The user's first name, if you have it */
  first_name?: string;
  /** The user's last name, if you have it */
  last_name?: string;
  /** The user's street address, if you have it */
  street_address?: string;
  /** The user's postcode, if you have it */
  postcode?: string;
  /** The user's date of birth, if you have it. Format as YYYY-MM-DD or ISO 8601 */
  date_of_birth?: string;
  /** Which verification flow to use.

Get the flow ID from the URL of the builder page.

For example: `/admin/teams/abc123/builder/[workflow_id]`

If not provided, the last published flow is used instead. */
  workflow_id?: string;
  /** An identifier from your own systems, to avoid needing to store Vouchsafe's own ID */
  external_id?: string;
  /** A generic or unique URL to send the user back to upon success.

If not provided, the verification flow default will be used. */
  redirect_url?: string;
  /** When will the verification session expire and the user cease getting reminders?

If not provided, the verification flow default will be used. */
  expires_at?: string;
}
