/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestVerificationInput
 */
export interface RequestVerificationInput {
    /**
     * The user's email address
     * @type {string}
     * @memberof RequestVerificationInput
     */
    email: string;
    /**
     * The user's first name, if you have it
     * @type {string}
     * @memberof RequestVerificationInput
     */
    first_name?: string;
    /**
     * The user's last name, if you have it
     * @type {string}
     * @memberof RequestVerificationInput
     */
    last_name?: string;
    /**
     * The user's street address, if you have it
     * @type {string}
     * @memberof RequestVerificationInput
     */
    street_address?: string;
    /**
     * The user's postcode, if you have it
     * @type {string}
     * @memberof RequestVerificationInput
     */
    postcode?: string;
    /**
     * The user's date of birth, if you have it. Format as YYYY-MM-DD or ISO 8601
     * @type {string}
     * @memberof RequestVerificationInput
     */
    date_of_birth?: string;
    /**
     * Which verification flow to use.
     * 
     * Get the flow ID from the URL of the builder page.
     * 
     * For example: `/admin/teams/abc123/builder/[workflow_id]`
     * 
     * If not provided, the last published flow is used instead.
     * @type {string}
     * @memberof RequestVerificationInput
     */
    workflow_id?: string;
    /**
     * An identifier from your own systems, to avoid needing to store Vouchsafe's own ID
     * @type {string}
     * @memberof RequestVerificationInput
     */
    external_id?: string;
    /**
     * A generic or unique URL to send the user back to upon success.
     * 
     * If not provided, the verification flow default will be used.
     * @type {string}
     * @memberof RequestVerificationInput
     */
    redirect_url?: string;
    /**
     * When will the verification session expire and the user cease getting reminders?
     * 
     * If not provided, the verification flow default will be used.
     * @type {string}
     * @memberof RequestVerificationInput
     */
    expires_at?: string;
}

/**
 * Check if a given object implements the RequestVerificationInput interface.
 */
export function instanceOfRequestVerificationInput(value: object): value is RequestVerificationInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RequestVerificationInputFromJSON(json: any): RequestVerificationInput {
    return RequestVerificationInputFromJSONTyped(json, false);
}

export function RequestVerificationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestVerificationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'first_name': json['first_name'] == null ? undefined : json['first_name'],
        'last_name': json['last_name'] == null ? undefined : json['last_name'],
        'street_address': json['street_address'] == null ? undefined : json['street_address'],
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'workflow_id': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'external_id': json['external_id'] == null ? undefined : json['external_id'],
        'redirect_url': json['redirect_url'] == null ? undefined : json['redirect_url'],
        'expires_at': json['expires_at'] == null ? undefined : json['expires_at'],
    };
}

export function RequestVerificationInputToJSON(json: any): RequestVerificationInput {
    return RequestVerificationInputToJSONTyped(json, false);
}

export function RequestVerificationInputToJSONTyped(value?: RequestVerificationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'street_address': value['street_address'],
        'postcode': value['postcode'],
        'date_of_birth': value['date_of_birth'],
        'workflow_id': value['workflow_id'],
        'external_id': value['external_id'],
        'redirect_url': value['redirect_url'],
        'expires_at': value['expires_at'],
    };
}

