/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RightToWorkInputPayload
 */
export interface RightToWorkInputPayload {
    /**
     * Name of the company requesting the verification
     * @type {string}
     * @memberof RightToWorkInputPayload
     */
    company_name: string;
    /**
     * Date of birth in YYYY-MM-DD or ISO 8601 format
     * @type {string}
     * @memberof RightToWorkInputPayload
     */
    date_of_birth: string;
    /**
     * The 9-character share code from the UK Home Office
     * @type {string}
     * @memberof RightToWorkInputPayload
     */
    share_code: string;
}

/**
 * Check if a given object implements the RightToWorkInputPayload interface.
 */
export function instanceOfRightToWorkInputPayload(value: object): value is RightToWorkInputPayload {
    if (!('company_name' in value) || value['company_name'] === undefined) return false;
    if (!('date_of_birth' in value) || value['date_of_birth'] === undefined) return false;
    if (!('share_code' in value) || value['share_code'] === undefined) return false;
    return true;
}

export function RightToWorkInputPayloadFromJSON(json: any): RightToWorkInputPayload {
    return RightToWorkInputPayloadFromJSONTyped(json, false);
}

export function RightToWorkInputPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): RightToWorkInputPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'company_name': json['company_name'],
        'date_of_birth': json['date_of_birth'],
        'share_code': json['share_code'],
    };
}

export function RightToWorkInputPayloadToJSON(json: any): RightToWorkInputPayload {
    return RightToWorkInputPayloadToJSONTyped(json, false);
}

export function RightToWorkInputPayloadToJSONTyped(value?: RightToWorkInputPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company_name': value['company_name'],
        'date_of_birth': value['date_of_birth'],
        'share_code': value['share_code'],
    };
}

