/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImmigrationStatusVerificationResponseValidations } from './ImmigrationStatusVerificationResponseValidations';
import {
    ImmigrationStatusVerificationResponseValidationsFromJSON,
    ImmigrationStatusVerificationResponseValidationsFromJSONTyped,
    ImmigrationStatusVerificationResponseValidationsToJSON,
    ImmigrationStatusVerificationResponseValidationsToJSONTyped,
} from './ImmigrationStatusVerificationResponseValidations';
import type { EvisaArtefact } from './EvisaArtefact';
import {
    EvisaArtefactFromJSON,
    EvisaArtefactFromJSONTyped,
    EvisaArtefactToJSON,
    EvisaArtefactToJSONTyped,
} from './EvisaArtefact';
import type { RightToRentVerificationResponseExtractedDetails } from './RightToRentVerificationResponseExtractedDetails';
import {
    RightToRentVerificationResponseExtractedDetailsFromJSON,
    RightToRentVerificationResponseExtractedDetailsFromJSONTyped,
    RightToRentVerificationResponseExtractedDetailsToJSON,
    RightToRentVerificationResponseExtractedDetailsToJSONTyped,
} from './RightToRentVerificationResponseExtractedDetails';
import type { ApiValidationStatus } from './ApiValidationStatus';
import {
    ApiValidationStatusFromJSON,
    ApiValidationStatusFromJSONTyped,
    ApiValidationStatusToJSON,
    ApiValidationStatusToJSONTyped,
} from './ApiValidationStatus';

/**
 * 
 * @export
 * @interface RightToRentVerificationResponse
 */
export interface RightToRentVerificationResponse {
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponse
     */
    verification_method: RightToRentVerificationResponseVerificationMethodEnum;
    /**
     * 
     * @type {boolean}
     * @memberof RightToRentVerificationResponse
     */
    billable: boolean;
    /**
     * 
     * @type {ApiValidationStatus}
     * @memberof RightToRentVerificationResponse
     */
    outcome: ApiValidationStatus;
    /**
     * 
     * @type {Array<EvisaArtefact>}
     * @memberof RightToRentVerificationResponse
     */
    artefacts: Array<EvisaArtefact>;
    /**
     * 
     * @type {ImmigrationStatusVerificationResponseValidations}
     * @memberof RightToRentVerificationResponse
     */
    validations: ImmigrationStatusVerificationResponseValidations;
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponse
     */
    evidence_type: RightToRentVerificationResponseEvidenceTypeEnum;
    /**
     * 
     * @type {RightToRentVerificationResponseExtractedDetails}
     * @memberof RightToRentVerificationResponse
     */
    extracted_details: RightToRentVerificationResponseExtractedDetails;
}


/**
 * @export
 */
export const RightToRentVerificationResponseVerificationMethodEnum = {
    Evisa: 'evisa'
} as const;
export type RightToRentVerificationResponseVerificationMethodEnum = typeof RightToRentVerificationResponseVerificationMethodEnum[keyof typeof RightToRentVerificationResponseVerificationMethodEnum];

/**
 * @export
 */
export const RightToRentVerificationResponseEvidenceTypeEnum = {
    RightToRent: 'right_to_rent'
} as const;
export type RightToRentVerificationResponseEvidenceTypeEnum = typeof RightToRentVerificationResponseEvidenceTypeEnum[keyof typeof RightToRentVerificationResponseEvidenceTypeEnum];


/**
 * Check if a given object implements the RightToRentVerificationResponse interface.
 */
export function instanceOfRightToRentVerificationResponse(value: object): value is RightToRentVerificationResponse {
    if (!('verification_method' in value) || value['verification_method'] === undefined) return false;
    if (!('billable' in value) || value['billable'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('artefacts' in value) || value['artefacts'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('evidence_type' in value) || value['evidence_type'] === undefined) return false;
    if (!('extracted_details' in value) || value['extracted_details'] === undefined) return false;
    return true;
}

export function RightToRentVerificationResponseFromJSON(json: any): RightToRentVerificationResponse {
    return RightToRentVerificationResponseFromJSONTyped(json, false);
}

export function RightToRentVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RightToRentVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verification_method': json['verification_method'],
        'billable': json['billable'],
        'outcome': ApiValidationStatusFromJSON(json['outcome']),
        'artefacts': ((json['artefacts'] as Array<any>).map(EvisaArtefactFromJSON)),
        'validations': ImmigrationStatusVerificationResponseValidationsFromJSON(json['validations']),
        'evidence_type': json['evidence_type'],
        'extracted_details': RightToRentVerificationResponseExtractedDetailsFromJSON(json['extracted_details']),
    };
}

export function RightToRentVerificationResponseToJSON(json: any): RightToRentVerificationResponse {
    return RightToRentVerificationResponseToJSONTyped(json, false);
}

export function RightToRentVerificationResponseToJSONTyped(value?: RightToRentVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_method': value['verification_method'],
        'billable': value['billable'],
        'outcome': ApiValidationStatusToJSON(value['outcome']),
        'artefacts': ((value['artefacts'] as Array<any>).map(EvisaArtefactToJSON)),
        'validations': ImmigrationStatusVerificationResponseValidationsToJSON(value['validations']),
        'evidence_type': value['evidence_type'],
        'extracted_details': RightToRentVerificationResponseExtractedDetailsToJSON(value['extracted_details']),
    };
}

