/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImmigrationStatusVerificationResponseValidations } from './ImmigrationStatusVerificationResponseValidations';
import {
    ImmigrationStatusVerificationResponseValidationsFromJSON,
    ImmigrationStatusVerificationResponseValidationsFromJSONTyped,
    ImmigrationStatusVerificationResponseValidationsToJSON,
    ImmigrationStatusVerificationResponseValidationsToJSONTyped,
} from './ImmigrationStatusVerificationResponseValidations';
import type { EvisaArtefact } from './EvisaArtefact';
import {
    EvisaArtefactFromJSON,
    EvisaArtefactFromJSONTyped,
    EvisaArtefactToJSON,
    EvisaArtefactToJSONTyped,
} from './EvisaArtefact';
import type { ApiValidationStatus } from './ApiValidationStatus';
import {
    ApiValidationStatusFromJSON,
    ApiValidationStatusFromJSONTyped,
    ApiValidationStatusToJSON,
    ApiValidationStatusToJSONTyped,
} from './ApiValidationStatus';
import type { RightToWorkVerificationResponseExtractedDetails } from './RightToWorkVerificationResponseExtractedDetails';
import {
    RightToWorkVerificationResponseExtractedDetailsFromJSON,
    RightToWorkVerificationResponseExtractedDetailsFromJSONTyped,
    RightToWorkVerificationResponseExtractedDetailsToJSON,
    RightToWorkVerificationResponseExtractedDetailsToJSONTyped,
} from './RightToWorkVerificationResponseExtractedDetails';

/**
 * 
 * @export
 * @interface RightToWorkVerificationResponse
 */
export interface RightToWorkVerificationResponse {
    /**
     * 
     * @type {string}
     * @memberof RightToWorkVerificationResponse
     */
    verification_method: RightToWorkVerificationResponseVerificationMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof RightToWorkVerificationResponse
     */
    evidence_type: RightToWorkVerificationResponseEvidenceTypeEnum;
    /**
     * 
     * @type {ApiValidationStatus}
     * @memberof RightToWorkVerificationResponse
     */
    outcome: ApiValidationStatus;
    /**
     * Whether this API call is billable. `true` when the eVisa was found on GOV.UK, `false` when the share code or date of birth was invalid.
     * @type {boolean}
     * @memberof RightToWorkVerificationResponse
     */
    billable: boolean;
    /**
     * 
     * @type {RightToWorkVerificationResponseExtractedDetails}
     * @memberof RightToWorkVerificationResponse
     */
    extracted_details: RightToWorkVerificationResponseExtractedDetails;
    /**
     * 
     * @type {Array<EvisaArtefact>}
     * @memberof RightToWorkVerificationResponse
     */
    artefacts: Array<EvisaArtefact>;
    /**
     * 
     * @type {ImmigrationStatusVerificationResponseValidations}
     * @memberof RightToWorkVerificationResponse
     */
    validations: ImmigrationStatusVerificationResponseValidations;
}


/**
 * @export
 */
export const RightToWorkVerificationResponseVerificationMethodEnum = {
    Evisa: 'evisa'
} as const;
export type RightToWorkVerificationResponseVerificationMethodEnum = typeof RightToWorkVerificationResponseVerificationMethodEnum[keyof typeof RightToWorkVerificationResponseVerificationMethodEnum];

/**
 * @export
 */
export const RightToWorkVerificationResponseEvidenceTypeEnum = {
    RightToWork: 'right_to_work'
} as const;
export type RightToWorkVerificationResponseEvidenceTypeEnum = typeof RightToWorkVerificationResponseEvidenceTypeEnum[keyof typeof RightToWorkVerificationResponseEvidenceTypeEnum];


/**
 * Check if a given object implements the RightToWorkVerificationResponse interface.
 */
export function instanceOfRightToWorkVerificationResponse(value: object): value is RightToWorkVerificationResponse {
    if (!('verification_method' in value) || value['verification_method'] === undefined) return false;
    if (!('evidence_type' in value) || value['evidence_type'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('billable' in value) || value['billable'] === undefined) return false;
    if (!('extracted_details' in value) || value['extracted_details'] === undefined) return false;
    if (!('artefacts' in value) || value['artefacts'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    return true;
}

export function RightToWorkVerificationResponseFromJSON(json: any): RightToWorkVerificationResponse {
    return RightToWorkVerificationResponseFromJSONTyped(json, false);
}

export function RightToWorkVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RightToWorkVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verification_method': json['verification_method'],
        'evidence_type': json['evidence_type'],
        'outcome': ApiValidationStatusFromJSON(json['outcome']),
        'billable': json['billable'],
        'extracted_details': RightToWorkVerificationResponseExtractedDetailsFromJSON(json['extracted_details']),
        'artefacts': ((json['artefacts'] as Array<any>).map(EvisaArtefactFromJSON)),
        'validations': ImmigrationStatusVerificationResponseValidationsFromJSON(json['validations']),
    };
}

export function RightToWorkVerificationResponseToJSON(json: any): RightToWorkVerificationResponse {
    return RightToWorkVerificationResponseToJSONTyped(json, false);
}

export function RightToWorkVerificationResponseToJSONTyped(value?: RightToWorkVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_method': value['verification_method'],
        'evidence_type': value['evidence_type'],
        'outcome': ApiValidationStatusToJSON(value['outcome']),
        'billable': value['billable'],
        'extracted_details': RightToWorkVerificationResponseExtractedDetailsToJSON(value['extracted_details']),
        'artefacts': ((value['artefacts'] as Array<any>).map(EvisaArtefactToJSON)),
        'validations': ImmigrationStatusVerificationResponseValidationsToJSON(value['validations']),
    };
}

