/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvisaBaseExtractedDetails } from './EvisaBaseExtractedDetails';
import {
    EvisaBaseExtractedDetailsFromJSON,
    EvisaBaseExtractedDetailsFromJSONTyped,
    EvisaBaseExtractedDetailsToJSON,
    EvisaBaseExtractedDetailsToJSONTyped,
} from './EvisaBaseExtractedDetails';

/**
 * 
 * @export
 * @interface RightToRentVerificationResponseExtractedDetails
 */
export interface RightToRentVerificationResponseExtractedDetails {
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponseExtractedDetails
     */
    first_name?: string;
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponseExtractedDetails
     */
    last_name?: string;
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponseExtractedDetails
     */
    date_of_birth?: string;
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponseExtractedDetails
     */
    share_code?: string;
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponseExtractedDetails
     */
    reference_number?: string;
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponseExtractedDetails
     */
    expiration_date?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RightToRentVerificationResponseExtractedDetails
     */
    valid_from?: string | null;
}

/**
 * Check if a given object implements the RightToRentVerificationResponseExtractedDetails interface.
 */
export function instanceOfRightToRentVerificationResponseExtractedDetails(value: object): value is RightToRentVerificationResponseExtractedDetails {
    return true;
}

export function RightToRentVerificationResponseExtractedDetailsFromJSON(json: any): RightToRentVerificationResponseExtractedDetails {
    return RightToRentVerificationResponseExtractedDetailsFromJSONTyped(json, false);
}

export function RightToRentVerificationResponseExtractedDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RightToRentVerificationResponseExtractedDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'first_name': json['first_name'] == null ? undefined : json['first_name'],
        'last_name': json['last_name'] == null ? undefined : json['last_name'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'share_code': json['share_code'] == null ? undefined : json['share_code'],
        'reference_number': json['reference_number'] == null ? undefined : json['reference_number'],
        'expiration_date': json['expiration_date'] == null ? undefined : json['expiration_date'],
        'valid_from': json['valid_from'] == null ? undefined : json['valid_from'],
    };
}

export function RightToRentVerificationResponseExtractedDetailsToJSON(json: any): RightToRentVerificationResponseExtractedDetails {
    return RightToRentVerificationResponseExtractedDetailsToJSONTyped(json, false);
}

export function RightToRentVerificationResponseExtractedDetailsToJSONTyped(value?: RightToRentVerificationResponseExtractedDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'date_of_birth': value['date_of_birth'],
        'share_code': value['share_code'],
        'reference_number': value['reference_number'],
        'expiration_date': value['expiration_date'],
        'valid_from': value['valid_from'],
    };
}

