/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { StepIdentityVouchApiMethod } from './stepIdentityVouchApiMethod';
import type { StepIdentityVouchApiOutcome } from './stepIdentityVouchApiOutcome';
import type { StepIdentityVouchApiStep } from './stepIdentityVouchApiStep';
import type { VouchDetailsApi } from './vouchDetailsApi';
import type { VouchEvidenceApi } from './vouchEvidenceApi';
import type { VouchValidationsApi } from './vouchValidationsApi';

export interface StepIdentityVouchApi {
  /** Proof of identity step — only present for v2 verifications. */
  step: StepIdentityVouchApiStep;
  /** Overall outcome of the evidence submission. */
  outcome: StepIdentityVouchApiOutcome;
  /** ISO 8601 timestamp for when this evidence attempt was started. */
  created_at: string;
  /** The method used to verify identity. */
  method: StepIdentityVouchApiMethod;
  /** The specific type of evidence submitted. */
  evidence_type: VouchEvidenceApi;
  /** Extracted details from the evidence. Shape depends on evidence type. */
  extracted_details: VouchDetailsApi;
  /** Validations performed on the evidence. Shape depends on evidence type. */
  validations: VouchValidationsApi;
}
