/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupportingDocumentVerificationResponseValidations } from './SupportingDocumentVerificationResponseValidations';
import {
    SupportingDocumentVerificationResponseValidationsFromJSON,
    SupportingDocumentVerificationResponseValidationsFromJSONTyped,
    SupportingDocumentVerificationResponseValidationsToJSON,
    SupportingDocumentVerificationResponseValidationsToJSONTyped,
} from './SupportingDocumentVerificationResponseValidations';
import type { SupportingDocumentVerificationResponseExtractedDetails } from './SupportingDocumentVerificationResponseExtractedDetails';
import {
    SupportingDocumentVerificationResponseExtractedDetailsFromJSON,
    SupportingDocumentVerificationResponseExtractedDetailsFromJSONTyped,
    SupportingDocumentVerificationResponseExtractedDetailsToJSON,
    SupportingDocumentVerificationResponseExtractedDetailsToJSONTyped,
} from './SupportingDocumentVerificationResponseExtractedDetails';
import type { SupportingDocumentEvidenceType } from './SupportingDocumentEvidenceType';
import {
    SupportingDocumentEvidenceTypeFromJSON,
    SupportingDocumentEvidenceTypeFromJSONTyped,
    SupportingDocumentEvidenceTypeToJSON,
    SupportingDocumentEvidenceTypeToJSONTyped,
} from './SupportingDocumentEvidenceType';
import type { ApiValidationStatus } from './ApiValidationStatus';
import {
    ApiValidationStatusFromJSON,
    ApiValidationStatusFromJSONTyped,
    ApiValidationStatusToJSON,
    ApiValidationStatusToJSONTyped,
} from './ApiValidationStatus';

/**
 * 
 * @export
 * @interface SupportingDocumentVerificationResponse
 */
export interface SupportingDocumentVerificationResponse {
    /**
     * 
     * @type {string}
     * @memberof SupportingDocumentVerificationResponse
     */
    verification_method: SupportingDocumentVerificationResponseVerificationMethodEnum;
    /**
     * 
     * @type {SupportingDocumentEvidenceType}
     * @memberof SupportingDocumentVerificationResponse
     */
    evidence_type: SupportingDocumentEvidenceType;
    /**
     * 
     * @type {boolean}
     * @memberof SupportingDocumentVerificationResponse
     */
    billable: boolean;
    /**
     * 
     * @type {ApiValidationStatus}
     * @memberof SupportingDocumentVerificationResponse
     */
    outcome: ApiValidationStatus;
    /**
     * 
     * @type {SupportingDocumentVerificationResponseExtractedDetails}
     * @memberof SupportingDocumentVerificationResponse
     */
    extracted_details: SupportingDocumentVerificationResponseExtractedDetails;
    /**
     * 
     * @type {SupportingDocumentVerificationResponseValidations}
     * @memberof SupportingDocumentVerificationResponse
     */
    validations: SupportingDocumentVerificationResponseValidations;
}


/**
 * @export
 */
export const SupportingDocumentVerificationResponseVerificationMethodEnum = {
    SupportingDocument: 'supporting_document'
} as const;
export type SupportingDocumentVerificationResponseVerificationMethodEnum = typeof SupportingDocumentVerificationResponseVerificationMethodEnum[keyof typeof SupportingDocumentVerificationResponseVerificationMethodEnum];


/**
 * Check if a given object implements the SupportingDocumentVerificationResponse interface.
 */
export function instanceOfSupportingDocumentVerificationResponse(value: object): value is SupportingDocumentVerificationResponse {
    if (!('verification_method' in value) || value['verification_method'] === undefined) return false;
    if (!('evidence_type' in value) || value['evidence_type'] === undefined) return false;
    if (!('billable' in value) || value['billable'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('extracted_details' in value) || value['extracted_details'] === undefined) return false;
    if (!('validations' in value) || value['validations'] === undefined) return false;
    return true;
}

export function SupportingDocumentVerificationResponseFromJSON(json: any): SupportingDocumentVerificationResponse {
    return SupportingDocumentVerificationResponseFromJSONTyped(json, false);
}

export function SupportingDocumentVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportingDocumentVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'verification_method': json['verification_method'],
        'evidence_type': SupportingDocumentEvidenceTypeFromJSON(json['evidence_type']),
        'billable': json['billable'],
        'outcome': ApiValidationStatusFromJSON(json['outcome']),
        'extracted_details': SupportingDocumentVerificationResponseExtractedDetailsFromJSON(json['extracted_details']),
        'validations': SupportingDocumentVerificationResponseValidationsFromJSON(json['validations']),
    };
}

export function SupportingDocumentVerificationResponseToJSON(json: any): SupportingDocumentVerificationResponse {
    return SupportingDocumentVerificationResponseToJSONTyped(json, false);
}

export function SupportingDocumentVerificationResponseToJSONTyped(value?: SupportingDocumentVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_method': value['verification_method'],
        'evidence_type': SupportingDocumentEvidenceTypeToJSON(value['evidence_type']),
        'billable': value['billable'],
        'outcome': ApiValidationStatusToJSON(value['outcome']),
        'extracted_details': SupportingDocumentVerificationResponseExtractedDetailsToJSON(value['extracted_details']),
        'validations': SupportingDocumentVerificationResponseValidationsToJSON(value['validations']),
    };
}

