/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SupportingDocumentEvidenceType = {
    Payslip: 'payslip',
    PensionAnnualStatement: 'pension_annual_statement',
    BenefitsLetter: 'benefits_letter',
    HmppsLetter: 'hmpps_letter',
    NhsLetter: 'nhs_letter',
    BankStatement: 'bank_statement',
    CreditCardStatement: 'credit_card_statement',
    MortgageStatement: 'mortgage_statement',
    UtilityBill: 'utility_bill',
    MobilePhoneBill: 'mobile_phone_bill'
} as const;
export type SupportingDocumentEvidenceType = typeof SupportingDocumentEvidenceType[keyof typeof SupportingDocumentEvidenceType];


export function instanceOfSupportingDocumentEvidenceType(value: any): boolean {
    for (const key in SupportingDocumentEvidenceType) {
        if (Object.prototype.hasOwnProperty.call(SupportingDocumentEvidenceType, key)) {
            if (SupportingDocumentEvidenceType[key as keyof typeof SupportingDocumentEvidenceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SupportingDocumentEvidenceTypeFromJSON(json: any): SupportingDocumentEvidenceType {
    return SupportingDocumentEvidenceTypeFromJSONTyped(json, false);
}

export function SupportingDocumentEvidenceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportingDocumentEvidenceType {
    return json as SupportingDocumentEvidenceType;
}

export function SupportingDocumentEvidenceTypeToJSON(value?: SupportingDocumentEvidenceType | null): any {
    return value as any;
}

export function SupportingDocumentEvidenceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SupportingDocumentEvidenceType {
    return value as SupportingDocumentEvidenceType;
}

