/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Extracted details from the supporting document
 */
export interface SupportingDocumentExtractedDetails {
  /** @nullable */
  first_name: string | null;
  /** @nullable */
  last_name: string | null;
  /** @nullable */
  first_line_of_address: string | null;
  /** @nullable */
  postcode: string | null;
  /** @nullable */
  document_date: string | null;
  /** @nullable */
  document_category: string | null;
  /** @nullable */
  unique_identifier: string | null;
  /** @nullable */
  issuer: string | null;
}
