/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiValidationStatus } from './ApiValidationStatus';
import {
    ApiValidationStatusFromJSON,
    ApiValidationStatusFromJSONTyped,
    ApiValidationStatusToJSON,
    ApiValidationStatusToJSONTyped,
} from './ApiValidationStatus';
import type { TamperingSignalsCheckFailedReason } from './TamperingSignalsCheckFailedReason';
import {
    TamperingSignalsCheckFailedReasonFromJSON,
    TamperingSignalsCheckFailedReasonFromJSONTyped,
    TamperingSignalsCheckFailedReasonToJSON,
    TamperingSignalsCheckFailedReasonToJSONTyped,
} from './TamperingSignalsCheckFailedReason';

/**
 * 
 * @export
 * @interface TamperingSignalsCheckResult
 */
export interface TamperingSignalsCheckResult {
    /**
     * 
     * @type {ApiValidationStatus}
     * @memberof TamperingSignalsCheckResult
     */
    status: ApiValidationStatus;
    /**
     * 
     * @type {Array<TamperingSignalsCheckFailedReason>}
     * @memberof TamperingSignalsCheckResult
     */
    failed_reasons?: Array<TamperingSignalsCheckFailedReason>;
}



/**
 * Check if a given object implements the TamperingSignalsCheckResult interface.
 */
export function instanceOfTamperingSignalsCheckResult(value: object): value is TamperingSignalsCheckResult {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TamperingSignalsCheckResultFromJSON(json: any): TamperingSignalsCheckResult {
    return TamperingSignalsCheckResultFromJSONTyped(json, false);
}

export function TamperingSignalsCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TamperingSignalsCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ApiValidationStatusFromJSON(json['status']),
        'failed_reasons': json['failed_reasons'] == null ? undefined : ((json['failed_reasons'] as Array<any>).map(TamperingSignalsCheckFailedReasonFromJSON)),
    };
}

export function TamperingSignalsCheckResultToJSON(json: any): TamperingSignalsCheckResult {
    return TamperingSignalsCheckResultToJSONTyped(json, false);
}

export function TamperingSignalsCheckResultToJSONTyped(value?: TamperingSignalsCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ApiValidationStatusToJSON(value['status']),
        'failed_reasons': value['failed_reasons'] == null ? undefined : ((value['failed_reasons'] as Array<any>).map(TamperingSignalsCheckFailedReasonToJSON)),
    };
}

