/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TamperingSignalsCheckFailedReason = {
    PossiblyTampered: 'POSSIBLY_TAMPERED'
} as const;
export type TamperingSignalsCheckFailedReason = typeof TamperingSignalsCheckFailedReason[keyof typeof TamperingSignalsCheckFailedReason];


export function instanceOfTamperingSignalsCheckFailedReason(value: any): boolean {
    for (const key in TamperingSignalsCheckFailedReason) {
        if (Object.prototype.hasOwnProperty.call(TamperingSignalsCheckFailedReason, key)) {
            if (TamperingSignalsCheckFailedReason[key as keyof typeof TamperingSignalsCheckFailedReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TamperingSignalsCheckFailedReasonFromJSON(json: any): TamperingSignalsCheckFailedReason {
    return TamperingSignalsCheckFailedReasonFromJSONTyped(json, false);
}

export function TamperingSignalsCheckFailedReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TamperingSignalsCheckFailedReason {
    return json as TamperingSignalsCheckFailedReason;
}

export function TamperingSignalsCheckFailedReasonToJSON(value?: TamperingSignalsCheckFailedReason | null): any {
    return value as any;
}

export function TamperingSignalsCheckFailedReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): TamperingSignalsCheckFailedReason {
    return value as TamperingSignalsCheckFailedReason;
}

