/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { TeamPlan } from './teamPlan';

export interface Team {
  /** The client ID of the team, as shown in the dashboard */
  id: string;
  /** The name of the team */
  name: string;
  /** The public name of the team, shown in end-user facing screens and communications. If set, overrides the name. */
  public_name: string;
  /** Which plan is the team on? */
  plan: TeamPlan;
  /** Path to the team's logo image */
  logo_url: string;
  /** When the team's details were last changed, formatted as an ISO 8601 string */
  updated_at: string;
  /** When the team was created, formatted as an ISO 8601 string */
  created_at: string;
}
