/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */

export interface UnfamiliarPhotoIdDetailsApi {
  /**
   * First name, if extracted. Otherwise null.
   * @nullable
   */
  first_name: string | null;
  /**
   * Last name, if extracted. Otherwise null.
   * @nullable
   */
  last_name: string | null;
  /**
   * Date of birth, if extracted. Otherwise null.
   * @nullable
   */
  date_of_birth: string | null;
  /**
   * Document number, if extracted. Otherwise null.
   * @nullable
   */
  document_number: string | null;
  /**
   * Expiry date, if present and extracted. Otherwise null.
   * @nullable
   */
  expiration_date: string | null;
}
