/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type { BankAccountEvidenceItemApi } from './bankAccountEvidenceItemApi';
import type { EvisaEvidenceItemApi } from './evisaEvidenceItemApi';
import type { PhotoIdEvidenceItemApi } from './photoIdEvidenceItemApi';
import type { RefereeEvidenceItemApi } from './refereeEvidenceItemApi';
import type { ReviewUserCheckApi } from './reviewUserCheckApi';
import type { StepAddressCreditReferenceAgencyApi } from './stepAddressCreditReferenceAgencyApi';
import type { StepAddressDigitalIdApi } from './stepAddressDigitalIdApi';
import type { StepAddressSupportingDocumentApi } from './stepAddressSupportingDocumentApi';
import type { StepIdentityDigitalIdApi } from './stepIdentityDigitalIdApi';
import type { StepIdentityPhotoIdApi } from './stepIdentityPhotoIdApi';
import type { StepIdentityVouchApi } from './stepIdentityVouchApi';
import type { SupportingDocumentEvidenceItemApi } from './supportingDocumentEvidenceItemApi';
import type { VerifyEmailCheckApi } from './verifyEmailCheckApi';
import type { VerifyPhoneNumberCheckApi } from './verifyPhoneNumberCheckApi';
import type { VideoSelfieCheckApi } from './videoSelfieCheckApi';

export type VerificationCheck = VideoSelfieCheckApi | VerifyEmailCheckApi | VerifyPhoneNumberCheckApi | ReviewUserCheckApi | PhotoIdEvidenceItemApi | SupportingDocumentEvidenceItemApi | BankAccountEvidenceItemApi | EvisaEvidenceItemApi | RefereeEvidenceItemApi | StepIdentityDigitalIdApi | StepIdentityPhotoIdApi | StepIdentityVouchApi | StepAddressDigitalIdApi | StepAddressCreditReferenceAgencyApi | StepAddressSupportingDocumentApi;
