/* tslint:disable */
/* eslint-disable */
/**
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven\'t already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckStatus } from './CheckStatus';
import {
    CheckStatusFromJSON,
    CheckStatusFromJSONTyped,
    CheckStatusToJSON,
    CheckStatusToJSONTyped,
} from './CheckStatus';
import type { VideoSelfieValidations } from './VideoSelfieValidations';
import {
    VideoSelfieValidationsFromJSON,
    VideoSelfieValidationsFromJSONTyped,
    VideoSelfieValidationsToJSON,
    VideoSelfieValidationsToJSONTyped,
} from './VideoSelfieValidations';

/**
 * 
 * @export
 * @interface VideoSelfieEvidenceItem
 */
export interface VideoSelfieEvidenceItem {
    /**
     * 
     * @type {VideoSelfieValidations}
     * @memberof VideoSelfieEvidenceItem
     */
    validations: VideoSelfieValidations;
    /**
     * 
     * @type {string}
     * @memberof VideoSelfieEvidenceItem
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoSelfieEvidenceItem
     */
    artefact_key: string | null;
    /**
     * 
     * @type {CheckStatus}
     * @memberof VideoSelfieEvidenceItem
     */
    status: CheckStatus;
}



/**
 * Check if a given object implements the VideoSelfieEvidenceItem interface.
 */
export function instanceOfVideoSelfieEvidenceItem(value: object): value is VideoSelfieEvidenceItem {
    if (!('validations' in value) || value['validations'] === undefined) return false;
    if (!('artefact_key' in value) || value['artefact_key'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VideoSelfieEvidenceItemFromJSON(json: any): VideoSelfieEvidenceItem {
    return VideoSelfieEvidenceItemFromJSONTyped(json, false);
}

export function VideoSelfieEvidenceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoSelfieEvidenceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'validations': VideoSelfieValidationsFromJSON(json['validations']),
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'artefact_key': json['artefact_key'],
        'status': CheckStatusFromJSON(json['status']),
    };
}

export function VideoSelfieEvidenceItemToJSON(json: any): VideoSelfieEvidenceItem {
    return VideoSelfieEvidenceItemToJSONTyped(json, false);
}

export function VideoSelfieEvidenceItemToJSONTyped(value?: VideoSelfieEvidenceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validations': VideoSelfieValidationsToJSON(value['validations']),
        'created_at': value['created_at'],
        'artefact_key': value['artefact_key'],
        'status': CheckStatusToJSON(value['status']),
    };
}

