/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Vouchsafe API docs
 * Vouchsafe offers a REST API to conduct operations programmatically.

You can request and manage verifications, as well as perform smart lookups.

To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.

We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 * OpenAPI spec version: 0.1.0
 */
import type {
  ApiErrorResponse,
  AuthenticateInput,
  AuthenticateResponse,
  CreateDigitalIdSessionInput,
  CreateDigitalIdSessionResponse,
  CreateTeamInput,
  CreateTeamResponse,
  DigitalIdSession,
  EvisaVerificationInput,
  EvisaVerificationResponse,
  Flow,
  GetArtefactsResponse,
  GetSmartLookupResponse,
  GetVerificationResponse,
  ListDigitalIdSessionsResponse,
  ListFlowsResponse,
  ListSessionsParams,
  ListVerificationsParams,
  ListVerificationsResponse,
  PostcodeResponse,
  RequestVerificationInput,
  RequestVerificationResponse,
  SearchPostcodeParams,
  SmartLookupInput,
  SupportingDocumentVerificationResponse,
  Team,
  VerifySupportingDocumentBody
} from './models';


/**
 * <div style="background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;">
<strong style="color: #c62828;">Experimental (beta):</strong> This feature is new and currently in beta.
</div>

Extract and validate a supporting document.

This endpoint accepts a document file (PDF, JPG, or PNG) and extracts personal identity information and address details.

**Request format:** This endpoint accepts `multipart/form-data` with:
- `document` - The document file (PDF, JPG, or PNG, max 10MB)
- `sub_type` (required) - The type of document (e.g., `BankStatement`, `UtilityBill`). See "Supported document types" below.
- `minimum_document_length` (optional) - Minimum document age in months. Documents older than this will fail the `document_age_valid` check.

**Supported document types (`sub_type`):**
- `Payslip` - Employment payslips
- `PensionAnnualStatement` - Pension statements
- `BenefitsLetter` - Government benefits letters
- `HMPPSLetter` - Probation service letters
- `NHSLetter` - NHS correspondence
- `BankStatement` - Bank account statements
- `CreditCardStatement` - Credit card statements
- `MortgageStatement` - Mortgage statements
- `UtilityBill` - Gas, electricity, water bills
- `MobilePhoneBill` - Mobile phone bills

**Validations performed:**
- `required_fields_extracted` - Key identity fields were successfully extracted. These are: `first_name`, `last_name`, `first_line_of_address` and `postcode`
- `category_match` - Document matches the specified sub_type
- `document_age_valid` - Document is within acceptable age range (only if `minimum_document_length` provided)
- `document_complete_and_legible` - Document is complete and readable
- `tampering_signals_check` - No signs of document tampering detected

Sandbox testing:
In sandbox mode, the endpoint returns a mock "pass" response with sandbox values. No actual document processing occurs.

> **Request behaviour:** This is a synchronous endpoint. Processing typically takes 5-15 seconds
> depending on document complexity.

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type verifySupportingDocumentResponse200 = {
  data: SupportingDocumentVerificationResponse
  status: 200
}

export type verifySupportingDocumentResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type verifySupportingDocumentResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type verifySupportingDocumentResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type verifySupportingDocumentResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type verifySupportingDocumentResponse503 = {
  data: ApiErrorResponse
  status: 503
}

export type verifySupportingDocumentResponseSuccess = (verifySupportingDocumentResponse200) & {
  headers: Headers;
};
export type verifySupportingDocumentResponseError = (verifySupportingDocumentResponse400 | verifySupportingDocumentResponse401 | verifySupportingDocumentResponse403 | verifySupportingDocumentResponse422 | verifySupportingDocumentResponse503) & {
  headers: Headers;
};

export type verifySupportingDocumentResponse = (verifySupportingDocumentResponseSuccess | verifySupportingDocumentResponseError)

export const getVerifySupportingDocumentUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/verify/supporting-documents`
}

export const verifySupportingDocument = async (verifySupportingDocumentBody: VerifySupportingDocumentBody, options?: RequestInit): Promise<verifySupportingDocumentResponse> => {
    const formData = new FormData();
formData.append(`document`, verifySupportingDocumentBody.document);
formData.append(`sub_type`, verifySupportingDocumentBody.sub_type);
if(verifySupportingDocumentBody.minimum_document_length !== undefined) {
 formData.append(`minimum_document_length`, verifySupportingDocumentBody.minimum_document_length);
 }

  const res = await fetch(getVerifySupportingDocumentUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: verifySupportingDocumentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as verifySupportingDocumentResponse
}



/**
 * <div style="background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;">
<strong style="color: #c62828;">Experimental (beta):</strong> This feature is new and currently in beta.
</div>

Verify a person's UK eVisa using their Home Office share code.

This endpoint allows you to verify a person's `immigration status`, `right to work`, or `right to rent` eVisa
by providing their share code and date of birth. The share code is obtained by
the individual from the UK Home Office online service.

**Supported verification types:**
- `ImmigrationStatus` - Check a person's immigration status (e.g., Settled, Skilled Worker, Youth Mobility Scheme)
- `RightToWork` - Check a person's right to work in the UK
- `RightToRent` - Check a person's right to rent property in the UK

> **Request behaviour:** This is a synchronous endpoint. It can take up to 20 seconds.

**Response fields by sub-type:**
The response fields directly reflect the information available on a particular eVisa sub-type.
On a `pass` outcome, all fields for the sub-type will be populated. On a `fail` outcome, `extracted_details` may be partially populated or empty depending on which validation step failed.

**Response summary:**
| HTTP Status | Meaning | Action |
|-------------|---------|--------|
| `200` | Verification completed | Check the `outcome` field to determine if the verification was successful |
| `422` | Share code locked out by GOV.UK | Retry with a new share code |
| `503` | Service temporarily unavailable | Retry with exponential backoff |

**Billing:**
An API call is billable when the eVisa was found on GOV.UK, regardless of whether the verification
outcome is `pass` or `fail`. If the `share_code` or `date_of_birth` is invalid and no eVisa can be
retrieved, the response will have `billable: false` and you will not be charged.
Error responses (`HTTP 422`, `HTTP 503`) are also not billable and return an Error response body.

**Artefacts:**
On a successful response, artefacts are returned inline with pre-signed download URLs.
You have **30 minutes** to download them before the URLs expire.


**Sandbox testing:**
Use these share codes in sandbox mode to test different outcomes:
- `PASS12345` - Returns a successful verification with "Pass" outcome
- `FAIL12345` - Returns a failed verification (e.g. expired status)
- `ERROR1234` - Returns an error response
- `BADCODE12` - Returns a non-billable failed verification (e.g. invalid share code)
- `WRONGDOB1` - Returns a non-billable failed verification (e.g. wrong date of birth)

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type verifyEvisaResponse200 = {
  data: EvisaVerificationResponse
  status: 200
}

export type verifyEvisaResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type verifyEvisaResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type verifyEvisaResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type verifyEvisaResponse422 = {
  data: ApiErrorResponse
  status: 422
}

export type verifyEvisaResponse503 = {
  data: ApiErrorResponse
  status: 503
}

export type verifyEvisaResponseSuccess = (verifyEvisaResponse200) & {
  headers: Headers;
};
export type verifyEvisaResponseError = (verifyEvisaResponse400 | verifyEvisaResponse401 | verifyEvisaResponse403 | verifyEvisaResponse422 | verifyEvisaResponse503) & {
  headers: Headers;
};

export type verifyEvisaResponse = (verifyEvisaResponseSuccess | verifyEvisaResponseError)

export const getVerifyEvisaUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/verify/evisa`
}

export const verifyEvisa = async (evisaVerificationInput: EvisaVerificationInput, options?: RequestInit): Promise<verifyEvisaResponse> => {
  
  const res = await fetch(getVerifyEvisaUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      evisaVerificationInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: verifyEvisaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as verifyEvisaResponse
}



/**
 * Request a new verification.

Provide the user's email and the ID of one of your verification flows to send them through.

Vouchsafe will respond with:

- a URL to redirect to the user to
- a unique ID for you to track the verification

If you have enabled "On request creation" emails in your flow, this also sends them an email.

You can optionally provide more information/claims about the user, like their name, date of birth and address. Any that are provided will be checked against evidence the user gives.

If you do provide additional information about your user, you should let them know the information you are expecting them to verify. This helps prevent users getting stuck when the evidence they have does not match what you have provided.

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type requestVerificationResponse201 = {
  data: RequestVerificationResponse
  status: 201
}

export type requestVerificationResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type requestVerificationResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type requestVerificationResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type requestVerificationResponseSuccess = (requestVerificationResponse201) & {
  headers: Headers;
};
export type requestVerificationResponseError = (requestVerificationResponse400 | requestVerificationResponse401 | requestVerificationResponse403) & {
  headers: Headers;
};

export type requestVerificationResponse = (requestVerificationResponseSuccess | requestVerificationResponseError)

export const getRequestVerificationUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/verifications`
}

export const requestVerification = async (requestVerificationInput: RequestVerificationInput, options?: RequestInit): Promise<requestVerificationResponse> => {
  
  const res = await fetch(getRequestVerificationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestVerificationInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: requestVerificationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as requestVerificationResponse
}



/**
 * List all verifications for your team.

This can be a long list, so filtering by status is recommended.

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type listVerificationsResponse200 = {
  data: ListVerificationsResponse
  status: 200
}

export type listVerificationsResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type listVerificationsResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type listVerificationsResponseSuccess = (listVerificationsResponse200) & {
  headers: Headers;
};
export type listVerificationsResponseError = (listVerificationsResponse400 | listVerificationsResponse401) & {
  headers: Headers;
};

export type listVerificationsResponse = (listVerificationsResponseSuccess | listVerificationsResponseError)

export const getListVerificationsUrl = (params?: ListVerificationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://app.vouchsafe.id/api/v1/verifications?${stringifiedParams}` : `https://app.vouchsafe.id/api/v1/verifications`
}

export const listVerifications = async (params?: ListVerificationsParams, options?: RequestInit): Promise<listVerificationsResponse> => {
  
  const res = await fetch(getListVerificationsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listVerificationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listVerificationsResponse
}



/**
 * Get a single verification by ID.

Returns the latest status, claim details and results for a verification you previously requested.

Vouchsafe will respond with:

- the verification status and timestamps
- the identity claim details (e.g. name, email, phone number)
- the list of checks performed (e.g. liveness, photo ID, email verification) including outcomes and validations
- results of any background checks (e.g. radar, online footprint analysis, aml sanctions)

#### Downloading files (artefacts)

Some checks may include an `artefacts` array (for example: face scan or document images).
For security reasons, the verification response only contains an `artefact key` — not the file itself.

To download an artefact, use:

- `GET /artefacts/{artefact_key}`

This returns a **time-limited pre-signed URL** which can be used to download the file.

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type getVerificationResponse200 = {
  data: GetVerificationResponse
  status: 200
}

export type getVerificationResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getVerificationResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getVerificationResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getVerificationResponseSuccess = (getVerificationResponse200) & {
  headers: Headers;
};
export type getVerificationResponseError = (getVerificationResponse400 | getVerificationResponse401 | getVerificationResponse404) & {
  headers: Headers;
};

export type getVerificationResponse = (getVerificationResponseSuccess | getVerificationResponseError)

export const getGetVerificationUrl = (id: string,) => {


  

  return `https://app.vouchsafe.id/api/v1/verifications/${id}`
}

export const getVerification = async (id: string, options?: RequestInit): Promise<getVerificationResponse> => {
  
  const res = await fetch(getGetVerificationUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getVerificationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getVerificationResponse
}



/**
 * Create a new team (Partners only).

Creates a new team with the specified configuration and admin users.

Vouchsafe will respond with:

- a unique team ID for tracking
- the team name and public-facing name
- client credentials to authenticate team API requests
- creation timestamp (ISO 8601 format)

The provided admin emails will be granted administrative access to manage the team's settings and workflows.

**Note:** This endpoint requires a valid partner token in the `X-Partner-Token` header.
 */
export type createTeamResponse200 = {
  data: CreateTeamResponse
  status: 200
}

export type createTeamResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type createTeamResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type createTeamResponseSuccess = (createTeamResponse200) & {
  headers: Headers;
};
export type createTeamResponseError = (createTeamResponse400 | createTeamResponse401) & {
  headers: Headers;
};

export type createTeamResponse = (createTeamResponseSuccess | createTeamResponseError)

export const getCreateTeamUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/team`
}

export const createTeam = async (createTeamInput: CreateTeamInput, options?: RequestInit): Promise<createTeamResponse> => {
  
  const res = await fetch(getCreateTeamUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTeamInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createTeamResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTeamResponse
}



/**
 * 
Get the currently authenticated team.

Helpful for testing, especially when managing multiple client IDs and secrets.

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type getTeamResponse200 = {
  data: Team
  status: 200
}

export type getTeamResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getTeamResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getTeamResponseSuccess = (getTeamResponse200) & {
  headers: Headers;
};
export type getTeamResponseError = (getTeamResponse400 | getTeamResponse401) & {
  headers: Headers;
};

export type getTeamResponse = (getTeamResponseSuccess | getTeamResponseError)

export const getGetTeamUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/team`
}

export const getTeam = async ( options?: RequestInit): Promise<getTeamResponse> => {
  
  const res = await fetch(getGetTeamUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTeamResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTeamResponse
}



/**
 * Run quick [background checks](https://help.vouchsafe.id/en/articles/11075009-how-background-checks-work) on a user's details.

Provide the user's details and the check(s) to run and receive the report.

First line of address should be taken from the results returned by the [`GET /postcode` endpoint](https://app.vouchsafe.id/docs/operations/SearchPostcode).

The supported checks are:
  - `CreditBureau` checking credit reference agency data, plus public data like the electoral roll
  - `OnlineFootprint` checking against public traces of the user's online activity
  - `AML` checking international sanctions database, watchlists and other lists of high-risk people

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type performSmartLookupResponse201 = {
  data: GetSmartLookupResponse
  status: 201
}

export type performSmartLookupResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type performSmartLookupResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type performSmartLookupResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type performSmartLookupResponseSuccess = (performSmartLookupResponse201) & {
  headers: Headers;
};
export type performSmartLookupResponseError = (performSmartLookupResponse400 | performSmartLookupResponse401 | performSmartLookupResponse403) & {
  headers: Headers;
};

export type performSmartLookupResponse = (performSmartLookupResponseSuccess | performSmartLookupResponseError)

export const getPerformSmartLookupUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/smart-lookups`
}

export const performSmartLookup = async (smartLookupInput: SmartLookupInput, options?: RequestInit): Promise<performSmartLookupResponse> => {
  
  const res = await fetch(getPerformSmartLookupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      smartLookupInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: performSmartLookupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as performSmartLookupResponse
}



/**
 * Look up all addresses for a given UK postcode.

Useful for guaranteeing that a user's address is recognised before onboarding.
 */
export type searchPostcodeResponse200 = {
  data: PostcodeResponse
  status: 200
}

export type searchPostcodeResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type searchPostcodeResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type searchPostcodeResponse403 = {
  data: ApiErrorResponse
  status: 403
}

export type searchPostcodeResponseSuccess = (searchPostcodeResponse200) & {
  headers: Headers;
};
export type searchPostcodeResponseError = (searchPostcodeResponse400 | searchPostcodeResponse401 | searchPostcodeResponse403) & {
  headers: Headers;
};

export type searchPostcodeResponse = (searchPostcodeResponseSuccess | searchPostcodeResponseError)

export const getSearchPostcodeUrl = (params: SearchPostcodeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://app.vouchsafe.id/api/v1/smart-lookups/postcode?${stringifiedParams}` : `https://app.vouchsafe.id/api/v1/smart-lookups/postcode`
}

export const searchPostcode = async (params: SearchPostcodeParams, options?: RequestInit): Promise<searchPostcodeResponse> => {
  
  const res = await fetch(getSearchPostcodeUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: searchPostcodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchPostcodeResponse
}



/**
 * 
Get a list of all the currently published verification flows.

Use an ID from one of these flows to request verifications with the  [`POST /verifications` endpoint](https://app.vouchsafe.id/docs/operations/RequestVerification).

Referee-specific verification flows cannot be started independently, so are not returned by this endpoint.

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type listFlowsResponse200 = {
  data: ListFlowsResponse
  status: 200
}

export type listFlowsResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type listFlowsResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type listFlowsResponseSuccess = (listFlowsResponse200) & {
  headers: Headers;
};
export type listFlowsResponseError = (listFlowsResponse400 | listFlowsResponse401) & {
  headers: Headers;
};

export type listFlowsResponse = (listFlowsResponseSuccess | listFlowsResponseError)

export const getListFlowsUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/flows`
}

export const listFlows = async ( options?: RequestInit): Promise<listFlowsResponse> => {
  
  const res = await fetch(getListFlowsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listFlowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listFlowsResponse
}



/**
 * 
Get a specific verification flow.

Use an ID from one of these flows to request verifications with the  [`POST /verifications` endpoint](https://app.vouchsafe.id/docs/operations/RequestVerification).

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type getFlowResponse200 = {
  data: Flow
  status: 200
}

export type getFlowResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getFlowResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getFlowResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getFlowResponseSuccess = (getFlowResponse200) & {
  headers: Headers;
};
export type getFlowResponseError = (getFlowResponse400 | getFlowResponse401 | getFlowResponse404) & {
  headers: Headers;
};

export type getFlowResponse = (getFlowResponseSuccess | getFlowResponseError)

export const getGetFlowUrl = (id: string,) => {


  

  return `https://app.vouchsafe.id/api/v1/flows/${id}`
}

export const getFlow = async (id: string, options?: RequestInit): Promise<getFlowResponse> => {
  
  const res = await fetch(getGetFlowUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getFlowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getFlowResponse
}



/**
 * <div style="background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;">
<strong style="color: #c62828;">Experimental:</strong> This feature is brand new. <a href="https://vouchsafe.id/contact">Contact us</a> to set it up.
</div>

Create a new Digital ID verification session.

This endpoint initiates a new identity verification session using Digital ID providers.
The session will generate a unique URL that can be used to start the verification flow.

You can optionally provide known claims about the user (e.g., their email, name, date of birth)
to pre-populate the verification form and improve the user experience.

The session will expire after a set period if not completed.
 */
export type createSessionResponse201 = {
  data: CreateDigitalIdSessionResponse
  status: 201
}

export type createSessionResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type createSessionResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type createSessionResponseSuccess = (createSessionResponse201) & {
  headers: Headers;
};
export type createSessionResponseError = (createSessionResponse400 | createSessionResponse401) & {
  headers: Headers;
};

export type createSessionResponse = (createSessionResponseSuccess | createSessionResponseError)

export const getCreateSessionUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/digital-id/sessions`
}

export const createSession = async (createDigitalIdSessionInput: CreateDigitalIdSessionInput, options?: RequestInit): Promise<createSessionResponse> => {
  
  const res = await fetch(getCreateSessionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDigitalIdSessionInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createSessionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSessionResponse
}



/**
 * <div style="background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;">
<strong style="color: #c62828;">Experimental:</strong> This feature is brand new. <a href="https://vouchsafe.id/contact">Contact us</a> to set it up.
</div>

List Digital ID verification sessions.

Retrieve a list of Digital ID verification sessions for your team.
You can filter sessions by flow, status, provider, or creation date.

Each session includes verified claims and enrichments (Radar risk assessment and smart lookup results)
when available. The `enrichments` field will be `null` for sessions that haven't completed.

Use pagination parameters (`limit` and `offset`) to page through large result sets.
 */
export type listSessionsResponse200 = {
  data: ListDigitalIdSessionsResponse
  status: 200
}

export type listSessionsResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type listSessionsResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type listSessionsResponseSuccess = (listSessionsResponse200) & {
  headers: Headers;
};
export type listSessionsResponseError = (listSessionsResponse400 | listSessionsResponse401) & {
  headers: Headers;
};

export type listSessionsResponse = (listSessionsResponseSuccess | listSessionsResponseError)

export const getListSessionsUrl = (params?: ListSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://app.vouchsafe.id/api/v1/digital-id/sessions?${stringifiedParams}` : `https://app.vouchsafe.id/api/v1/digital-id/sessions`
}

export const listSessions = async (params?: ListSessionsParams, options?: RequestInit): Promise<listSessionsResponse> => {
  
  const res = await fetch(getListSessionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listSessionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSessionsResponse
}



/**
 * <div style="background-color: #ffebee; border-left: 4px solid #c62828; padding: 12px 16px; margin: 10px 0;">
<strong style="color: #c62828;">Experimental:</strong> This feature is brand new. <a href="https://vouchsafe.id/contact">Contact us</a> to set it up.
</div>

Get a Digital ID verification session by ID.

Retrieve details of a specific Digital ID verification session.
Returns the session status, verified claims, enrichments (including Radar risk assessment
and smart lookup results), and other session metadata.

The `enrichments` field will be `null` until the session reaches `completed` status.

Returns a 404 error if the session does not exist or does not belong to your team.
 */
export type getSessionResponse200 = {
  data: DigitalIdSession
  status: 200
}

export type getSessionResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getSessionResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getSessionResponseSuccess = (getSessionResponse200) & {
  headers: Headers;
};
export type getSessionResponseError = (getSessionResponse401 | getSessionResponse404) & {
  headers: Headers;
};

export type getSessionResponse = (getSessionResponseSuccess | getSessionResponseError)

export const getGetSessionUrl = (id: string,) => {


  

  return `https://app.vouchsafe.id/api/v1/digital-id/sessions/${id}`
}

export const getSession = async (id: string, options?: RequestInit): Promise<getSessionResponse> => {
  
  const res = await fetch(getGetSessionUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSessionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSessionResponse
}



/**
 * Get the access token, needed for all other API requests.

You will need your client ID and secret from the **API Integration** tab of the Vouchsafe dashboard.

Each access token is valid for 24 hours, after which you will need to re-authenticate.

Once you have an access token, pass it in future requests as a [Bearer token](https://workos.com/blog/understanding-bearer-tokens) in an `Authorization` header.

Use an [SDK or library](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) to simplify handling tokens

> This endpoint supports sandbox mode. [See how sandbox mode works](https://help.vouchsafe.id/en/articles/11979598-how-does-sandbox-mode-work).
 */
export type authenticateResponse201 = {
  data: AuthenticateResponse
  status: 201
}

export type authenticateResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type authenticateResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type authenticateResponseSuccess = (authenticateResponse201) & {
  headers: Headers;
};
export type authenticateResponseError = (authenticateResponse400 | authenticateResponse401) & {
  headers: Headers;
};

export type authenticateResponse = (authenticateResponseSuccess | authenticateResponseError)

export const getAuthenticateUrl = () => {


  

  return `https://app.vouchsafe.id/api/v1/authenticate`
}

export const authenticate = async (authenticateInput: AuthenticateInput, options?: RequestInit): Promise<authenticateResponse> => {
  
  const res = await fetch(getAuthenticateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authenticateInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authenticateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authenticateResponse
}



/**
 * Get an artefact download link.

For security reasons, other endpoints (e.g. `GET /verifications/{id}`) may return only an `artefact_key`.
Use this endpoint to exchange that key for a **time-limited pre-signed URL** that can be used
to download the file.

Vouchsafe will respond with:
- the requested `artefact_key`
- a `download_url` (pre-signed and time-limited)
- an `expires_at` timestamp (ISO 8601, UTC)

**Note:** The `download_url` will stop working after `expires_at`.
If it expires, request a new URL using this endpoint.
 */
export type getArtefactResponse200 = {
  data: GetArtefactsResponse
  status: 200
}

export type getArtefactResponse400 = {
  data: ApiErrorResponse
  status: 400
}

export type getArtefactResponse401 = {
  data: ApiErrorResponse
  status: 401
}

export type getArtefactResponse404 = {
  data: ApiErrorResponse
  status: 404
}

export type getArtefactResponseSuccess = (getArtefactResponse200) & {
  headers: Headers;
};
export type getArtefactResponseError = (getArtefactResponse400 | getArtefactResponse401 | getArtefactResponse404) & {
  headers: Headers;
};

export type getArtefactResponse = (getArtefactResponseSuccess | getArtefactResponseError)

export const getGetArtefactUrl = (artefactKey: string,) => {


  

  return `https://app.vouchsafe.id/api/v1/artefacts/${artefactKey}`
}

export const getArtefact = async (artefactKey: string, options?: RequestInit): Promise<getArtefactResponse> => {
  
  const res = await fetch(getGetArtefactUrl(artefactKey),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getArtefactResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getArtefactResponse
}



